### ISSUE TITLE
Error after dev server: Typescript package and config not included with Quick Start

### ISSUE THREAD

**Issue by adriancorcoran** [Shopify/quilt#1024]
## Overview

Just flagging this as it happened today in the current install. Looks like some typescript packages are missing from the install?

---

I was following the Quick Start guide in the main repo, after running `dev server` at this point:

![](https://screenshot.click/20-23-qifdl-r9b9k.jpg)

the following error is thrown:

<details><summary>Error output</summary>

```
=> Booting Puma
=> Rails 6.0.0 application starting in development
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.1 (ruby 2.6.3-p62), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.64.1:34092
Use Ctrl-C to stop
[error] sewing-kit cannot build a typescript project without typescript as a project dependency. Run yarn add typescript in your project directory and try again.
Error: sewing-kit cannot build a typescript project without typescript as a project dependency. Run yarn add typescript in your project directory and try again.
    at /Users/adriancorcoran/Repos/github.com/AdrianCorcoran/test-quilt-adrian/node_modules/@shopify/sewing-kit/dist/src/tools/typescript/verify-typescript-task.js:31:33
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adriancorcoran/Repos/github.com/AdrianCorcoran/test-quilt-adrian/node_modules/@shopify/sewing-kit/dist/src/tools/typescript/verify-typescript-task.js:4:58)
```

</details><br>

Looks like typescript is not installed? So I then followed the manual commands given underneath in the readme:

![](https://screenshot.click/20-27-xn9g3-e50ks.jpg)

After then running `dev server` I still got errors:

<details><summary>Error output</summary>

```
=> Booting Puma
=> Rails 6.0.0 application starting in development
=> Run `rails server --help` for more startup options
Puma starting in single mode...
* Version 3.12.1 (ruby 2.6.3-p62), codename: Llamas in Pajamas
* Min threads: 5, max threads: 5
* Environment: development
* Listening on tcp://192.168.64.1:34092
Use Ctrl-C to stop
[error] sewing-kit cannot build a typescript project without typescript as a project dependency. Run yarn add typescript in your project directory and try again.
Error: sewing-kit cannot build a typescript project without typescript as a project dependency. Run yarn add typescript in your project directory and try again.
    at /Users/adriancorcoran/Repos/github.com/AdrianCorcoran/test-quilt-adrian/node_modules/@shopify/sewing-kit/dist/src/tools/typescript/verify-typescript-task.js:31:33
    at Generator.next (<anonymous>)
    at fulfilled (/Users/adriancorcoran/Repos/github.com/AdrianCorcoran/test-quilt-adrian/node_modules/@shopify/sewing-kit/dist/src/tools/typescript/verify-typescript-task.js:4:58)
```

</details><br>

Same error? I then looked at the commands from the [Rails with Node walkthrough](https://docs.shopifycloud.com/getting_started/rails-with-node-walkthrough) and noticed that the following packages were installed there but not in the [quilt readme](https://github.com/Shopify/quilt/blob/master/gems/quilt_rails/README.md):

* typescript 
* @types/react 
* @types/react-dom

So I ran, `yarn add typescript @types/react @types/react-dom` and copied the `tsconfig.json` file example given in the Rails Walkthrough and everything then worked fine :)

Perhaps the quilt installer needs to be updated? As well as the [quilt readme](https://github.com/Shopify/quilt/blob/master/gems/quilt_rails/README.md) commands in the **Manual Install** section?

---

## Consuming repo

My own simple test repo: https://github.com/adriancorcoran/test-quilt-adrian

### Scope

- Is this issue related to a specific package?

I'm not 100% sure on this one :)

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by GoodForOneFare** [comment]
cc @cartogram - looks like [template rework](https://github.com/Shopify/quilt/pull/947) has turned TypeScript into a hard dependency for all projects.  Was this intended?

**Comment by martenbjork** [comment]
✅ Just followed the same instructions and ran into the same issue. Attempted to follow the Quick start, but ended up filling in the gaps from the manual guide.

**Comment by adriancorcoran** [comment]
From the audit trail above, looks like this was done but not closed - closing now :)
