### ISSUE TITLE
Automate 'X-Shopify-Server-Side-Rendered' header addition for server-side GraphQL queries

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1030]
## Overview
Right now, quilt_rails [has documentation about a CSRF strategy + SSR header](https://github.com/Shopify/quilt/blob/master/gems/quilt_rails/README.md#fixing-rejected-csrf-tokens-for-new-user-sessions), but this is quite easy to overlook.

If possible, a React-side library should automatically augment GraphQL requests with the `X-Shopify-Server-Side-Rendered` header.

**Comment by TheMallen** [comment]
Didn't realize it was a duplicate but I also opened https://github.com/Shopify/quilt/issues/1297 for the same thing. We should use that one because I've updated it with input from the security team.

**Comment by TheMallen** [comment]
Solved in latest versions of the packages :)
