### ISSUE TITLE
quilt_rails generator should install react/typescript versions that are guaranteed to be compatible with our stack

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1040]
## Overview
https://github.com/Shopify/quilt/pull/1038 added unbounded `typescript` / `react` / `react-dom` / `@types/react` / `@types/react-dom` installation.

At some point, one of these dependencies will get out of sync with the others, and bootstrapping an app will fail again.  We should avoid that.

## Type

- [x] Changes to existing features

## Motivation
Avoiding future breakages.

**Comment by TheMallen** [comment]
@michenly  seems related to what you're working on

**Comment by michenly** [comment]
The task was done. However, what actually shipped included much more including more in the generator and documentation update.
