### ISSUE TITLE
External error doesn't get cleared when the error is removed from externalErrors prop

### ISSUE THREAD

**Issue by felipenvaz** [Shopify/quilt#1041]
## Overview

I wrote a test to demonstrate the issue. It's on `quilt/form-state-external-errors`.

When an error is provided on the `externalErrors` prop, it is added to the `error` property of the specified field. If that error is removed from the `externalErrors` array, and the `onChange` function is not triggered on the field (if the external error needs async validation, for example), the error is not removed.

## Consuming repo

`partners`

**Comment by GoodForOneFare** [comment]
@TheMallen could you confirm that this is a bug, please?

**Comment by lemonmade** [comment]
@TheMallen reping
