### ISSUE TITLE
[react-server] requires ip, port and cdn in sewing-kit config

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/quilt#1051]
## Overview

I'm working on adding a playground for one of our experiments (https://github.com/Shopify/sandbox/pull/89). When adding the react-server setup, I ran into an issue where assets weren't loading. After some debugging, I figured out that configuring the plugins for `devServer` and `cdn` are required.

```ts
plugins.devServer({
  ip,
  port,
}),
plugins.cdn(assetPrefix),
```

Prior to that, I wasn't getting any CSS and my js files were returning my HTML document.

Since sewing-kit has some smart defaults around what port to start up at, I wonder if these could just be included automatically for these plugins. OR, throw an error if this are missing.

```ts
// localhost:8081 is the sewing-kit default for dev server
export const ip = process.env.IP || 'localhost';
export const port = process.env.PORT ? parseInt(process.env.PORT, 10) : 8081;

// localhost:8080 is the sewing-kit default build server
export const assetPrefix =
  process.env.CDN_URL || 'http://localhost:8080/webpack/assets/';
```

## Consuming repo

https://github.com/Shopify/sandbox/pull/89

cc @cartogram @GoodForOneFare

**Comment by TheMallen** [comment]
@macdonaldr93  any idea if this is still an issue? I think we handle this, but I thought it had from the start so maybe something about this case in particular was a problem?

**Comment by macdonaldr93** [comment]
Hey @TheMallen I'm not sure anymore and I don't have a repo I can test this with easily. We can close for now if you want

**Comment by TheMallen** [comment]
Cool thanks
