### ISSUE TITLE
Verify quilt_rails in public apps

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1055]
## Overview

Most quilt_rails apps use a Shopify gem that sends users through an oauth flow before they see any site content.  This is great for security but:
- It means that quilt_rails apps are guaranteed to have an existing session
- quilt_rails _may_ have unknown assumptions about sessions baked into itself
- We need to find and 🔥 any of these assumptions for this to be usable in public apps

It's possible that everything Just Works, though¯\\_(ツ)_/¯

**Comment by cartogram** [comment]
Created https://github.com/Shopify/hydrox to verify this. It seems to work well at https://hydrox.shopifycloud.com/

**Comment by GoodForOneFare** [comment]
Renamed this so that it can be closed :p  Fixing first request is a separate issue: #1077
