### ISSUE TITLE
Selectively disable SSR with a query parameter

### ISSUE THREAD

**Issue by amooz** [Shopify/quilt#1075]
## Overview
When debugging, sometimes SSR is the most annoying thing in the world.  It would be great if we could disable it selectively with a query parameter like `?ssr=false` and refresh the page.  The query param should persist such that I can refresh to my hearts content, knowing my local client is rendering the page for me.

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

...

## Labels

- [x] Add the `Type: Feature Request` label to this issue.

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

- Is it related to a new package?
  - [ ] Tag it with the `New package` Label

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by michenly** [comment]
can you give some more context on why SSR is annoying while debugging?
does this mean you would like to app to always render on the client or just the graphql will always skip ssr.
