### ISSUE TITLE
Deprecation warnings for Performance API usage

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#1090]
When running our performance libraries in web, I see the following warnings:

![Screen Shot 2019-10-03 at 12 22 21 PM](https://user-images.githubusercontent.com/3012583/66145331-9959b300-e5d8-11e9-9637-d0c8c935b6d0.png)

cc/ @TheMallen @michenly maybe something that could be addressed in your sprint if you have time?

**Comment by michenly** [comment]
`The PerformanceObserver does not support buffered flag with the entryTypes argument.`
from https://github.com/Shopify/quilt/blob/c5721a6104343c2b46a13bfd0d6dd50ab5797c6a/packages/performance/src/utilities.ts#L42-L45


`Deprecated API for given entry type.`
from https://github.com/Shopify/quilt/blob/c5721a6104343c2b46a13bfd0d6dd50ab5797c6a/packages/performance/src/utilities.ts#L31

**Comment by lemonmade** [comment]
I logged out the entry type before each of the warnings:

![Screen Shot 2019-10-17 at 10 24 48 AM](https://user-images.githubusercontent.com/3012583/67162902-ea86d800-f336-11e9-9098-6f677f4b1b7a.png)

**Comment by donnielrt** [comment]
It would be awesome if we could get rid of these, they really do clutter up the console!

**Comment by atesgoral** [comment]
The deprecated API warning is easy to repro in the dev console: 

```
performance.getEntriesByType('longtask')
VM179:1 Deprecated API for given entry type.
```

But I still haven't been able to track down any spec around what/why is deprecated and what the course of action is.
