### ISSUE TITLE
Decide on a scalable quilt_rails architecture

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1100]
## Overview
quilt_rails should have a recommended architecture that scales far beyond its current limitations.  

For now, this discussion will happen in internal channels.  Ping me in Slack if you'd like more context.

## Motivation
Deadlocks in Puma (see #1059 for more information).

**Comment by GoodForOneFare** [comment]
This is a rough version of the architecture that we'll work towards with prod eng:

<img width="935" alt="Private Rails for Node - draw io 2020-01-07 15-48-49" src="https://user-images.githubusercontent.com/673655/72161518-4426fd80-338e-11ea-87f0-2eed3762371d.png">

There'll be some improvements along the way, of course.

**Comment by TheMallen** [comment]
Closing this, as the architecture is decided. Tracking in a private issue since it's Shopify specific.
