### ISSUE TITLE
`react-server-webpack-plugin` should pass URL for location on client and server

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#1115]
Right now, we pass in `location={ctx.request.url}` to the application during SSR as part `@shopify/react-server-webpack-plugin`. There are four problems with this:

1. It probably won't line up with what our own react router will accept
2. It is a pain to parse information out of
3. It does not contain any information about the origin of the request
4. It is not automatically passed down during the client render, which may be unexpected

I think the best way to resolve this is to:

1. Pass `url={ctx.request.URL}` instead, which is a proper `URL` object
2. Pass in this value on the client also as a convenience

Any thoughts @TheMallen @michenly?

**Comment by TheMallen** [comment]
This makes a lot of sense to me, I'm not sure that it isn't confusing to pass it to the client if it never updates. One might naively expect the client receiving something called "location" to mean it would actually be up to date. Maybe it should be called something like "initialLocation" or "originalUrl"?

**Comment by lemonmade** [comment]
I don't think people should expect that, because there is no way for React props on the root component to be changed after the fact (or if there is, no one uses it). This would also only be a problem if they assumed it was automatically reactive to the current URL, and chose not to use any routing solution, and actually have more than one route, which seems like a pretty small edge case to satisfy with a more awkward API, IMO.
