### ISSUE TITLE
Look into bringing in VSCode plugin for react-i18n

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#1116]
@mohebifar did an amazing job on a VSCode plugin for react-i18n (https://github.com/mohebifar/vscode-shopify-i18n). Is there a way it would fit naturally into this monorepo?

**Comment by mohebifar** [comment]
Absolutely! There's just a few things we need to address:

1. We don't need to publish the package on npm. I don't know how easy that would be to exclude this package from lerna.
1. We may want to consider automatic deploy of the extension using `vsce`.
1. The extension currently has not tests. 😬
1. It has no docs.
