### ISSUE TITLE
Respect `prefix` in enable cookie route

### ISSUE THREAD

**Issue by timolins** [Shopify/quilt#1148]
## Overview

The redirect introduced with #1022 doesn't apply the prefix. This means all requests get forwarded to `/auth` instead of `/my-prefix/auth`. 

## Consuming repo

> What repo were you working in when this issue occurred?

koa-shopify-auth

**Comment by scotttrinh** [comment]
@timolins 

I think you need to sign the CLA to get your PR merged. I'm running into this issue now, too, and would love to help get this over the finish line.

**Comment by timolins** [comment]
I think you a right, but I wasn't able to find more information about this. They should probably add a few words about this in [`CONTRIBUTING.md`](https://github.com/Shopify/quilt/blob/master/.github/CONTRIBUTING.md).

**Comment by scotttrinh** [comment]
@timolins 

If you click through the details on the failed check I think it'll walk you through it, but I haven't done it so it's a bit opaque to me, too. Definitely worth mentioning in the contribution guide!

**Comment by timolins** [comment]
Thanks for the hint! Just signed the CLA and the bot is happy now.

**Comment by eugene-kim** [comment]
I'm running into this issue as well and it's great see that there's a fix ready to go. Is there anything preventing the PR from being merged besides the review and the branches being out of sync?

**Comment by scotttrinh** [comment]
I have a fork with @timolins' fix merged published to npm while we're waiting if anyone here cares to use it. As soon as this lands in quilt, I plan on deprecating it, so if you're like me and just need to get it working, [@cala/koa-shopify-auth](https://www.npmjs.com/package/@cala/koa-shopify-auth) can hold you over for now.

**Comment by junaid33** [comment]
Facing the same issue. @shopify/koa-shopify-auth works sometimes and sometimes it says page not found. This issue is causing our application to be rejected from the Shopify App Store. The package is updated but we are using a prefix.

**Comment by TheMallen** [comment]
I believe this was fixed in #1440. Feel free to reopen if the issue persists.

**Comment by dooman87** [comment]
@TheMallen I believe this issue has been fixed only partially. I created a PR #1498 which should finally fix this. Appreciate if you could have a look.
