### ISSUE TITLE
Create @shopify/react-error-boundary

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#115]
We should pull out our custom [`<ErrorBoundary />`](https://github.com/Shopify/neutron/blob/master/app/foundation/components/ErrorBoundary/ErrorBoundary.tsx#L22) component.

**Comment by michenly** [comment]
Is there a universal `ErrorBoundary` that can be pull out?

**Comment by posth** [comment]
Looking at the `web` repo, there are a couple generic `ErrorBoundary` components:

- [app/components/ErrorBoundary/ErrorBoundary.tsx](https://github.com/Shopify/web/blob/master/app/components/ErrorBoundary/ErrorBoundary.tsx)
- [app/foundation/ErrorBoundary/ErrorBoundary.tsx](https://github.com/Shopify/web/blob/master/app/foundation/ErrorBoundary/ErrorBoundary.tsx)

Maybe one of these or a combination of both can be used?
