### ISSUE TITLE
Bug: react-shopify-app-route-propagator is using the soon to be deprecated iframe name

### ISSUE THREAD

**Issue by vividviolet** [Shopify/quilt#1150]
## Overview

A bunch of apps are utilizing `quilt/react-shopify-app-route-propagator` to synchronize the app's url with the browser url. This package relies on the iframe name in order to skip the url synch when rendered in modal. 

Iframe names are being deprecated as they are unreliable, especially on Mobile, which might not render an iframe at all. It also was always an unadvertised hack added in by 1P developers.

**Fix**

Use `app.getState('context')` to figure out whether the app is rendered in a modal

## Consuming repo

> https://github.com/Shopify/buy-button
> https://github.com/Shopify/facebook-marketplace
> many more apps: https://github.com/search?q=react-shopify-app-route-propagator&type=Code

**Comment by michenly** [comment]
@vividviolet I had chatted with @gf3 briefly before about this, but this might be an good opportunity to remove the `react-shopify-app-route-propagator` package all together and move the implementation into `@shopify/app-bridge-react`.

What do you think?

**Comment by vividviolet** [comment]
Yes, we can take the opportunity to remove this package from quilt. Maybe putting in `@shopify/app-bridge-react` makes sense. The only thing to note is that we do not support hooks in app-bridge-react yet.

cc @gf3 @iainmcampbell

**Comment by gf3** [comment]
indeed, however we should 😅

**Comment by iainmcampbell** [comment]
Trish moved route propagator to app bridge react in https://github.com/Shopify/app-bridge/issues/1303
