### ISSUE TITLE
`refetch` from `useQuery` does not update data after a network error in React Native

### ISSUE THREAD

**Issue by josephroquedev** [Shopify/quilt#1157]
## Overview

When using the `useQuery` hook in a React Native environment, I am experiencing an issue where `refetch` fails to update `data` and does not cause a re-render.

Reproduction:

1. Perform a query in a React Native environment, that succeeds.
2. Disconnect the data or turn off the server so the query will error out, then call `refetch` from the `useQuery` hook.
3. The query will fail and `data` will become `undefined`
4. Reconnect (or restart the server) and call `refetch`. If you watch the network, the query **will** succeed and will fetch the new data, but the `useQuery` hook and `data` will not be updated, and the component will not re-render.

Might be related to: https://github.com/Shopify/quilt/issues/821

There's also a similar `react-apollo` issue that was fixed in the past: https://github.com/apollographql/react-apollo/issues/2070 but forcing this version does not fix in this repo.

## Consuming repo

> What repo were you working in when this issue occurred?
https://github.com/shopify/arrive-client

**Comment by warefhaque** [comment]
Having the exact same issue in https://github.com/Shopify/start-mobile. Has a workaround been found for this?

**Comment by sbalay** [comment]
Bump

**Comment by gavin-hinchley** [comment]
This issue affects `React` more generally also: `useQuery()` does not update after `refetch()` is called following `any graphql error`. 

This seems to be a bug within [@shopify/react-graphql -> useQuery()](https://github.com/Shopify/quilt/blob/main/packages/react-graphql/src/hooks/query.ts#L21) as `@apollo/react-hooks -> useQuery()` works as expected.

**Comment by vsumner** [comment]
I've identified the problem and will have a fix shortly.
