### ISSUE TITLE
react-intersection-observer does not provide all members of IntersectionObserverEntry

### ISSUE THREAD

**Issue by jamesism** [Shopify/quilt#1158]
## Overview

When using `react-intersection-observer` only the `isIntersecting` member of `IntersectionObserverEntry` is present on the returned `intersection` from `const [intersection] = useIntersection()`.  

This is because all of the members of `IntersectionObserverEntry` are non-enumerable, and the current implementation tries to spread them across an internal state setter which fails when transpiled to an `Object.assign`. The `isIntersecting` property is still present as it is [set as a guard for browser support](https://github.com/Shopify/quilt/blob/master/packages/react-intersection-observer/src/hooks.ts#L61).

I believe these properties are implemented as getters (or so it seems..) in order to be lazily loaded and avoid the performance hit of calculating bounding boxes unless the specific property is actually requested in user land. I have tried a solution that would copy that implementation directly (using `defineProperties` and `getOwnPropertyDescriptors`), but oddly enough the members of `IntersectionObserverEntry` are still not reported to `getOwnPropertyDescriptors` or `getOwnPropertyNames`. They are visible as keys in `for .. in` walk, but seemingly cannot be accessed with `getOwnPropertyDescriptor` either.

One possible solution is to directly set the `IntersectionObserverEntry` object as state, this would preserve the lazy loading of the expensive properties, but it would eliminate the current [browser support fallback](https://caniuse.com/#feat=intersectionobserver) for `isIntersecting`.

Another solution would be to manually copy the known properties:
```
setIntersectingEntry({
  isIntersecting: entry.isIntersecting || entry.intersectionRatio > 0,
  intersectionRatio: entry.intersectionRatio,
  intersectionRect: entry.intersectionRect,
  /* etc */
});
```

However as it may be a performance degradation to automatically include evaluated values of these properties, I don't think it is wise to copy them all. Perhaps as a compromise solution we could leave out the `DOMRectReadOnly` properties (`boundingClientRect`, `intersectingRect`, and `rootBounds`), and manually copy the other simple values. 

I can create a PR for either of these solutions, but am curious how others might prefer to proceed. Thanks!

## Consuming repo

> What repo were you working in when this issue occurred?

[start-web](https://github.com/Shopify/start-web)

**Comment by lemonmade** [comment]
Whether it's a performance issue or not it feels like we should stay away from copying the properties. I'd probably feel most comfortable if we saved the `IntersectionObserverEntry`, and just patch the instances to have the field if we see that the field is missing. Or, we could make this a polyfill instead, and patch `IntersectionObserverEntry.prototype`.
