### ISSUE TITLE
Add script to repo to remove a dependency from a package

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#119]
[Lerna currently doesn't have support for removing packages from the root](https://github.com/lerna/lerna/issues/833#issuecomment-375850356), this is a big pain as you basically need to manually remove stuff and then regenerate the lockfile afterwards atm.

One way we could get around this for now is to write a script we can use to do so ourselves. That said, it might be better to just open a PR on lerna to get this working.

**Comment by michenly** [comment]
Look into support in Lerna 2
