### ISSUE TITLE
[react-i18n] Add ability to supply inline fallback for `i18n.translate`

### ISSUE THREAD

**Issue by qq99** [Shopify/quilt#1194]
## Overview

We would like to translate ENUM from server, and do so dynamically with interpolating, e.g.,:

```tsx
i18n.translate(`SomeComponent.someConcept.${serverProvidedEnum}`)
```

This would raise if a new `serverProvidedEnum` is introduced, which will cause the app to stop working.  1 workaround is to wrap in `try/catch`, but it feels like there could be a nicer API.

@TheMallen mentions some alternative approaches at
https://discourse.shopify.io/t/provide-an-inline-fallback-translation-for-react-i18n-translate-calls/5279/2

However, they are still a bit more cumbersome than what we desire, which is closer to something like this:
```tsx
i18n.translate(serverProvidedEnum, {
  scope: 'SomeComponent.someConcept',
  default: i18n.translate(...) // my default string for when the key is not found
})
```

Here, `default` could also be named `fallback`

**Comment by TheMallen** [comment]
I don't think that the `getTranslationTree` approach ends up being all that clunky. In the example above it would just be:

```
const translations = i18n.getTranslationKey('SomeComponent.someConcept');

// later ...

<MySubComponent content={translations[someVariable] || translations.unknown}/>
```

Given the flexibility that API already gives and the relative rarity of the case I'm not sure it's worth adding an API.

That said, if it *was* going to be it's own API like this than  I'd rather see something like `fallbackKey` instead of `default` or `fallback` because it would enforce looking in the same `scope`, be less prone to having inlined string literals put in (thus breaking translatability) and not need another relatively costly traversal of all the different translation trees.

```
i18n.translate(serverProvidedEnum, {
  scope: 'SomeComponent.someConcept',
  fallbackKey: 'florpus',  // ends up as the value of `SomeComponent.someConcept.florpus`
})
```

I'm curious to hear other devs who use the API often's thoughts.

**Comment by qq99** [comment]
I like the concept of `fallbackKey` a lot

I think you're right, `getTranslationTree` isn't too bad (thankfully we have this mechanism!), but it also feels like a lesser known API and requires you to hold the tree into a constant, hampering your ability to inline things (requiring a minimum of 2 spots in code related to the concept vs. 1 spot)

**Comment by TheMallen** [comment]
Yeah, like I said I'd like to hear if other folks feel strongly about having an explicit API vs using the existing one

**Comment by adjnor** [comment]
The approach using `getTranslationTree` works but it does seem a bit overkill for the situation. I would say that method is mainly intended for situations where a set of related translations is needed and retrieving those one by one would introduce a lot more code.

In this example, we know which specific translation key we're looking for, only caveat being that the key might be missing in which case we need a fallback. The `fallbackKey` solution proposed by @TheMallen is quite simple and elegant and it seems to me to be more appropriate for this particular use case.

**Comment by patsissons** [comment]
We use `camelCase(enumValue)` frequently in Capital, composing into the key string. But this is not typically for raw enum content but rather dynamic content that is enum value driven. Search for `camelCase(financingType)` in web to see examples. We generally want things to fail fast if our enums were to unfortunately change on the backend without a heads up so our error tracking picks it up. We also have very stable enums that this is used for, so very little risk for translation errors.

**Comment by TheMallen** [comment]
it sounds like folks like `fallbackKey`, I'm going on vacation now though, if anyone wants to try to PR it in they can ping other folks on web-foundations though
