### ISSUE TITLE
jest-mock-apollo should not operate on globally mutable state and needs more passthrough options for building the client

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#120]
A few things:

1. The schema should not be determined by having some default path, then having the user overwrite that path, then lazily instantiating the schema when first called. Globally mutable state is pretty much always bad news.
2. There needs to be more pass through options for the client. You kinda-sorta allow the passing of the fragment matcher (again, in a weird way), but we need access to basically all the cache options (as shown here: https://github.com/Shopify/web/pull/4402/files#diff-79c4ff104d28ec7dab79444410e619c6R245)

I think you are better off having a factory here, where your library vends functions that can create a GraphQL client, with all the instantiation logic configurable by the user. For the schema in particular, I'd recommend just making them pass a function that you call once lazily, since that will allow for schemas in a variety of shapes.

**Comment by tzvipm** [comment]
Splitting this into 2 issues:
1: https://github.com/Shopify/quilt/issues/123
2: https://github.com/Shopify/quilt/issues/124

I'll tackle #124 first, as it may not require a breaking API change. #123 will require some more discussion and is not a blocker for the mentioned issue in `web`.
