### ISSUE TITLE
[quilt_rails] Expose header passing API from `reverse_proxy`

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1205]
## Problem Space

It's relatively common for apps to need some kind of initial (meta)data before they can do too much. With the current setup suggested by `quilt_rails` + `react-server` we push folks to use GraphQL for everything, which has a few unfortunate side-effects:
- to get simple trivial initial data (eg. custom locale preferences or other user specific metadata) we are forced to introduce waterfalling GraphQL requests which is a big performance no-no
- until we have our SSR GraphQL architecture sorted out it practically means that nothing can be server rendered (since the initial data request would not be able to be run on the server and nothing could be rendered before it is done)

In complex applications this gets worse, as we have seen in our largest React+GraphQL app where we actually have two different top level queries we need to run in series to figure out what sections we can render (and one we have to run before we even start rendering the app!)

Beyond the above, it's also a bit of DX bummer for extremely simple applications to need to setup graphQL before even the most trivial of data can be sent to their React app.

## Proposal

We already have a hook that we recommend devs use to access request headers inside the app

```ts
import {useRequestHeader} from '@shopify/react-network';

// ...

const someData = useRequestHeader('some-header');
```

On top of this, the gem we use internally to proxy requests to `react-server` exposes a `headers` option.

```ruby
reverse_proxy(headers: { foo: 'bar' })
```

If we were to just expose a similar option on `render_react` we could pretty easily support simple cases (specifically strings) being passed to the react app directly from Rails

```ruby
# ui_controller.rb

def index
  render_react(headers: {'x-custom-locale': current_user.custom_locale})
end
```

```tsx
// App.tsx
import {useRequestHeader} from '@shopify/react-network';

// ...
export function App() {
  const locale = useRequestHeader('x-custom-locale');
```

This setup would be a bit less nice for complex data, which is both a good thing (pushes users towards GraphQL for complex data needs), and a bad thing (might just mean they use it anyway and their code is worse). I think it's a sane API that will make 80% easy and 20% possible for our devs, and if we see a consistent need for data that it is a poor fit for we can do more then.

## Type
- [x] New feature

**Comment by TheMallen** [comment]
@jordanAtShopify  heard you might be interested in helping out with this

**Comment by jordanAtShopify** [comment]
@TheMallen Thanks for the awesome write-up!
