### ISSUE TITLE
I used koa-shopify-auth and submitted the application to the Shopify App Store and got this repsonse

### ISSUE THREAD

**Issue by junaid33** [Shopify/quilt#1211]
## Overview
I'm using koa-shopify-auth to install the application on shops, but when I submitted this application, I got this response:

When installing the app, the redirect goes to an app and API key that is different than the one associated with this submission. Please update keys in your app's code or update the app setup URLs in your Partner Dashboard. Please see this screenshot for additional details.

![image](https://user-images.githubusercontent.com/34615258/70273585-fbb56800-176f-11ea-83e9-d56f24133d3a.png)

The API key matches the one in our partner account and the HMAC is hashed so why are those compared?
...

## Consuming repo

> What repo were you working in when this issue occurred?
 koa-shopify-auth

...

## Labels
[Type: Bug]
- [ ] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by beatlecz** [comment]
Have you discovered what was the problem? thx

**Comment by junaid33** [comment]
It was a mistake on their end about comparing the wrong keys. Contact them and they should fix the issue.
