### ISSUE TITLE
[react-testing] Types issue with the new `@types/jest` version.

### ISSUE THREAD

**Issue by alexandcote** [Shopify/quilt#1212]
## Overview
I found an issue with our testing library when you have @type/jest > `24.0.19`.

For example, in the example bellow, typescript will complain about `id: 'bar'` with

>(property) id: string
>Type 'string' is not assignable to type 'never'.ts(2322)

```tsx
it('example', () => {
  const Foo = (_: {id: string}) => null;
  const wrapper = mount(<Foo id="bar" />);
  expect(wrapper.find(Foo)).toHaveReactProps({
    id: 'bar',
  });
});
```

<img width="650" alt="image" src="https://user-images.githubusercontent.com/4728325/70349852-94f98280-1833-11ea-86e7-ae239ddfdda6.png">

Temporary solution, add `"@types/jest": "24.0.19"` to the list of resolutions in your `package.json`

## Consuming repo

> What repo were you working in when this issue occurred?

Online-Store Web

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

cc @lemonmade

**Comment by GoodForOneFare** [comment]
Closing because I don't see any quilt packages that mandate use of `@types/jest` in consumers ¯
\\_(ツ)_/¯

**Comment by GoodForOneFare** [comment]
Sorry, I was lazy and didn't read the description properly.  Reopening 👍
