### ISSUE TITLE
`react-i18n` negative currency issue

### ISSUE THREAD

**Issue by Jurgyte** [Shopify/quilt#1234]
## Overview
I use `I18n.formatCurrency` to display a discount value, which is a negative price. This function returns `$-3.45`, but it should be `-$3.45`.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by movermeyer** [comment]
More context:

Some people expected this format, so we have previously used `$-3.45` for some regions.
However after some research (by `@winterweix`) we have recently decided that putting the `-` sign before the rest of the price is actually how we want it for all regions.

See the new Polaris guidelines: https://polaris.shopify.com/foundations/formatting-localized-currency#navigation

Aside: This has been fixed recently in [`shopify-i18n v1.1.4`](https://github.com/Shopify/shopify-i18n/pull/519)
