### ISSUE TITLE
[react-form] Use of useChoiceField results in Cannot read property 'dirty' of undefined

### ISSUE THREAD

**Issue by chaddjohnson** [Shopify/quilt#1261]
_Please note I do not have the ability to assign the "bug" label to this issue._

## Overview

When using `useChoiceField`, I get an error, `Cannot read property 'dirty' of undefined`. Here is a code snippet:

```jsx
import { useForm, useField, useChoiceField, notEmpty } from '@shopify/react-form';

const [product, setProduct] = useState(props.product);

const { fields, submit, submitting, dirty, reset } = useForm({
  fields: {
    name: useField({
      value: product.name,
      validates: [notEmpty("Name can't be blank")]
    }),
    showNotification: useChoiceField({
      value: product.showNotification,
      validates: []
    })
  },
  onSubmit: async form => {
    // ...
  }
});
```

I also tried

```jsx
useChoiceField(product.showNotification);
```

The error definitely occurs when using `useChoiceField`.

Here is my checkbox (the error occurs whether or not this checkbox is in place):

```jsx
<Checkbox label={`Show notification`} {...fields.showNotification} />
```

## Consuming repo

> What repo were you working in when this issue occurred?

Building my own app using Shopify Polaris.

**Comment by chaddjohnson** [comment]
@patsissons @TheMallen @michaelmelanson Any chance we can get this looked at? `useChoiceField` is broken.

**Comment by chaddjohnson** [comment]
Actually, it appears that the following works:

```javascript
showNotification: useField(useChoiceField(product.showNotification)),
```

If this is the correct way to utilize `useChoiceField`, it might make sense to update the documentation to reflect this.

**Comment by michaelmelanson** [comment]
I think it was my change in https://github.com/Shopify/quilt/pull/1296 that caused this, so I'll look into it for you. Sorry for the trouble. 

In the meantime I suggest going back to version 0.3.34 of `react-form` until this is resolved.

**Comment by chaddjohnson** [comment]
Thanks @michaelmelanson!

Also, I might have jumped the gun. When using

```javascript
showNotification: useField(useChoiceField(product.showNotification)),
```

I am seeing the following for checkbox item values (instead of `true`/`false`) in `formValues` in the `onSubmit` handler passed to `useForm()`:

<img width="688" alt="Screen Shot 2020-03-18 at 12 44 04 PM" src="https://user-images.githubusercontent.com/676134/76985297-64d37c80-6916-11ea-8332-3b6272df57ed.png">

**Comment by chaddjohnson** [comment]
@michaelmelanson Any news on this? Having this fixed would make react-form more usable.

**Comment by michaelmelanson** [comment]
Sorry for the delay here. I meant to get to this sooner, but with everything else going on I haven’t yet. 

It’s still on my radar, so I’ll get to it as soon as I can.

**Comment by chaddjohnson** [comment]
I found a workable solution.

For `Checkbox` fields, I'm using `useField` and `asChoiceField`:

```jsx
const showNotifications = useField(props.product.showNotifications);

// ...

<Checkbox label="Show notifications" {...asChoiceField(showNotifications)} />
```

This works great. However, `useChoiceField` does not work:

```jsx
const showNotifications = useChoiceField(props.product.showNotifications);

// ...

<Checkbox label="Show notifications" {...showNotifications} />
```

This results in `Uncaught TypeError: Cannot convert undefined or null to object`.

For `ChoiceList` fields, I am using `useField`:

```jsx
const notificationOptions = useField(props.product.notificationOptions);

<ChoiceList
  choices={[
    {
      label: 'Always',
      value: 'ALWAYS'
    },
    {
      label: 'Never',
      value: 'NEVER'
    }
  ]}
  selected={notificationOptions.value}
  onChange={([value]) => notificationOptions.onChange(value)}
/>
```

**Comment by pratiknikam** [comment]
@chaddjohnson that exactly solved my issue! Thanks a ton.
