### ISSUE TITLE
[graphql-universal-provider] automatically include `x-react-server-rendered`

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1297]
**Update:** comments below detail an improved proposal

## Overview

`quilt_rails` provides a custom CSRF policy that checks for some headers to indicate that a request came from a server rendered page. Currently these need to be manually added with an `if (server)` check in the `clientOptions` function passed to the graphQL provider. Let's make this nicer by just automatically adding that header when we are on the server.

## Motivation

It's easy to miss the details of how this should work when reading our docs and get blocked on CSRF errors.

**Comment by TheMallen** [comment]
After chatting with @JackMc  we may be able to add our custom header on **all** requests from the GraphQL provider (not just server rendered ones) and attain cross-site safety that way due to the fact that modern browsers block cross-site header setting.

**Comment by TheMallen** [comment]
Overall proposal:
- add Quilt::HeaderCsrfStrategy that just always checks a header
- deprecate the current CRSF strategy (but leave it around for now)
- add that header to the client created by the GraphQL provider by default
- update the docs to mention the strategy and that the provider handles it by default

**Comment by michenly** [comment]
Related issue https://github.com/Shopify/quilt/issues/1030
