### ISSUE TITLE
@shopify/address should have been a major bump.

### ISSUE THREAD

**Issue by TayKangSheng** [Shopify/quilt#1320]
## Overview

The minor bump of `@shopify/address` in #1301 should have been a major bump. This feature is [removed](https://github.com/Shopify/quilt/pull/1301/files#diff-e5f9487d6e99b48fb3ca92d674695b1dL82-L83) which is not backwards compatible. 

Previously when user uses a supported locale but unsupported variant, it would have default back to the supported locale. but now it defaults to `en` because of the fallback provided by CountryService. 

| user input | previous<br>output to<br>CountryService | current<br>output to<br>CountryService |  previous returned<br>locale from<br>CountryService | current returned<br>locale from<br>CountryService |
| :--- | :--- | :--- | :--- |  :--- |
| `en-AU` | `en` | `en-AU` | `en` | `en` |
| `pt-XX` | `pt` | `pt-XX` | `pt` | `en` |

## Motivation

Realised it when bumping `@shopify/address` in https://github.com/Shopify/web/pull/24461

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TayKangSheng** [comment]
@michenly @ismail-syed Any recommend approach for me to do this? Is it okay if I create another PR to add a line something like this to the changelog
```
- [breaking change] Update to `@shopify/address` [#1301](https://github.com/Shopify/quilt/pull/1301) is not backwards compatible [#1320](https://github.com/Shopify/quilt/issues/1320)
```

**Comment by ismail-syed** [comment]
@TayKangSheng, Yes that is correct

* Update changelog with a new major version mentioning that it is a breaking change. 
* Also, add this note in the mistaken minor bump

**Comment by ilamp** [comment]
Can this package be opened for external use for Shopify App Developers? We can most definitely use it.
