### ISSUE TITLE
[Polyfill] Intl.FormatNumber

### ISSUE THREAD

**Issue by alexandcote** [Shopify/quilt#1339]
## Overview
Browsers don't support the same set of features of `Intl.FormatNumber`.

For example, the `Scientific` and `Compact` notations are only supported on Chrome and Node 12.

We should probably add a [new polyfill](`https://github.com/formatjs/formatjs/blob/master/packages/intl-unified-numberformat`) so it will make things easier for folks who want to use it.

**Comment by alexandcote** [comment]
We should use https://github.com/Shopify/condense-number instead of `Intl.FormatNumber` with the compact notation.

**Comment by alexandcote** [comment]
After some discussion, `condense-number` doesn't seems to respect exactly the spec.

Here is the polyfill I found.

https://github.com/formatjs/formatjs/tree/master/packages/intl-unified-numberformat

**Comment by TheMallen** [comment]
Seems like this might want to just be another polyfill that lives in our polyfill package? Let me know if you would like me to review anything.

**Comment by alexandcote** [comment]
@Shopify/web-foundations since @TheMallen is off for his intermission.
