### ISSUE TITLE
Changelogs should be linted on publish

### ISSUE THREAD

**Issue by sambostock** [Shopify/quilt#1342]
Quilt has many packages, and it is easy for someone to miss moving the `UNRELEASED` section of a `CHANGELOG.md` into a versioned section on publish.

**This has unfortunately already occurred, as documented in #1341.**

Ideally, we would solve this on multiple fronts:

- Update `CHANGELOG.md` automatically on publish
- Lint `CHANGELOG.md` on publish, preventing invalid publication
  _This could be done naively by checking for the presence of `## UNRELEASED`, vs `<!-- ## UNRELEASED -->`.

**Comment by alexandcote** [comment]
Should we use conventional changelog? Lerna 3.0 had this feature built-in.
