### ISSUE TITLE
[useList] support toggling form's dirty state when adding/removing items from list

### ISSUE THREAD

**Issue by sherisoli** [Shopify/quilt#1346]
## Overview
Currently, the form's `dirty` state is only toggled when an item in the list is dirty.

If an item is added or removed from the list, however, `dirty` can remain false, which doesn't represent the true state of the form.

## Motivation
I think this is a common enough use case.

In my case, I'm using the `useList` hook to represent a list of variants selected in a form. The user can edit these variants to add some or remove some and I depend on the `dirty` boolean to render a contextual save bar.

**Comment by moimael** [comment]
Just a heads up that this is currently blocking a delete feature on the subscription app code red.

**Comment by moimael** [comment]
@TheMallen

**Comment by hobbydevs** [comment]
any updates on this?

**Comment by coler-j** [comment]
Probably duplicated by https://github.com/Shopify/quilt/issues/1713
