### ISSUE TITLE
Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by jared-dykstra** [Shopify/quilt#1349]
## Overview
Frequently receiving an error when navigating to the react version of an OrderDetail
```
Cannot read property 'filter' of undefined

TypeError: 
    at /Users/jared.dykstra/src/github.com/Shopify/web/node_modules/@shopify/sewing-kit-koa/dist/src/assets.js:189:32
    at Array.reduce (<anonymous>)
    at getAsyncAssetsFromManifest (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/@shopify/sewing-kit-koa/dist/src/assets.js:182:34)
    at getAssetsFromManifest (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/@shopify/sewing-kit-koa/dist/src/assets.js:162:11)
    at Assets.<anonymous> (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/@shopify/sewing-kit-koa/dist/src/assets.js:53:54)
    at step (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/tslib/tslib.js:117:57)
    at fulfilled (/Users/jared.dykstra/src/github.com/Shopify/web/node_modules/tslib/tslib.js:107:62)
```

The root cause seems to be here: 
`assetsMatchingId` is `undefined`, but `normalizedKind` is not `null`. 

Consequently, an error is thrown at the `.filter()` call.

https://github.com/Shopify/quilt/blob/df541d641794a8a885073cee15a23316a233ccc0/packages/sewing-kit-koa/src/assets.ts#L184-L208

A potential solution is to change the code on line 201 to `(assetsMatchingId || []).filter`  Although the code runs and renders without error, I don't know if this is a fix, or if this may actually just be masking a deeper problem.

## Consuming repo
`shopify/web`

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by jared-dykstra** [comment]
To get more information, I've added the log statements, added `(assetsMatchingId || []).filter` and accessed an OrderDetail page.

```js
function getAsyncAssetsFromManifest(ids, manifest, _a) {
    console.log('getAsyncAssetsFromManifest: ids=' + JSON.stringify(ids, null, 2));
    console.log('getAsyncAssetsFromManifest: manifest=' + JSON.stringify(manifest, null, 2));
    console.log('getAsyncAssetsFromManifest: _a=' + JSON.stringify(_a, null, 2));
    var kind = (_a === void 0 ? {} : _a).kind;
    return tslib_1.__spread(ids).reduce(function (all, id) {
        var assetsMatchingId = isAssetSelector(id)
            ? getAsyncAssetsById(id.id, manifest)
            : getAsyncAssetsById(id, manifest);
        var normalizedKind = kind || (isAssetSelector(id) && kindFromAssetSelector(id)) || null;
        var filteredMatchingAssets = normalizedKind == null
            ? assetsMatchingId
            : (assetsMatchingId || []).filter(function (_a) {
                var file = _a.file;
                return file.endsWith("." + normalizedKind);
            });
        return tslib_1.__spread(all, filteredMatchingAssets);
    }, [])
        .map(function (_a) {
        var publicPath = _a.publicPath;
        return ({ path: publicPath });
    });
}
```

The function is called twice.

This is a log containing all of the output.
[Log at 2020-04-02 11-08-00 AM.txt](https://github.com/Shopify/quilt/files/4421884/Log.at.2020-04-02.11-08-00.AM.txt)

**Comment by jared-dykstra** [comment]
I've repeated steps from the previous comment.  This time *without the code change* (Just the logs)  This way the stack trace is logged in context.

[Log at 2020-04-02 11-17-12 AM.txt](https://github.com/Shopify/quilt/files/4421929/Log.at.2020-04-02.11-17-12.AM.txt)

**Comment by jared-dykstra** [comment]
Slack Threads:
https://shopify.slack.com/archives/C9L3DAVM0/p1584995903416600

**Comment by jared-dykstra** [comment]
The file in question is missing from `build/client/assets.json`

**Comment by jared-dykstra** [comment]
Looking further into the generation of `assets.json`

I put console.log on line 57 - https://github.com/Shopify/sewing-kit/blob/master/packages/webpack-asset-metadata-plugin/src/manifest.ts#L57 and the file/chunk in question just isn’t in the resulting list. 

This implies that the data is missing from webpack's `compilation.chunkGroups.chunks.files`

**Comment by GoodForOneFare** [comment]
I would continue to look async modules that are being included in the wrong chunk.  Unfortunately, without the specific asset ID that's causing your problems, I can't be more specific than that.

Hacking `node_modules/@shopify/sewing-kit/dist/src/tools/webpack/dev/client.js` to contain:

```js
// Line 57
            compiler.hooks.done.tap('SewingKit.Dev.Client', (stats) => __awaiter(this, void 0, void 0, function* () {        
stats.compilation.modules
    .filter((m) => m.resource && m.resource.match(/OrderDetails/))
    .filter((m) => m.resource && !m.resource.match(/[/]translations[/]/))
    .map((m) => ({
        path: m.resource, 
        chunks: [...m._chunks].map((c) => c.id)
    }))
    .filter((m) => m.chunks.includes('Admin'))
    .map((m) => m.path)
```

I see these modules that are still in the `Admin` chunk,
```
app/sections/Orders/DraftOrders/DraftOrderDetails/components/DraftOrderDetailsQuery/DraftOrderDetailsQuery.tsx
app/sections/Orders/DraftOrders/DraftOrderDetails/components/DraftOrderDetailsQuery/index.ts
app/sections/Orders/DraftOrders/DraftOrderDetails/components/index.ts
app/sections/Orders/DraftOrders/DraftOrderDetails/index.tsx
app/sections/Orders/OrderDetails/index.tsx
app/sections/PurchaseOrders/PurchaseOrderDetails/graphql/PurchaseOrderDetailsQuery.tsx
app/sections/PurchaseOrders/PurchaseOrderDetails/index.tsx
app/sections/PurchaseOrders/PurchaseOrderDetails/types.ts"
```

Not 100% are misplaced, I'm guessing at least `DraftOrderDetailsQuery` should be isolated in an async chunk somewhere.

**Comment by GoodForOneFare** [comment]
cc @Shopify/web-foundation - the above snippet is maybe a start at a webpack plugin for "your async modules are in the wrong place".  Failing fast would be nice.

Alternatively, it's maybe just a sign that GraphQL types are leaking out of their components 🤷‍♂

**Comment by GoodForOneFare** [comment]
This was definitely caused by child components reaching into parents and siblings.  I managed to turn the above checks into a plugin, but I'm not sure it's worth it given how rarely this crops up.

Pretty sure this goes away when we embrace type import/exports.  @Shopify/web-foundation likely have a support roadmap and recommendations for this underway.

**Comment by jared-dykstra** [comment]
@GoodForOneFare - I'm totally OK with closing this issue.

Perhaps consider adding an explicit error, something like:
```ts
if (!assetsMatchingId) {
  throw new Err('An Async bundle is missing, likely caused by child components reaching into parents and siblings');
}
```
