### ISSUE TITLE
invalid cert on staging

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1355]
Our cert seems to be invalid on staging.

![image](https://user-images.githubusercontent.com/4889856/78590937-a6b65b00-7810-11ea-8803-af98393b1e55.png)

![image](https://user-images.githubusercontent.com/4889856/78590901-956d4e80-7810-11ea-9762-37a398fe14c0.png)

**Comment by ismail-syed** [comment]
Fixed by https://github.com/Shopify/shrink-ray/pull/1169
