### ISSUE TITLE
Move @shopify/javascript-utilities to quilt

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#136]
See https://github.com/Shopify/javascript-utilities/issues/33.

Currently, `javascript-utilities` is set up as a large package with multiple exports. This pattern doesn't work well with our monorepo approach, and doesn't really feel like a proper package boundary.

1. Packages need to be created for each of the javascript-utilities functions:
  - decorators can be moved into @shopify/javascript-decorators
  - files like feature-detect can be moved into their own packages (ex. @shopify/feature-detection)

2. Create an issue in the `javascript-utilites` repo for deprecating the library, add an upgrade path document for where to find the new utilities, and ensure that no key libraries (ex. `polaris`) are depending on the old packages.

**Comment by michelleyschen** [comment]
Propose packages to be created from `javascript-utilities`

- [ ] [decorators](https://github.com/Shopify/javascript-utilities/tree/master/src/decorators) => create `@shopify/javascript-decorators` 
- [ ] [dates](https://github.com/Shopify/javascript-utilities/blob/master/src/dates.ts) => merge into [quilt/dates](https://github.com/Shopify/quilt/tree/master/packages/dates)
- [ ] [doms](https://github.com/Shopify/javascript-utilities/blob/master/src/doms.ts)  +  [fastdom](https://github.com/Shopify/javascript-utilities/blob/master/src/fastdom.ts) + [focus](https://github.com/Shopify/javascript-utilities/blob/master/src/focus.ts) => create `@shopify/dom`
- [ ] [events](https://github.com/Shopify/javascript-utilities/blob/master/src/events.ts) => create `@shopify/events`
- [ ] [feature-detect](https://github.com/Shopify/javascript-utilities/blob/master/src/feature-detect.ts) => create `@shopify/feature-detect`
- [ ] [math](https://github.com/Shopify/javascript-utilities/blob/master/src/math.ts) + [geometry](https://github.com/Shopify/javascript-utilities/blob/master/src/geometry.ts) => create `@shopify/math`
- [ ] [url](https://github.com/Shopify/javascript-utilities/blob/master/src/url.ts) => create `@shopify/url`
- [ ] [others/noop](https://github.com/Shopify/javascript-utilities/blob/master/src/other.ts#L1-L2) => ???
- [ ] [others/createUniqueIDFactory](https://github.com/Shopify/javascript-utilities/blob/master/src/other.ts#L4-L7) => ???

**Comment by michelleyschen** [comment]
cc @tzvipm @lemonmade @ismail-syed @nimzco @rexmac 

I am not super familiar with everything in `javascript-utilities`
if I can get people's thoughts on how we should split it up in quilt please 🙏

**Comment by lemonmade** [comment]
I would just ditch `dom` + `fastdom` for now; the first is better done via polyfills, the second is kind of not a good idea in general for React. I like the idea of still having focus + anything that we can't polyfill in `/dom` library.

I would probably put `events` in there too, since it's all DOM-related. Since the feature detection is only for event stuff, I'd put that wherever event lives.

The geometry stuff seems too trivial to be in a package at all to me (if anything, it might want to go in DOM, since it is only really used for that).

`url` can also go, it is better solved by other patterns (I don't even know where we use it tbh).

The others stuff is weird, I might make a simple package that just exports the noop, and maybe the other one can just be collapsed into Polaris, which I think is the only user of it?

**Comment by michelleyschen** [comment]
also should `@shopify/react-utilities/target.ts` goes into `@shopify/dom` as well ?

**Comment by michelleyschen** [comment]
I actually found quite a lot of usage for `createUniqueIDFactory` https://github.com/search?q=org%3AShopify+createUniqueIDFactory&type=Code, maybe part of `dom` as well. You don't need id if there is no dom element.

**Comment by lemonmade** [comment]
I wish we never had the unique ID factory, it is not a good idea for SSR. Oh well. If people really need it I think a dedicated package (`@shopify/id`?) makes sense since you can conceivably use IDs for lots of different things

**Comment by BPScott** [comment]
I'd be very tempted to kill `noop` too. I know it's used EVERYWHERE but having to import something instead of doing `const noop = () => {}` doesn't feel like it adds much value.
