### ISSUE TITLE
[react-form] Removing fields from useList doesn't trigger dirty state

### ISSUE THREAD

**Issue by moimael** [Shopify/quilt#1361]
## Overview

I'm trying to implement a delete feature on a form that make use of `useList`.

I update the initial value of the list, my UI is correctly updated (the fields are removed from the UI), but the form doesn't detect that the list has changed and doesn't go in a dirty state.

It works fine when updating the values of those fields, it's only when deleting that it becomes an issue.

```
policies: useList({
  list: sellingPlanPolicyList,
})
```

```
{policies.map((policy, index) => (<My fields>))}
```

**Comment by moimael** [comment]
Duplicate of #1346

**Comment by michenly** [comment]
Close because of duplication.
