### ISSUE TITLE
Move @shopify/react-utilities to quilt

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#137]
Unfortunately, as the old repo is private, only Shopify employees will be able to access the old repo. This issue is an attempt to bring those utilities into quilt, making them more readily available to the community at large, and better integrating them with the rest of our utility packages.

See https://github.com/Shopify/react-utilities/issues/24#issuecomment-391702866

**Comment by michenly** [comment]
This is done in https://github.com/Shopify/react-utilities/issues/24
