### ISSUE TITLE
Safari 13.1 now blocks all third-party cookies by default

### ISSUE THREAD

**Issue by arenatheme** [Shopify/quilt#1387]
https://community.shopify.com/c/Shopify-APIs-SDKs/Safari-13-1-and-embedded-apps/td-p/688416

**Comment by pratiknikam** [comment]
I think everyone is facing this issue now. I didn't hear any solution from Shopify team yet :( 

In my case Safari 13.1 is causing cookie redirect loop.

**Comment by trytada** [comment]
This would be important to prioritize quickly. Solution is discussed here https://medium.com/@sleyhane/shopify-embedded-apps-and-safari-81903dec20f7, it's currently making users that use Safari unable to use most apps using this auth module. If someone has an idea how to apply that fix to the module, that'd be amazing.

**Comment by trytada** [comment]
We're also seeing Cookie Redirect Loop on Safari 13.1

**Comment by pratiknikam** [comment]
@lemonmade would love to hear from you on this one.

**Comment by lemonmade** [comment]
@pratiknikam and others, sorry for the delay. We have a couple folks working on getting this resolved, and we'll be able to provide guidance very soon. Keep an eye on this issue or the [community post](https://community.shopify.com/c/Shopify-APIs-SDKs/Safari-13-1-and-embedded-apps/td-p/688416/page/2).

**Comment by trytada** [comment]
@lemonmade , this is great to hear this is getting worked on. I believe there should also be some different handling of cookies based on the user agent, as discussed here: https://www.chromium.org/updates/same-site/incompatible-clients

We're excited to see support for this!

**Comment by Milbergs** [comment]
@lemonmade - looking forward to the fix, we are currently submitting our app for the review and we need to fix this ASAP

**Comment by ReinisL** [comment]
I don't know if it's related to this issue, but what was causing the redirect loop for me was that I was missing these options in the afterAuth method. 

```
ctx.cookies.set("shopOrigin", shop, {
  httpOnly: false,
  secure: true, <----
  sameSite: "none", <----
});
```

**Comment by pratiknikam** [comment]
@ReinisL no this one is different I believe. Can you test app with above code in Safari 13.1?

**Comment by ReinisL** [comment]
@pratiknikam yes. I don't have redirect issue anymore. Tested on multiple Safari 13.1 browsers

**Comment by pratiknikam** [comment]
That's super weird. Are you doing anything special with the way you handled cookies?

Me along with others have above code from months but never had issue until Safari 13.1 release which blocks third party cookies by default. Mind sending me your app link? Would love to try it out.

**Comment by ayronshopify** [comment]
This should now be resolved by bumping your `koa-shopify-auth` package to `3.1.61`

**Comment by pratiknikam** [comment]
Thanks a ton for releasing patch quickly.
