### ISSUE TITLE
@shopify/dates formatDate is broken for serverside rendering

### ISSUE THREAD

**Issue by meunierd** [Shopify/quilt#1390]
## Overview
I found a weird issue with @shopify/dates
Node only supports the en locale so if you use formatDate with serverside rendering it always gives you the en date. If you nav to the same component from elsewhere, the client-side rendering will localize it properly.

Jason Godson:
> I think we may need to make sure we build node with --with-intl=full-icu It seems to be the default now in 13, but 10.x is small-icu

## Consuming repo

Shopify/web

**Comment by michenly** [comment]
From the library perspective this is the way it is suppose to work.

In order to get the functionality you are looking for with node, included https://www.npmjs.com/package/full-icu for node version < 13. This is included for node version >=13.
