### ISSUE TITLE
quilt_rails docs: Required steps not documented

### ISSUE THREAD

**Issue by martenbjork** [Shopify/quilt#1402]
## quilt_rails docs: Project won't run without adding tsconfig.json

I'm following the "manual" steps in this Readme:

https://github.com/Shopify/quilt/blob/master/gems/quilt_rails/README.md

There are two undocumented steps that are required to make it work:

1. `yarn add typescript`
2. Add a `tsconfig.json` with at least an empty object. Without it you get this error in the browser `Waiting for React server to boot up`. In the terminal logs you'll find `[error] sewing-kit cannot build a typescript project without tsconfig.json` but it's hidden among huge amounts of log statements.

**Comment by michenly** [comment]
Close in favor of https://github.com/Shopify/quilt/issues/1024
