### ISSUE TITLE
How the react-form-state and react-form for radio button list?

### ISSUE THREAD

**Issue by TommyLee0088** [Shopify/quilt#1406]
How the react-form-state and react-form for radio button list?

I try to use them, the button list have same name 
e.g <RadioButton name ="good" value="stack">
<RadioButton name ="good" value="grid">
<RadioButton name ="good" value="slide">

I don't know how to use the  react-form-state  to set the default value and validators , they default select stack, and one of them should be selected.

I don't find any help for these.
Could someone have some example or helps.
Many thanks,
Tommy

**Comment by michenly** [comment]
Hi Tommy,
can you provided more details of your problem. An example with what you expected to happen would be very helpful.

**Comment by TommyLee0088** [comment]
Hi @michenly ,
Thank you fo your response, I want to use the radio group, e.g  radio button: Stack, Grid, Slide, there are the same  name="myStyle", how could I use the react-form or react-form-state to control them and validate? 

Could you give me some example? I use the shopify polairs, too.

Many thanks,
Tommy
