### ISSUE TITLE
Use a <div> for serializations instead of a <script>

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#1409]
After talking it through with @Becojo, we (checkout) opted to use a `div` to store serialized values, using `data-serialized-id` as the attribute for the serialization's ID, and `data-serialized-value` for the JSON-encoded serialized value. We opted for this because it just feels safer to avoid a `script` tag here, even if we provide a non-JavaScript type. Core also has some validations that complain about the markup we use in `react-html` for these serializations.

I made this change to our own version of `react-html`: https://github.com/lemonmade/quilt/commit/199f77739b7c20762a2d562cde2885e1522ab850#diff-fa2b0a55752ecf9bd270b9c4167b97f8, and it's probably a good idea to pull it into mainline too. I don't think anyone should be depending on the exact structure of these serializations, but that would be a note to call out in the changelog.

cc/ @TheMallen

**Comment by TheMallen** [comment]
This seems simple enough, but I'm not sure how impactful it is as a change. If I understand the concern here is just that it could potentially be flagged by linters / browser security in the future? Or just that it's possibly slightly more secure to use `div` than `script type="text"`?

**Comment by lemonmade** [comment]
The value is both that it’s safer and that it didn’t complain about the markup when we added an implementation of serialization to core. That second part doesn’t matter if it’s a bogus rule in core, but I think core is right that we should just prefer the safer markup here. I think it may also mean the dependency on serialization-JavaScript could go away, since HTML attributes have special escaping rules, but not 100% sure on that bit
