### ISSUE TITLE
Add a list formatter to react-i18n

### ISSUE THREAD

**Issue by Flufd** [Shopify/quilt#1416]
## Overview

Add a utility for formatting a list of items in a locale aware way. Something like this..

`i18n.formatList(["a", "b", "c"])`
=> "a, b, and c"

`i18n.formatList(["a", "b", "c"], ListFormat.Or)`
=> "a, b, or c"

In Spanish
`i18n.formatList(["a", "b", "c"], ListFormat.Or)`
=> "a, b o c"

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

This feature is required to join dynamic lists of items with the "and" at the end, ins the correct language, as well as using the correct separating string (not always a comma)

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Looks like this is supported by [the INTL object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat), if you would like to PR it onto the `i18n` instance that would be appreciated :)

**Comment by plentz** [comment]
Duplicates https://github.com/Shopify/quilt/issues/807
