### ISSUE TITLE
quilt_rails - accept JSON metrics in text/plain format

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#1431]
## Overview
When sending metrics using `navigator.sendBeacon(url, JSON.stringify(myStats))`, Firefox uses Content-Type `text/plain`:

<img width="942" alt="Firefox network dev tools view of a metrics request that appears to be sent as JSON content.  However, the request header view shows text/plain content-type." src="https://user-images.githubusercontent.com/673655/81704399-bc382980-943b-11ea-8f99-1ab506daa33b.png">

I would like to discuss if it makes sense to have quilt_rails parse plain as JSON content.

## Motivation

I'm trying to avoid working around this problem on the client side because:
* Workarounds typically involve [using a `Blob`](https://stackoverflow.com/a/47122503) to set the content type, but this [is flagged by Chrome's CORS checks](https://stackoverflow.com/a/52054424)
* [Sending as `FormData`](https://stackoverflow.com/a/59878273) works for the browser, but trips Rails' CORS checks
  * [A suggested workaround is disabling forgery protection](https://github.com/rails/rails/issues/22965#issuecomment-172983268), but I'd prefer not to leave all endpoints unprotected just to get metrics
* More selfishly, any client-side workaround is extra bytes, and I'm trying to keep the overhead of performance metrics low 😅 

## Workaround
For now, I'm patching quilt_rails like this:

```rb
require 'quilt_rails'

module Quilt
  module Performance
    module Reportable
      def process_report(&block)
        # Munge plain content into JSON because:
        # - Firefox's `sendBeacon` always uses Content-Type=text/plain
        # - Chrome throws security errors if explicit content type headers are applied (https://stackoverflow.com/a/45622855)
        # - Sending as form-data trips Rails' HTTP Origin header checks ("didn't match request.base_url")

        report_params = if request.content_type == 'text/plain'
          ActionController::Parameters.new(JSON.parse(request.body.read))
        else
          params.transform_keys! { |key| key.underscore.to_sym }
          report_params = params
        end

        Client.send!(Report.from_params(report_params), &block)
      end
    end
  end
end
```

**Comment by TheMallen** [comment]
This makes a lot of sense.
