### ISSUE TITLE
Apollo Smart Cache

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#144]
Right now we do a lot of manual cache fiddling in our apollo projects, and it's a big potential source of errors, as well as generally quite WET.

We should create a custom Apollo Cacheing layer that has the following properties:
 - conventions around mutation naming to automatically resolve cache updates
 - ability to provide a custom discriminator for custom operation types
 - find and update caches across queries with different variables

**Comment by michenly** [comment]
Tired and failed.
