### ISSUE TITLE
/auth/enable_cookies XSS attack?

### ISSUE THREAD

**Issue by seamusabshere** [Shopify/quilt#1453]
## Overview

/auth/enable_cookies appears to render arbitrary javascript - XSS

## Consuming repo

We have the shopify koa app mounted at: (real URL available in private email to seamus@abshere.net)

https://example.com/shopify

If you click this, you will get a "hello world" prompt.

https://example.com/shopify/auth/enable_cookies?shop=%27%22%3C/title%3E%3C/style%3E%3C/textarea%3E%3C/noscript%3E%3C/script%3E--%3E%3Cdtfy%3E%3Cscript%3Ealert(%27hello%20world%27)%3C/script%3E

## Labels

- [ ] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by jonpulsifer** [comment]
FYI @seamusabshere we have a bug bounty program over at https://hackerone.com/shopify and there are rules for participation!

I am thinking of two rules in particular:

- Rules for reporting must be followed.
- Do not disclose any issues publicly before they have been resolved.
