### ISSUE TITLE
react-i18n doesn't refresh when used below usePerformanceMark

### ISSUE THREAD

**Issue by kvendrik** [Shopify/quilt#1465]
## Overview
react-i18n doesn't refresh when used below `usePerformanceMark`. [Demo](https://drive.google.com/file/d/1kXTZ1mXMy33Su15UuHg8GF8rKKAf_5Cj/view?usp=sharing)

## Consuming repo

> What repo were you working in when this issue occurred?

Signage - https://github.com/Shopify/signage/compare/master...feature/use-perf-i18n-bug

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by michenly** [comment]
I scaffold out a minimal app with one page that has en or fr translations, set the locale="fr"  in `App.tsx`  and was able to load the page with french translation with or without performance mark.

sewing-kit version @ 0.120.0 & 0.129.0
@shopify/react-i18n version @ 3.0.2
@shopify/react-i18n-universal-provider version @1.0.55
