### ISSUE TITLE
Add an `addEventListener` mock to `jest-dom-mocks`

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#150]
We should expose a handy way of mocking out the document level `addEventListener` and `removeEventListener`, as well as add this to our between test checks for having restored them.

**Comment by lemonmade** [comment]
I think generally speaking, there are a whole bunch of document mocks that we could use (`createElement`, spy on particular methods of DOM nodes for testing refs, etc)

**Comment by donnielrt** [comment]
+1 :) would especially love a mock for `scrollWidth`, `offsetWidth`, etc.
