### ISSUE TITLE
Proposal for porting @shopify/koa-shopify-auth to express

### ISSUE THREAD

**Issue by hgezim** [Shopify/quilt#1502]
## Overview

I'm creating a port of @shopify/koa-shopify-auth for express.

Would you folks be interested in maintaining it?

**Comment by hgezim** [comment]
Here's my repo: https://github.com/hgezim/express-shopify-auth

**Comment by tbeseda** [comment]
@hgezim Do you happen to know if this Koa middleware can be directly adapted to Express without modification to the package? Seems like it should be possible given how Koa and Express middleware share a lot of the same DNA.

**Comment by hgezim** [comment]
@tbeseda 99% sure it can't be done without modifications. Koa uses [context](https://koajs.com/#context) which has shorthands for request and response objects. The cookie library used by koa is different and has a different API. Koa and Express handle `next()` calls differently.

Did you try my package (https://github.com/hgezim/express-shopify-auth)?

**Comment by ismail-syed** [comment]
Hey, thanks for the issue. We don't support express. Feel free to fork and create your own package that supports express.

**Comment by hgezim** [comment]
@ismail-syed Feel free to read my messages. Already created my own package:

https://github.com/hgezim/express-shopify-auth
