### ISSUE TITLE
[react-network] Empty cookies are still being set

### ISSUE THREAD

**Issue by kvendrik** [Shopify/quilt#1516]
Some cookies still get passed through

```
curl -IXGET "https://signage.myshopify.io/tools/signage-maker" --cookie "_cookieA=this%2Bhas%2Ba%2Bplus; _cookieB=" --silent | grep "_cookieA\|_cookieB" 

set-cookie: _cookieB=; path=/; expires=Thu, 01 Jan 1970 00:00:00 GMT; HttpOnly; secure
```

[This](https://github.com/Shopify/quilt/blob/30a0dabc9ba416ba41cc690fa761e5fa7af14b58/packages/react-network/src/server.ts#L31-L34) needs to be changed to `typeof rawCookieValue  !== 'undefined' && ...` because currently it skips the equals check if the cookie is empty.

**Comment by TheMallen** [comment]
fixed by #1517
