### ISSUE TITLE
Explore `@sewing-kit` for quilt's builds

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1522]
## Overview
We should rebuild quilt's build setup from the ground up to using the `@sewing-kit/*` ecosystem of packages (referred to in general as sewing-kit-next) being championed and prototyped by @lemonmade

## Motivation
There are a few reasons to do this:
- Organizationally, we want to be able to recommend a build-tool for other npm package publishing repos at Shopify (especially multi-package repos) and sewing-kit `0.x` doesn't handle this usecase well (if at all)
- @lemonmade  has been working on this stuff in relative isolation for a while and we need some on-ramps to be able to gain understanding before we can even begin to help
- Quilt itself has a poor build situation. We can't build assets other than ts in this repo and we only build legacy commonjs files. Sewing-kit-next can help us on both counts. **We should see immediate impact in the form of greater tree-shakeability, and thus reduced bundle sizes for our consumers**

**Comment by TheMallen** [comment]
## Resources
The hardest part of this is that, since the tool is currently a one-man show under active development, there is little documentation and relatively few examples to look at. We will be able to help make up this gap, once we have worked with and on it a bit more,  but for now it will mostly be a "read the code and figure it out" situation unfortunately. 

### Repos to look at

Luckily, @lemonmade  has made extensive use dogfooding the sewing-kit-next in many of the packages that are being used in some more experimental projects. This means there are some repos with similar structures to quilt (in one case an actual fork / re-imagining) that we can learn from.

-the [sewing-kit-next monorepo]( https://github.com/lemonmade/sewing-kit), useful to see the source but also as an example of a setup since it currently builds itself
- the [alternate quilt monorepo](https://github.com/lemonmade/quilt), useful as a starting point to see some of the existing packages already converted and how a shared plugin might work for us
- the [https://github.com/lemonmade/remote-ui](remote-ui) repo, just another example really

**Comment by ismail-syed** [comment]
I've tagged this issue with the Explore label and renamed to highlight this work as our exploration. I've open'd https://github.com/Shopify/quilt/issues/1592 and added it to our board to cut an official release in our build phase.
