### ISSUE TITLE
Modularize for react-testing for different React flavours

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#1526]
## Overview
We should make `@shopify/react-testing` work for multiple React flavours rather than maintain separate libraries for them.

## Motivation

Currently we have two different testing libraries for `preact` and `react`, and no similar library for React-Native that doesn't depend on the DOM. Rather than continuing to maintain them separately, it is preferable that we consolidate them into one library (or at least the shared parts into a shared core library they both depend on).

## Implementation
In his [forked / alternate quilt repo](https://github.com/lemonmade/quilt/blob/main/packages/react-testing/src/implementations/shared/react.ts) @lemonmade  already built an implementation of this.

This implementation looks pretty good to me, though unfortunately it has no tests and the current setup depends on using `@sewing-kit/*` for building the package. As such, if we were to use it as is we would need to solve #1522  first. Regardless, it is a good starting point and should not be too difficult to adapt over and make sure our e2e test suite still passes.

**Comment by lemonmade** [comment]
> Unfortunately has no tests

:shame:

**Comment by gvarandas** [comment]
Sorry to resurrect this issue but our team on POS RN is facing similar issues with `@shopify/react-testing` in an RN environment and one of my exploratory tasks is to determine what's the best course of action to solve them.

As of right now, we have a [custom jest reporter](https://github.com/Shopify/pos-next-react-native/blob/master/tests/reporter/filteredLogReporter.js) that filters most of the warnings that get outputted as the renderer doesn't recognize the elements that were outputted and we were looking into deprecating it and moving to a solution that doesn't rely on a DOM-based rendered while still remaining in the Shopify-best-practices boundaries.

All that being said, is this still being considered in the library roadmap? How can we contribute, if possible, to make this happen and unblock this to not only our team but for all present and future ones?
