### ISSUE TITLE
@shopify/jest-dom-mocks is broken on latest Jest

### ISSUE THREAD

**Issue by amrocha** [Shopify/quilt#155]
On version 22, Jest updated their JSDom version from `9.x` to `11.x`. This included several breaking changes, and among them is the ability to make direct edits to the `window.location` object (https://github.com/jsdom/jsdom/commit/58a7028d0d5b6aacc5b435daee9fd8f9eacbb14c).

`@shopify/jest-dom-mocks` relies on the `window.location` object being editable  in order to work, so it stopped working.

The following issues might be helpful in determining a good possible solution:
 - https://github.com/facebook/jest/issues/5124
 - https://github.com/facebook/jest/issues/890

**Comment by amrocha** [comment]
I don't mind working on a solution for this if we agree on how we want to handle it

**Comment by TheMallen** [comment]
:/ looks like we need to do some junk with `reconfigure`

**Comment by tzvipm** [comment]
We are currently using jest `23.x` in quilt, and all of our tests are passing. This must mean either things were fixed in jest `23`, or else our testing suite is insufficient.

**Comment by amrocha** [comment]
This is not fixed in jest 23, I found out about this by trying to upgrade web to jest t23

**Comment by alexandcote** [comment]
You can do something like : 
```
history.replaceState({}, 'YourPath', `/yourPath?key=value`);
```

Instead of changing directly window.location.

**Comment by tmlayton** [comment]
Still WIP, but this is how we are sorting it in https://github.com/Shopify/polaris-react/pull/2208

**Comment by alexandcote** [comment]
@Shopify/web-foundations is it still an issue?
