### ISSUE TITLE
Custom tags for navigation events

### ISSUE THREAD

**Issue by lazarmarkov** [Shopify/quilt#1553]
## Overview
Currently, it's not possible to add a group ID (or tags) to [navigations](https://github.com/Shopify/quilt/tree/master/packages/performance#navigation). I think navigations should be taggable since they're used as aggregations downstream in DataDog.

A common pattern is to group events based on action/route/status etc. With navigations that's not possible in a consistent manner.

Navigations do have a `target` field which defaults to the relative path for where the navigation is taking the user: e.g. `/admin`, `/thank-you`. This could and is used as group ID, but the problem is that some routes are dynamic, e.g. `/order/123`; or have long subroutes: `/admin/settings/checkout/edit` which requires route knowledge and can be error prone.

Not having a stable grouping ID has been a problem in the past and the approach was to parse `target` (a relative path), server-side:
  - https://github.com/Shopify/web/blob/master/server/middleware/utilities/stats.ts
  - https://github.com/Shopify/partners/pull/25877
  - https://github.com/Shopify/partners/pull/26094

It seems that the complexity ☝️ can be dropped if the client can add grouping IDs (tags) to navigations.

### How to do that?

Here are two possible approaches:

#### Add tags when navigations are created
One way would be to add tags when a navigation is created. That seems to happen here: https://github.com/Shopify/quilt/blob/master/packages/performance/src/performance.ts#L59. I'm not sure if this makes sense though, since navigations are created as callbacks to history API events (push,pop,replace). And thus the programmer doesn't know _where_ the user is taken.

#### Add tags when navigations complete
One way would be allow passing in tags to [usePerformanceMark()](https://github.com/Shopify/quilt/blob/master/packages/react-performance/src/performance-mark.ts#L4) which in turn calls [Performance.finish()](https://github.com/Shopify/quilt/blob/master/packages/performance/src/performance.ts#L264).

My suggestion is to add the tags when the navigation completes, because this is triggered from the codebase as via `usePerformanceMark()` and thus the programmer knows which React page is being rendered.

### Automatically apply tags to StatsD metrics

By default, [koa-performance](https://github.com/Shopify/quilt/tree/master/packages/koa-performance) and [quilt_rails](https://github.com/Shopify/quilt/tree/master/gems/quilt_rails) (which process the browser performance reports) won't apply tags on the navigation distributions, this can also be automated as part of this feature extension. This way users don't have to apply logic like: https://github.com/Shopify/quilt/blob/master/gems/quilt_rails/test/quilt_rails/performance_reportable_test.rb#L170-L208. 

## Type

- [x] Changes to existing features

## Motivation

I'm trying to add browser perf. metrics to shop.app but some of the routes are dynamic and therefore they won't aggregate properly in DataDog. My options are to do what other teams have done previously - post-process the routes server-side or allow tagging navigations on the client.

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by lazarmarkov** [comment]
cc @lemonmade.

**Comment by lemonmade** [comment]
Can you explain why server-side tagging is not appropriate for your use case? I think this is certainly the correct case for the admin, where we already have other stats the server generates that we want to tag with normalized route, and because we generally prefer no code on the client when we can find a way around it.

**Comment by lazarmarkov** [comment]
Sure. My point is that from what I can tell, most of the complexity introduced in the referenced PRs above can be removed if the performance API allows adding tags to a navigation metrics. The server will no longer have to know about routing on the client nor to parse the path. 

> other stats the server generates that we want to tag with

That's still valid and it won't change.

> we generally prefer no code on the client when we can find a way around it

What is the rationale for that? The client is the one that knows **which** page is being rendered and can easily provide that context as data.

**Comment by lemonmade** [comment]
We generally prefer the server because there is no performance overhead with handling it on the server. For something that only benefits us, not merchants, it's nice not to put that in their JavaScript bundles.

> That can still be done server-side, I don't think this change affects that.

The point is that, for web, as well as any other service that records backend metrics it wants to associate with a route (I imagine many would, since we generally record the backend response time), putting this logic on the client requires it being duplicated. In the case of a Ruby app, the logic needs to be duplicated in two different languages.

If this is absolutely critical to you, it can certainly be added. You’d probably need to teach [`usePerformanceReport`](https://github.com/Shopify/quilt/blob/master/packages/react-performance/src/performance-report.ts#L12-L18) how to generate tags for a navigation, run that [when sending navigations to the metric server](https://github.com/Shopify/quilt/blob/master/packages/react-performance/src/performance-report.ts#L43-L46), and then teach the Koa + Rails integrations to include those tags alongside the autogenerated ones. Since the web foundation recommendation would be to keep this logic on the server, I don't think it will ever be prioritized by that team, but they are generally very kind in offering time on PR reviews.

**Comment by lazarmarkov** [comment]
Hmm, I think we might be talking about different things, perhaps my point is not concrete. Here's a gist of what I expect the changes to look like:

```js
render () {
  id = 'order/123'
  tags = {'action': 'order#view')
  usePerformanceMark(Stage.Complete, id, tags);
  return <> ... <>
}
```

`tags` is then added to the navigation object [here](https://github.com/Shopify/quilt/blob/master/packages/performance/src/performance.ts#L271), like so:
```js
finish(timeStamp = now(), tags = []) {
  ...
  this.inflightNavigation.finish(timeStamp, tags);
```

Also, I won't need to  modify `usePerformanceReport` as the tags will be serialized to JSON as part of the Navigation object. The report is then send.

-----

> The point is that, for web, as well as any other service that records backend metrics it wants to associate with a route (I imagine many would, since we generally record the backend response time), putting this logic on the client requires it being duplicated. In the case of a Ruby app, the logic needs to be duplicated in two different languages.

I wouldn't say we're duplicating the path parsing logic on the client, but rather removing the requirement for the backend to parse the path for the sake of adding more context to the navigation metric ("which page is this navigation event for?") . This way we're removing a use-case for the path-parsing logic.

The reason I want to fix this is to reduce complexity across different repositories. The alternative for me is to do in arrive-website, what shopify/web and shopify/partners have done. But I think the approach taken there was for a lack of time and/or context on how @shopify/performance lib works. I'm no expert either, that's why I'm reaching out for feedback, but my opinion is that the suggested approach is easier to maintain.

**Comment by lemonmade** [comment]
Where you're suggesting putting it is not in line with how the package is structured. Navigations are standalone objects that are built up, in part, by the results of calling `usePerformanceMark`. Navigations, alongside other events that do not directly correlate to a navigation (TTFB, first input delay, etc), are then emitted to listeners, and that's where things like the reporter can kick in and send to a metrics server. Putting tags on `usePerformanceMark` means that the tags are not then applied to other constructs, like events. It's also not clear what the behaviour should be if `usePerformanceMark` changes the tags during the navigation, which makes me feel like it is not the correct place for that logic to live.

I am also still confused why a project would not want to tag other, entirely backend-focused metrics, like response time, with the normalized path. If a project does that, it needs this mapping on the server, so it may as well only be on the server. I get that this is not required, but having response timing metrics without a path seems unhelpful.

My previous suggestion on where this can lives stands, if you really want to avoid having to make a change in a server-only repo for this. This is probably going to be an increasingly uncommon use case, as the web foundation team has done a lot of work on `quilt_rails` that allows a single application to house the client and server, but if it's valuable for your case and you have the time, you should go for it.

**Comment by lazarmarkov** [comment]
> Putting tags on usePerformanceMark means that the tags are not then applied to other constructs, like events. 

Yeah that's a good point. I guess `usePerformanceMark` is not the correct place to put it. The problem is that since events/navigations are browser event based, it's not possible to bind them to a certain path of the codebase (e.g. React page). Instead we'd have to backfill any additional data by determining which page is an event/navigation related to. And that bring us back to square one which is parsing the path. 

Thanks for the comments, Chris!

**Comment by lemonmade** [comment]
I think I mentioned it above, but if this is an important feature to you, you can definitely implement it, and I am sure that the web foundation team will happily review. There is a place where I think the logic you are talking about makes sense (in `usePerformanceReport`); I don't think it will ever be a priority for the web foundation team, but we hope that features that are priorities for individual projects/ subsets of projects can be added by developers on that team.

Up to you how to proceed, just don't want to make this sound like a very final, "we will never add this feature" kind of discussion :)
