### ISSUE TITLE
[Address] Query getCountries for signupOnly countries

### ISSUE THREAD

**Issue by JenGreatrix** [Shopify/quilt#1556]
## Overview

Is it possible to extend `@shopify/address` -> `getCountries()` to allow querying for signupOnly countries?

The country-db service has the capability to [query for countries that are approved for signup](https://github.com/Shopify/country-service/blob/master/app/graphql/country_service_schema.graphql#L99) using the `signupOnly` boolean. Currently the `@shopify/address` package does not have the capability to query `getCountries` with the `signupOnly` option.

## Type

- [x] Changes to existing features

## Motivation

The account setup portion of signup (aka 10-field) has moved into Web and uses the shared `AddressForm` component. This component queries the `@shopify/address` package to pull the list of countries to display. For sign up, there is a specific list of countries that should display. Right now we get a full list of countries (from `getCountries`) then filter them based on a hard coded list of the accepted countries for sign up. This is not so great, as the accepted countries can change over time and we have to manually make the change.  

I would love to be able to replace our hard codes list and pull the signup countries from country-db via the address package. 

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
Hey, not sure when the team will be able to take a look at adding support for this but we're open to PRs. Thanks!

**Comment by JenGreatrix** [comment]
👍  stay tuned, will send a PR your way

**Comment by JenGreatrix** [comment]
Closing this out, going to handle this elsewhere
