### ISSUE TITLE
[react-router] SSR Router has incorrect pathname

### ISSUE THREAD

**Issue by jamesism** [Shopify/quilt#1569]
## Overview

When helping a teammate on his quilt_rails/react-server set up, we encountered some odd behaviour with routing. We noticed that all server-side requests were falling through to 404, and then mismatch during hydration would warn in console and client side would render the correct page. 

The `Router` component is rendered and the whole `URL` object passed in with `location` prop.

We noticed a potential fix in version `0.0.30` published yesterday which detects the URL object and resolves to `location.href`. Though after updating to this version the issue persisted. In some quick testing it appears that this causes `StaticRouter` to think the pathname is the fully qualified url (`location.href`), which meant none of the routes were matching and it was falling through to the 404.

I think a fix for this could be as simple as changing the `locationString` dereferencing line to use `location.pathname` rather than `location.href`. If you don't see any issue with this let me know and I can put up a PR.

cc @cptjackson 

## Consuming repo
[clickstream-clustering](https://github.com/Shopify/clickstream-clustering)

**Comment by michenly** [comment]
This had been fixed with v0.0.31
https://github.com/Shopify/quilt/blob/master/packages/react-router/CHANGELOG.md#changed
