### ISSUE TITLE
Uncaught TypeError: event.getModifierState is not a function comes when using Chrome autofill

### ISSUE THREAD

**Issue by bhavathi** [Shopify/quilt#1606]
## Overview

Uncaught TypeError: event.getModifierState is not a function

When using native autofill feature in Chrome, keydown event is raised but event object is missing getModifierState function and causes this error.

## Consuming repo

https://github.com/Shopify/quilt  -  @shopify/react-shortcuts
https://github.com/Shopify/quilt/tree/master/packages/react-shortcuts

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by bhavathi** [comment]
I raised a pull request for the same #1578. Please review

**Comment by sanjanadesai27** [comment]
Review is not feasible without a reproduction script or a project that shows this bug occuring. Please provide a gist or example (on [codesandbox](https://codesandbox.io/)) if possible.

**Comment by bhavathi** [comment]
@sanjanadesai27 I have created a codesandbox to reproduce the issue. Please check at https://codesandbox.io/s/compassionate-kare-7i1dv

when tried to fill the input by using autofill, we get below error.
TypeError
event.getModifierState is not a function

**Comment by gmcgibbon** [comment]
https://github.com/Shopify/quilt/blob/a8773ddc6c31bb90c55338967e0feee805eb8134/packages/react-shortcuts/src/ShortcutManager/ShortcutManager.tsx#L70
https://github.com/Shopify/quilt/blob/a8773ddc6c31bb90c55338967e0feee805eb8134/packages/react-shortcuts/src/ShortcutManager/ShortcutManager.tsx#L21

I think our typing here is wrong / we didn't expect chrome to trigger `keydown` when autofilling. This should be easy to fix cc @Shopify/web-foundations

**Comment by gmcgibbon** [comment]
Fixed in https://github.com/Shopify/quilt/pull/1578
