### ISSUE TITLE
Set up greenkeeper-lockfile

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#162]
⚠️ Greenkeeper found a yarn.lock file in this repository. Please use greenkeeper-lockfile to make sure this gets updated as well.

https://github.com/greenkeeperio/greenkeeper-lockfile

**Comment by tkbky** [comment]
Not sure if this is still relevant since greenkeeper has native lockfile support for public packages. https://blog.greenkeeper.io/announcing-native-lockfile-support-85381a37a0d0

**Comment by michenly** [comment]
Using dependabot instead
