### ISSUE TITLE
koa-shopify-webhooks isn't working with koa-body

### ISSUE THREAD

**Issue by soggie** [Shopify/quilt#1624]
## Overview

As title. If I have a koa installation that uses `koa-body` instead of `koa-bodyparser`, in the file `receive.js` the variable `ctx.request.rawBody` would be null, thus failing everything. I think it's worth pointing out the requirements in the documentation.

## Consuming repo

> What repo were you working in when this issue occurred?

`@shopify/koa-shopify-webhooks`

**Comment by gmcgibbon** [comment]
`bodyParser` is composed into the webhook receive function as middleware here: https://github.com/Shopify/quilt/blob/a8773ddc6c31bb90c55338967e0feee805eb8134/packages/koa-shopify-webhooks/src/receive.ts#L60

`rawBody` is added to the context here: https://github.com/koajs/bodyparser/blob/4d931c634e9b59a843152f56d68b3ef2e1719675/index.js#L81

We expect it to always be there, but parsing could fail (in your case I think `koa-body` might be causing the property set to fail). I think our typing is wrong here, we should define `rawBody` as nullable. cc @Shopify/web-foundations
