### ISSUE TITLE
Collaborating on GraphQL Tools and Codegens

### ISSUE THREAD

**Issue by dotansimha** [Shopify/quilt#1625]
Hi there!
My name is Dotan and I’m a member of an open source group called [The Guild](https://the-guild.dev).

We create and maintain a bunch of GraphQL related open source libraries like [GraphQL Tools](https://github.com/ardatan/graphql-tools), [GraphQL Codegen](https://github.com/dotansimha/graphql-code-generator), [GraphQL Inspector](https://github.com/kamilkisiela/graphql-inspector) and [others](https://the-guild.dev/open-source).

I’ve just seen the amazing tools you are building at Shopify and I thought it might be great to exchange ideas!

I had some initial thoughts, but maybe there are many more things to discuss and share ideas about:

We could discuss your `@shopify/react-graphql` library and it’s usage of [graphql-typescript-definitions](https://github.com/Shopify/graphql-tools-web/tree/main/packages) and graphql-typed packages. Like what we can learn from it and maybe integrate into GraphQL Codegen’s new [TypedDocuementNode](https://the-guild.dev/blog/typed-document-node).

Also, we recently [took over the GraphQL Config library](https://the-guild.dev/blog/graphql-config) and released a new v3 version. 
It is also integrated into the new GraphiQL and graphql-vscode extension.
We would love to learn from you about your graphql-config-utilities library and if we could learn and improve GraphQL Config from your experience.

Also, we recently took over the [GraphQL Tools](https://the-guild.dev/blog/graphql-tools-v6) library and improved it a lot, including merging a lot of known utility libraries into it.
Would be awesome to hear about your graphql-tool-utilities, graphql-fixtures, graphql-validate-fixtures, graphql-mini-transforms libraries and if there are lessons there we should share with our community.

Thank you for open sourcing and sharing such amazing tools and I hope we could learn from you more!

> Edit: didn't meant it to be label as `bug`, so feel free to change it :D

**Comment by GoodForOneFare** [comment]
cc @Shopify/web-foundations

**Comment by michenly** [comment]
@dotansimha Thank you for reaching out. 
There are quite a few things around GraphQL in flight at the moment and I am trying to figure out who may have the context and bandwidth to chat with you. This may take some time but rest assure you are not forgotten!

**Comment by TheMallen** [comment]
👋  We can definitely have a chat, feel free to reach out to me at mathew.allen@shopify.com directly :)
