### ISSUE TITLE
Currency list is out of sync with `Shopify/shopify`

### ISSUE THREAD

**Issue by cejaekl** [Shopify/quilt#1631]
## Overview

The list of currencies in `Shopify/quilt` has not been kept updated as we changed the list in `Shopify/shopify`.

The following changes are needed to bring them into sync again:

    New currencies:
      - `BYN` Belarusia New Ruble
      - `BMD` Bermuda Dollar (pegged 1:1 to USD)
      - `DJF` Djibouti Franc
      - `ERN` Eritrea Nakfa
      - `FKP` Falkland Islands Pound (pegged 1:1 to GBP)
      - `GIP` Gibraltar Pound (pegged 1:1 to GBP)
      - `GNF' Guinea Franc
      - `IRR` Iran Rial
      - `KID` Kiribati Dollar (pegged 1:1 to AUD)
      - `LYD` Libya Dinar
      - `MRU` Mauritania New (Second) Ouguiya
      - `PAB` Panama Balboa
      - `SHP` Saint Helena Pound (pegged 1:1 to GBP)
      - `SLL` Sierra Leone Leone
      - `SOS` Somalia Shilling (a fiat currency that is unique because it's no longer backed by a central bank)
      - `TJS` Tajikistan Simoni
      - `TOP` Tonga Pa'anga
      - `VES` Venezuelan Sovereign Bolivar

    Historical currencies that are being removed:
      - `BYR` Belarusia (Old) Ruble (replaced by `BYN`)
      - `VEF` Venezuealan Strong Bolivar (replaced by `VES`)

## Consuming repo

`Shopify/web`

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [X] Please delete the labels section before submitting your issue
- [X] I have described this issue in a way that is actionable (if possible)

**Comment by atesgoral** [comment]
Assuming this is where all the currencies are defined in shopify: https://github.com/Shopify/shopify/blob/master/db/data/currencies.yml
