### ISSUE TITLE
[Type: bug] [koa-shopify-webhooks] Unable to construct ApiVersion enum value

### ISSUE THREAD

**Issue by foresttoney** [Shopify/quilt#1639]
## Overview

TypeScript is failing to compile when registering a webhook because I can't construct an ApiVersion enum value. The primary issue is that while the enum is exported from [register.ts](https://github.com/Shopify/quilt/blob/a63ecc3f36b12b412aa5951b61960fb2f7a5db84/packages/koa-shopify-webhooks/src/register.ts#L5), it isn't re-exported from [index.ts](https://github.com/Shopify/quilt/blob/a63ecc3f36b12b412aa5951b61960fb2f7a5db84/packages/koa-shopify-webhooks/src/index.ts#L3). 

Further, providing a string value for ApiVersion [does not type check](https://github.com/microsoft/TypeScript/issues/17690).

```
await registerWebhook({
  accessToken,
  address: AWS_EVENT_SOURCE_ARN,
  apiVersion: "2020-04",
  deliveryMethod: DeliveryMethod.EventBridge,
  shop,
  topic: "ORDERS_CREATE"
})

>>>

TSError: ⨯ Unable to compile TypeScript:
server/index.ts:77:15 - error TS2322: Type '"2020-04"' is not assignable to type 'ApiVersion'.

77               apiVersion: "2020-04",
                 ~~~~~~~~~~

  node_modules/@shopify/koa-shopify-webhooks/dist/src/register.d.ts:20:5
    20     apiVersion: ApiVersion;
           ~~~~~~~~~~
```

In all the [examples](https://github.com/Shopify/shopify-demo-app-node-react/blob/b3cd9276ff19b27880923bcdd8b1a876c9a5af34/server.js#L10) I have seen, ApiVersion isn't constructed from `@shopify/koa-shopify-webhooks`, but from `@shopify/shopify-graphql-proxy`.  This would have type checked previously because the enums were the same. However, `ApiVersion` defined in `@shopify/koa-shopify-webhooks` was not updated to include July20 and therefore using `ApiVersion` from `@shopify/shopify-graphql-proxy` no longer type checks.

While updating and exporting `ApiVersion` from `@shopify/koa-shopify-webhooks` will satisfy TypeScript, having to import the same enum from two different packages isn't ideal (`@shopify/koa-shopify-webhooks` and `@shopify/shopify-graphql-proxy`).

## Consuming repo

@shopify/koa-shopify-webhooks

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by gmcgibbon** [comment]
> While updating and exporting ApiVersion from @shopify/koa-shopify-webhooks will satisfy TypeScript, having to import the same enum from two different packages isn't ideal (@shopify/koa-shopify-webhooks and @shopify/shopify-graphql-proxy).

Updating `ApiVersion` in `@shopify/koa-shopify-webhooks` and re-exporting it from the main index would make it so you could easily use _either_ enum though, right?

We could also look at moving API versioning logic to a separate package that both of these packages consume. Thoughts, @Shopify/web-foundations?

**Comment by foresttoney** [comment]
Yes, until the two type definitions fall out of sync again. Given that both type definitions are meant to represent the same thing, perhaps `ApiVersion` should be defined external to the two packages.

**Comment by atesgoral** [comment]
@gmcgibbon @foresttoney Would this new shared package be just for the ApiVersion enum?

**Comment by gmcgibbon** [comment]
Fixed by https://github.com/Shopify/quilt/pull/1641. Continuing package extraction in https://github.com/Shopify/quilt/issues/1683
