### ISSUE TITLE
Playground/ working examples

### ISSUE THREAD

**Issue by 9at8** [Shopify/quilt#165]
I feel like we should have a playground or some working examples (demos) for the packages. This could improve dev experience.

@TheMallen @tzvipm thoughts?

**Comment by tzvipm** [comment]
I don't think we necessarily need a playground, but I do like the idea of some toy examples. Perhaps these could also double as e2e test fixtures. It'd also be cool to see if we can include the examples as snippets in the markdown readmes. Perhaps the package readmes could be auto-generated, similar to the way I'm setting up the root readme.

A good place to start, IMO, would be just to improve the examples sections in each of the package READMEs, and see how helpful that is to people. thoughts?

**Comment by 9at8** [comment]
> I don't think we necessarily need a playground

I agree with you. We don't need a playground for every package.

> but I do like the idea of some toy examples. 

But since we are including these, it shouldn't be too hard to set up the dependencies and demo that toy example.

> A good place to start, IMO, would be just to improve the examples sections in each of the package READMEs, and see how helpful that is to people.

Yes!

**Comment by TheMallen** [comment]
I actually think it might be a good idea to use something like codesandbox for this
