### ISSUE TITLE
Better Link default behaviour from react-router package

### ISSUE THREAD

**Issue by ryanwilsonperkin** [Shopify/quilt#1672]
## Overview

See this Discourse link for full details: https://discourse.shopify.io/t/default-behaviour-of-linkcomponent-is-wrong-for-external-links/11940

TLDR: The `Link` component exported by `@shopify/react-router` should support external links.

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

We pass through the React-Router `Link` component in our `@shopify/react-router` package, but the Polaris documentation recommends a [code snippet](https://github.com/Shopify/polaris-react/blob/72748e3ddb7d60433ba6ed9d9895b390ffa7a283/src/components/AppProvider/README.md#using-linkcomponent) that each application implement that wraps this `Link` component if they want to support links to external URLs. Here's an example of where we had to manually implement this behaviour in ServicesDB: https://github.com/Shopify/services-db/pull/6459/

I'd argue that links to external URLs is the type of behaviour that we would want to support by default (and instead give you the ability to opt-out if desired) and that this behaviour should live in `@shopify/react-router`. This proposal would change the `Link` component to provide the behaviour mentioned in the snippet, and export the original `Link` as `ReactRouterLink`. I believe this would be a breaking change.

When generating a new app with `sewing-kit`, the default `web/foundation/Polaris.tsx` module looks like this:

```ts
import React from 'react';
import {Link} from '@shopify/react-router';
import {AppProvider} from '@shopify/polaris';
import {useI18n} from '@shopify/react-i18n';

interface Props {
  children?: React.ReactNode;
}

export function Polaris({children}: Props) {
  const [i18n] = useI18n({
    id: 'Polaris',
    translations: async (code) => {
      return import(`@shopify/polaris/locales/${code}.json`);
    },
  });

  return (
    <AppProvider i18n={i18n.translations} linkComponent={Link}>
      {children}
    </AppProvider>
  );
}
```

By providing this change, the included `linkComponent` prop would "just work" for external links, without requiring any override code.

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ryanwilsonperkin** [comment]
@alex-page would you be the right person to review if this is the right approach?

**Comment by alex-page** [comment]
@ryanwilsonperkin probably not as I haven't contributed to quilt before.

**Comment by BPScott** [comment]
I can take this from the Polaris side.
