### ISSUE TITLE
Apollo 3 support

### ISSUE THREAD

**Issue by gvarandas** [Shopify/quilt#1677]
## Overview

With the advent of [Apollo 3](https://www.apollographql.com/docs/react/migrating/apollo-client-3-migration/), the `ApolloClient`, some breaking changes were introduced, including centralization of imports and typedef changes.
These changes cause apps that have migrated to Apollo 3 and are currently using `graphql-testing` to load additional packages that now are part of `@apollo/client`.

That being said, I wanted to confirm that supporting Apollo 3 is something that's on the roadmap and also offer to create a PR to perform the initial migration if that's the case (and no one's currently working on it).

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

Client apps that are consuming the library and have migrated to Apollo 3 will load additional packages on their dependency graph, such as:

- apollo-cache-inmemory
- apollo-client
- apollo-link

One additional example of a breaking change is that the `GraphQL` type (from `graphql-controller.ts`) is using the `ApolloClient` type from `apollo-client`, which doesn't contain the `setLink` method, now present in the Apollo client exported by `@apollo/client`, causing errors when matching types from the library and this library.

**Comment by ismail-syed** [comment]
Apollo 3 is not on the team's roadmap. The team has been building an in-house lightweight graphql client, https://github.com/shopify/alpaql. cc/ @Shopify/alpaql

**Comment by gvarandas** [comment]
Thanks for the clarification, @ismail-syed. This will help our team streamline the decisions over migrating to Apollo 3.

**Comment by dohomi** [comment]
@ismail-syed I start looking into the use of @shopify/react-graphql-universal-provider and @shopify/react-graphql. Both packages consume v2 of apollo-client. The use of `graphql-codegen` also uses v3 of apollo-client which breaks the generator.
Could you lead me in the right way where the `alpaql` is in use and does it replace the need of `@shopify/react-graphql`? Thanks for clarification

**Comment by ismail-syed** [comment]
Hi @dohomi. `AlpaQL` is currently a private repository internal to developers at Shopify. This may change in the future.

**Comment by jcteague** [comment]
I made a fork of the graphql-testing library and updated it to work with Apollo 3. So far it's working for us, but there could be some edge cases that needs updating.  https://github.com/jcteague/graphql-testing

**Comment by 9at8** [comment]
@atesgoral any plans to open-source the in-house non-Apollo solution? :)
