### ISSUE TITLE
Better media mocks for jest-dom-mocks

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#169]
I was underwhelmed using out `matchMedia` mocks on a recent problem. It was awkward to simulate changing the media query/ calling listeners. I think it would be much nicer to simulate the media for the whole device (width, height, other things you can write media queries for), easily change these, and then stub `matchMedia` to return objects that would be correctly updated in response to these changes (by parsing their media query). Might be tricky but IMO would be a nicer experience.

**Comment by tzvipm** [comment]
Note for future us: This would involve a breaking change tot he `jest-dom-mocks` library
