### ISSUE TITLE
Support for offsetTop dimension

### ISSUE THREAD

**Issue by phobetron** [Shopify/quilt#1690]
## Overview

The `offsetTop` dimension should be included as a `dimension` that could be user-specified.

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

I've been looking into using this library to help test DOM scripting in Vue components. The only dimension that I currently need that seems to be missing is `offsetTop`.

### Area

- [ ] Add any relevant `Area: dimension` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: jest-dom-mocks` label.

- Is it related to a new package?
  - [ ] Tag it with the `New package` Label

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by gmcgibbon** [comment]
Could you clarify which package you are referring to? Quilt is a monorepo with 50+ packages.
