### ISSUE TITLE
support for IntersectionObserver v2 api

### ISSUE THREAD

**Issue by vidarc** [Shopify/quilt#1696]
## Overview

Requesting to see if there is interest in adding in support for IntersectionObserver v2 api. Currently seems to only be a Chromium feature though, https://caniuse.com/?search=isVisible

Might just need to add the ability to pass in isVisible to simulate and callback calls. Could check to see if trackVisibility option is passed in as to whether or not to add isVisible option. 

## Type

- [x] New feature
- [x] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

Currently using and the current jest-dom-mocks package lacks the ability to pass this option due to the normalize entry function. 

### Scope

- Is this issue related to a specific package?

- `Package: @shopify/jest-dom-mocks`

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by gmcgibbon** [comment]
If it is simply a property of the mock, I don't see a problem with adding this. I think it would be around [here](https://github.com/Shopify/quilt/blob/391d870796c74ccfcd6c5ae0bddf675524eec85f/packages/jest-dom-mocks/src/intersection-observer.ts#L50).
