### ISSUE TITLE
How to use @shopify/react-google-analytics ?

### ISSUE THREAD

**Issue by fataaaaaa** [Shopify/quilt#1711]
Hello anyone, i now create a shopify apps, and i need to track my apps with package @shopify/react-google-analytics.
Can someone give me example to use this package ? 

Thankyou before,
Im using React

**Comment by thecodepixi** [comment]
There is [some documentation here](https://github.com/Shopify/quilt/tree/master/packages/react-google-analytics) that might help you.

**Comment by atesgoral** [comment]
@fataaaaaa please take a look at the documentation @thecodepixi posted and open an issue if you encounter any problems. Closing this question for now.
