### ISSUE TITLE
[react-form] Dynamic list fields are incorrectly typed for the form's onSubmit

### ISSUE THREAD

**Issue by ryanwilsonperkin** [Shopify/quilt#1714]
## Overview

The TypeScript types are incorrect when handling the `fieldValues` parameter of the `onSubmit` function that is passed to `useForm` when using a dynamic list from `useDynamicList`.

Given this snippet of code: <details>
<summary>Code snippet to replicate the issue</summary>

```tsx
const {fields} = useDynamicList([{name: 'Ryan'}], () => ({name: ''}));
useForm({
  fields: {fields},
  onSubmit: async (fieldValues) => {
    ...
  },
});
```
</details>

`fieldValues` gets typed as

```ts
FormMapping<{fields: FieldDictionary<EditableLink>[]}, "value">
```

which would mean that the object's value should be accessed at:

```ts
fieldValues.fields[0].name.value
```

however in actual practice the argument that is passed to `onSubmit` is _not_ a `FieldDictionary` type, rather it is the actual value of the field, so it should be accessed like this:

```ts
fieldValues.fields[0].name
```

This results in bugs when trying to use the two together in a TypeScript project because the type system tells you you should be accessing the `value` property to get the string, when in fact that property does not exist.

A full example can be seen in [this CodeSandbox](https://codesandbox.io/s/usedynamiclist-submit-bug-61uxq?file=/src/App.tsx) which forks the original sandbox from the documentation and displays the result at the bottom. This result shows the JSON'ified version of `fieldValues` which can then be compared against what TypeScript says should be present.

### Potential Solution
The `FormMapping` type should be updated to handle the case where it has received an array of `FieldDictionary`s as one of the values in its `Bag`

## Consuming repo

https://github.com/shopify/services-db

**Comment by ryanwilsonperkin** [comment]
I'm still interested in a fix for this so I'll comment now to keep it from being stale. If there's a better approach for me to advocate for this please let me know 😄

**Comment by debchn** [comment]
👋 I just noticed this issue after I made one of my own! Pretty sure it's derived from the same bug, though I'm using `useList` instead of `useDynamicList`: https://github.com/Shopify/quilt/issues/1794

**Comment by ryanwilsonperkin** [comment]
Fixed by https://github.com/Shopify/quilt/pull/1795
