### ISSUE TITLE
useForm "undirty" itself after a failed submission when makeCleanAfterSubmit is true.

### ISSUE THREAD

**Issue by kai-lma** [Shopify/quilt#1717]
## Overview

The [`useForm`](https://github.com/Shopify/quilt/tree/a7594add91ec3fc3ddc73ec12865ba71c3d863f6/packages/react-form#useform) document state that:

> makeCleanAfterSubmit, A boolean flag (defaults to false) indicating whether the form should "undirty" itself after a **successful submission**. ...

I suppose that the return value of the `onSubmit` indicate whether or not the submission is successful. So when it return a `{ status: 'sucess' }` the subsmission is successful , and `{ status : 'fail', errors: [...] }` mean  it failed.

The problem is when `makeCleanAfterSubmit` is set to `true`, the failed submission also "undirty" the form itself.

### Steps to reproduce

* [makeCleanAfterSubmit: false](https://codesandbox.io/s/shopifyreact-form-2-forked-43mr4?file=/src/MyForm.tsx)
    1. fill in the name field with "error" text then submit the form
    2. the "error message" is shown 

* [makeCleanAfterSubmit: true](https://codesandbox.io/s/shopifyreact-form-2-forked-d8cyv?file=/src/MyForm.tsx)
    1. fill in the name field with "error" text then submit the form
    2. the "error message" is **not** shown (its supposed to be shown)

### Potential Solution

Either my assumption about "successful submission" is wrong or `makeCleanAfterSubmit` logic is not correct. So either:

1. Update the document to make it clearer.
2. Maybe we should return after `setErrors(result.errors); `

https://github.com/Shopify/quilt/blob/a7594add91ec3fc3ddc73ec12865ba71c3d863f6/packages/react-form/src/hooks/submit.ts#L57-L65

### Scope

- Package: react-form

**Comment by gmcgibbon** [comment]
Thank you for the bug report. I agree something looks off here, and the docs don't align with the behaviour. I think we meant to have

https://github.com/Shopify/quilt/blob/a7594add91ec3fc3ddc73ec12865ba71c3d863f6/packages/react-form/src/hooks/submit.ts#L63-L65

after

https://github.com/Shopify/quilt/blob/a7594add91ec3fc3ddc73ec12865ba71c3d863f6/packages/react-form/src/hooks/submit.ts#L60
