### ISSUE TITLE
Error importing apollo-client

### ISSUE THREAD

**Issue by blob84** [Shopify/quilt#1718]
When I run npm start I get this error:
```
./node_modules/@shopify/react-graphql/build/esm/hooks/query.mjs
"Can't import the named export 'ApolloError' from non EcmaScript module (only default export is available)"
```

**Comment by gmcgibbon** [comment]
Thanks for the report, but I can't tell what package you are referring to. If you could specify which package you are having trouble with, and an example of the issue (https://codesandbox.io/ or similar), we would be happy to help.

**Comment by patryk-smc** [comment]
Related: https://github.com/Shopify/quilt/issues/1722

**Comment by gmcgibbon** [comment]
Closing in favour of #1722, it is indeed the same problem spanning multiple packages.
