### ISSUE TITLE
Better documentation pattern

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#174]
We should have a better way of providing in depth documentation for our more complex packages.

There are many ways we might generate docs sites, or we might just want to have a standard template for writing docs in a package.

**Comment by TheMallen** [comment]
consideration: https://www.docz.site/introduction/deploying-your-docs

**Comment by tzvipm** [comment]
another consideration: https://github.com/angular/dgeni

**Comment by tzvipm** [comment]
Another consideration is to maintain better conventions / automation aroudn our READMEs. In particular, when we describe examples and APIs. I really like the concept of shortcodes in hugo, although I'm not sure how we might apply it: https://gohugo.io/content-management/shortcodes/.

**Comment by TheMallen** [comment]
We could also use TSDoc to provide another layer of docs (and help JS consumers who don't get as much typing support).

**Comment by tzvipm** [comment]
https://api-extractor.com/

**Comment by tzvipm** [comment]
I also like @9at8's suggestion of incorporating codesandbox into our docs.

**Comment by tzvipm** [comment]
This is all the hype these days: https://github.com/mdx-js/mdx

**Comment by TheMallen** [comment]
Some concerns a doc solution might want to think about 
- being type-aware
- living alongside code
- editor integration
- being easily rendered into a doc-site without us spending lots of time on maintenance
- being easily collated into a larger doc-site in the future (perhaps some sort of meta docs site for JS @ shopify)

I don't feel like any of these tools will solve the problem in itself, though I think TSDoc probably comes the closest, and would be valuable even if we didn't render documentation sites out of it as devs  would still get tooltips in their editors.
