### ISSUE TITLE
[koa-shopify-graphql-proxy] GraphQL API Version is not up to date

### ISSUE THREAD

**Issue by jabrms** [Shopify/quilt#1744]
## Overview

The ```ApiVersion``` object in ```shopify-graphql-proxy.ts``` is not up to date. Using ```ApiVersion.January21``` which is currently the latest API Version leads to errors, since the server tries to connect to ```https://<shop>.myshopify.com/admin/api/undefined/graphql.json```.

Edit: ```register.js``` in the ```koa-shopify-webhooks``` package has the same problem.

### Scope

Packages:
- @shopify/koa-shopify-graphql-proxy
- @shopify/koa-shopify-webhooks

**Comment by dahukish** [comment]
Feel free to open a PR(s) ❤️

**Comment by peter-hamilton** [comment]
Addressed in #2001
