### ISSUE TITLE
Move https://github.com/Shopify/graphql-tools-web into quilt

### ISSUE THREAD

**Issue by michenly** [Shopify/quilt#1753]
Quilt has many lib that make uses of lib in https://github.com/Shopify/graphql-tools-web

Having all those in the same place will :
1. Ensure update to graphql-tools-web pacakges will update  pacakges dep in quilt
2. Ensure all lib have chagelog
3. All our libs uses the same base dep such as typescript and graphql version.

-------

Things to watch out for:
- How to carry over repo history to quilt
- Some of the packages that `graphql-tools-web` uses under the hood does not exist and anymore or is very behind.

**Comment by BPScott** [comment]
Guessing we can close this now?
