### ISSUE TITLE
[react-form] enable sorting of Dynamic list fields

### ISSUE THREAD

**Issue by jonarnaldo** [Shopify/quilt#1765]
## Overview
Currently, if a user wants to rearrange a list they must manually remove items and/or add items.  I would like to propose a `moveItem` method which allow an item to be moved from `original index` to `new index` which would perhaps involve calling `removeItem` which takes the current index as an argument and a new `addItemAtIndex` which would take the desired index as an argument.  Additionally, moving an item should also trigger a 'dirty' state in the form.

Adding this functionality would also play nicely with UI packages like https://github.com/clauderic/react-sortable-hoc, where `moveItem` could be called within `onSortEnd`, for example.  
...

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

Currently working on https://vault.shopify.io/projects/16738 which uses [dynamic lists](https://github.com/Shopify/quilt/tree/main/packages/react-form#using-usedynamiclist) to display a series of items a user has added.  Updated UX Designs require the ability for user to sort items via drag handles.

Additionally, I think this would contribute to the overall user experience of any application that requires dynamic sortable lists as well as validation.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by dahukish** [comment]
Thanks @jonarnaldo! It looks like `moveItem` is already part of the api:
```
const {fields, addItem, removeItem, moveItem} = useDynamicList(
  [{cardNumber: '4242 4242 4242 4242', cvv: '000'}],
  emptyCardFactory,
);
```

**Comment by dahukish** [comment]
Closing as this has been merged.
