### ISSUE TITLE
Changelogs?

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/quilt#177]
I noticed we don't have any changelogs for our monorepo packages. Is this intentional? It might be worth exploring some best practices and automated tooling around changelogs for monorepos.

**Comment by TheMallen** [comment]
Not intentional really, we don't have a good strategy for this ATM. I would like us to start doing something like this though. If we ever actually set up conventional commits we could possibly automate it. It's definitely something I'd like to see in some form.

**Comment by michenly** [comment]
Done
