### ISSUE TITLE
Dev Style and Yarn Lint exit with error code 1

### ISSUE THREAD

**Issue by jamesmengo** [Shopify/quilt#1823]
## Overview
- Running `yarn lint` or `dev style` exits with error code 1 due. I believe this may be due to a stale dependancy
- This is similar to [this problem in discourse](https://discourse.shopify.io/t/app-node-modules-graphql-validate-fixtures-bin-graphql-validate-fixtures/15087/8), however the suggested solution did not work for me
- More info also in these slack threads
  - https://shopify.slack.com/archives/C58CNRGQH/p1617844462392100
  - https://shopify.slack.com/archives/CNH0GMZ41/p1616425455061700

## Consuming repo

> What repo were you working in when this issue occurred?

Shopify/Web

### Area

- [ ] Tooling

### Scope

- Is this issue related to a specific package?

  - [ ] Package: Graphql-validate-fixturesz

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by GoodForOneFare** [comment]
The [original solution from that topic](https://discourse.shopify.io/t/app-node-modules-graphql-validate-fixtures-bin-graphql-validate-fixtures/15087/5?u=gord_pearson) should work for web:

> You should remove that resolution and make sure you’re using at least graphql-validate-fixtures 0.14.2 in your yarn.lock file.

@ismail-syed as ATC, can you sync up with @jamesmengo to make that happen today, please?

**Comment by GoodForOneFare** [comment]
Also, sorry for not spotting Ben's solution last night 😬  I was just scanning stuff quickly, and didn't notice this was solved long ago.
