### ISSUE TITLE
[react-form-state] filter out unnecessary properties from fields 

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#184]
I'm not sure this is the right thing to do but I *think* it probably is. Right now we throw react warnings because we are including `initialValue` and other fields in the field descriptors that aren't actually real input props. We can pretty easily strip these out, since I don't think we ever really want to use them.

**Comment by TheMallen** [comment]
@m-ux @loic-d  do you think stripping initial value and stuff is fine for your usecases?

**Comment by loic-d** [comment]
This will not impact validation, right? You would just remove the unnecessary props from the state?

**Comment by TheMallen** [comment]
yeah it wouldn't it would just mean initialValue and dirty would not be on the field objects anymore
