### ISSUE TITLE
react-testing broken links in README.md

### ISSUE THREAD

**Issue by bowen9284** [Shopify/quilt#1933]
## Overview
There are two areas in the README.md where the conventions link is broken. I couldn't find a viable replacement, otherwise I'd open a PR.

#### Above the **Table of contents**
"A library for testing React components according to [Shopify conventions](https://github.com/Shopify/web-foundations/blob/main/handbook/Best%20Practices/Testing.md)."

#### In the **FAQ** section under `Why not use Enzyme instead?`
"It has a very large API surface area, much of which does not conform to Shopify’s [testing conventions](https://github.com/Shopify/web-foundations/blob/main/handbook/Best%20Practices/React/Testing.md). For example, Enzyme provides APIs like `setState` which encourage reaching in to implementation details of your components."

## Motivation
I noticed it while exploring the docs and I was interested in learning more about testing best practices at Shopify.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by michenly** [comment]
Hi @bowen9284 the link you mentioned above are broken because the repository had become private. You should have access to it now that you've join the Shopify github org :)

I will be removing the links in README going forward. Thank you for letting us know.
