### ISSUE TITLE
Escape curly braces in a i18n string

### ISSUE THREAD

**Issue by elhoyos** [Shopify/quilt#1960]
## Overview

`react-i18n` could help reducing boilerplate code and support escaping curly braces in strings:

```tsx
<TextField label={i81n.translate('myLabel')} />
```

```json
{
  "myLabel": "Glob pattern e.g. {{foo|bar}}.rb"
}
```

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

Translating strings that contain curly braces not intended as replacements result in a `MissingReplacementError`. I have tried escaping them with `\`, \`, `{{` to no avail.

To escape-hatch we can do:

```tsx
<TextField
  label={i18n.translate(
    'form.pattern.label'
  )}
  placeholder={i18n.translate(
    'form.pattern.placeholder',
    // HACK, react-i18n does not support escaping curly braces
    {
      '?customer_id,shop': '{?customer_id,shop}',
      contract_id: '{contract_id}',
    }
  )}
  {...pattern}
/>
```

where
```json
{
  "form": {
      "pattern": {
        "label": "URL template pattern",
        "placeholder": "https://myapp.com/path{?customer_id,shop}&id={contract_id}"
      },
  }
}
```

**Comment by dahukish** [comment]
I get what you are saying here but given the patten of place holders we use at Shopify, this seems to be more of an edge case that case live in the host application rather than this library. 🤷

**Comment by elhoyos** [comment]
Thanks for the feedback.

Do you consider this could be a valid use case for i18n text that should appear in non-place holders, for example, in links or paragraphs? Please notice that I'm not familiar with the pattern you mention.

I would be happy to help moving forward the idea in a PR.

**Comment by elhoyos** [comment]
I ended up interpolating for my use case because I found the translation of URLs was not really necessary.

Let's reopen if we find traction and valid use cases.
