### ISSUE TITLE
[react-html] Support for <script>some code here</script>

### ISSUE THREAD

**Issue by kaelig** [Shopify/quilt#198]
My use case: adding Google Analytics to a small app directly in the `<head>`.

Instead I'm having to do this, which doesn't appear in the `<head>` but in the body instead:

```jsx
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=UA-49178120-48"
        />
        <script
          dangerouslySetInnerHTML={{
            __html: `
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'UA-49178120-48');
          `,
          }}
        />
```

See https://github.com/Shopify/polaris-react/commit/7b9d125369f6b798cd9f2c12815d16b390180e82 where I sadly had to get rid of react-html just so I could add Google Analytics to the app.

Is there something I'm missing / doing wrong? (otherwise: please consider this as a feature request :) )

**Comment by kaelig** [comment]
Related: https://github.com/Shopify/web/issues/4478

**Comment by TheMallen** [comment]
This should just work with helmet so likely something is broken with how we're using it.
