### ISSUE TITLE
Humanize in react-i18n does not distinguish between "1 minute ago" and "1 minutes ago"

### ISSUE THREAD

**Issue by aktill** [Shopify/quilt#2029]
## Overview

@doctorhyde mentioned over on slack that the web timeline was showing events that happened between 1 and 2 minutes ago with the linguistically awkward description `1 minutes ago` as opposed to `1 minute ago`. Asked if someone could investigate

![shows singular as plural as above](https://screenshot.click/21-09-bjpgl-mg49s.png)
## Motivation

Investigation seemed to indicate that this could be tweaked in i18n.ts in quilt by inserting a case handling `isOneMinuteAgo` between `isLessThanOneMinuteAgo` and `isLessThanOneHourAgo`
<img width="592" alt="Screen Shot 2021-09-03 at 8 13 17 AM" src="https://user-images.githubusercontent.com/24965135/132045940-93082e3a-cfe7-4793-9875-e9a60b1e079f.png">

Have a possible solution underway

## Checklist

- [ X ] Please delete the labels section before submitting your issue
- [ X ] I have described this issue in a way that is actionable (if possible)

**Comment by movermeyer** [comment]
Users need to provide `one` and `other` keys for `lessThanOneHourAgo`:

```json
"lessThanOneHourAgo": {
  "one": "{count} minute ago",
  "other": "{count} minutes ago", 
},
```

Which means that the incorrect `quilt` docs need to get corrected: https://github.com/Shopify/quilt/blob/51fabc952487933f14ed62e9bdaea07606e40713/packages/react-i18n/migration-guide.md#L87-L123

**Comment by aktill** [comment]
Addressed by above linked PR
