### ISSUE TITLE
@shopify/react-testing Support for React 18

### ISSUE THREAD

**Issue by frandiox** [Shopify/quilt#2095]
## Overview

When upgrading to latest React 18 beta (`18.0.0-beta-fdc1d617a-20211118`) or experimental channel (`0.0.0-experimental-0cc724c77-20211125`), calling `mount(<Component />)` throws errors and warnings:

- Unable to find node on an unmounted component
- ReactDOM.render is no longer supported in React 18. Use createRoot instead

## Consuming repo

`shopify/hydrogen` ([branch here](https://github.com/Shopify/hydrogen/pull/312)), or any other repo using React 18.

**Comment by BPScott** [comment]
v4.1.0 of react-testing now supports react 18
