### ISSUE TITLE
Add a persistence provider that abstracts persistence across server/ client

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#212]

**Comment by TheMallen** [comment]
So is this basically an abstraction over the serializer component?

**Comment by lemonmade** [comment]
No, over react cookie + either localStorage (client) or session (server)

**Comment by michenly** [comment]
@lemonmade is this covered by the universal provider pattern or something else all togther?

**Comment by lemonmade** [comment]
I don’t think we need this much nowadays
