### ISSUE TITLE
Add a mechanism for providing some browser-related stats in server render

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#213]
Things like DPI would be great to get up front so we could fine tune GraphQL queries for the browser without any potential JS thrashing on page load. Could see this working fairly well by saving cookie values on the client and reading on the server.

**Comment by michenly** [comment]
@lemonmade can you provided more information on this?

**Comment by lemonmade** [comment]
I am just going to close, not totally sure I remember exactly what I meant
