### ISSUE TITLE
@shopify/react-i18n - formatCurrency with precision

### ISSUE THREAD

**Issue by dan003400** [Shopify/quilt#2130]
## Overview

When displaying currency, choose the precision you would like to display that currency in.

## Type

- [X] New feature

## Motivation

Display monetary amounts in areas of an app like chart axis.

**Comment by BPScott** [comment]
formatCurrency lets you pass `precision` into the object argument

```
formatCurrency(1.25345, {currency: 'CAD', precision: 3})
```
