### ISSUE TITLE
i18n.unformatCurrency returns NaN when passed "-"

### ISSUE THREAD

**Issue by zaquille-oneil** [Shopify/quilt#2174]
## Overview

While making use of a component that is unformatting a currency value with `i18n.unformatCurrency`, I stumbled upon a case where passing "-" (dash, subtract, negative, hyphen) alone to the method causes it to return `NaN`. This is not expected, as the return type for this method is `string`.

Same behavior for `i18n.unformatNumber`

Perhaps we should be returning empty string (`""`) if we encounter this case. Also, adding supporting tests for this case as well.

## Consuming repo
@shopify/web, working in the `web/app/components/CurrencyField/CurrencyField.tsx` file. In the definition of `unformat` method.

Resolves https://github.com/Shopify/core-issues/issues/34510

### Area

- [x] Add any relevant `Area: <area>` labels to this issue
- (I added "Area: tooling", but unsure if that's correct)

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by trishrempel** [comment]
@zaquille-oneil Please also check how `unformatNumber` responds to `-`, because it might also have the same bug.
