### ISSUE TITLE
Create utility to provide context/scope for translation ids

### ISSUE THREAD

**Issue by djhoughton** [Shopify/quilt#220]
On the server there is the ability to pass in a scope for an id which enables the caller to build up the key piece by piece. ([development handbook link](https://development.shopify.io/engineering/developing_at_Shopify/write-code/internationalization/string_externalization#_Interpolation))

For instance, to build the id a.b.c.d you can:

        I18n.t(
          'd',
          scope: ['a', 'b', 'c'],
          substitution1: 'some_value',
          substitution2: 'another_value',
        )
It would be useful if the client-side libraries allowed the user to pass in a scope array rather than having to build it manually before calling the translate() function.

Moved from https://github.com/Shopify/web/issues/5525.

**Comment by lemonmade** [comment]
This one is implemented in the react-i18n library once it is moved in: https://github.com/Shopify/quilt/pull/238

**Comment by tzvipm** [comment]
Closing via #238
