### ISSUE TITLE
[react-form-state] fork field typing based on whether the provided value is a valid choice value

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#227]
We should consider making choice fields (ones with `checked` as their current state prop) have their own typing and field generation logic. We can possibly do this using typescript conditional types.

`Value extends boolean | Indeterminate ? Field<V> : ChoiceField`

If this doesn't work well enough then we can only make an `asChoiceField` helper available for now and consider an api change that would make this type of thing better for a major release at some point.

**Comment by michenly** [comment]
duplicate issue https://github.com/Shopify/quilt/issues/673
