### ISSUE TITLE
Compatibility with jsdom 11.12.0 and higher

### ISSUE THREAD

**Issue by alexandcote** [Shopify/quilt#239]
`localStorage` and `sessionStore` can't be mock properly with `jsdom@11.12.0`.  Since sewing-kit bump jest version to `^23.0.0`, we are now facing an issue. 

The problem is in the [installMockStorage](https://github.com/Shopify/quilt/blob/master/packages/jest-dom-mocks/src/index.ts#L25-L36) method. 

```ts
Object.defineProperties(window, {
   localStorage: {
      value: localStorage,
   },
   sessionStorage: {
      value: sessionStorage,
   },
});
```
`window.sessionStorage` and `window.localStorage` can't be reassigned.

You can find more context on this [here](https://github.com/facebook/jest/issues/6798) and [here](https://github.com/jsdom/jsdom/blob/master/Changelog.md#11120)

A quick patch for us was to specify a resolution in the `package.json` of our project.
```
"resolutions": {
    "jsdom": "~11.11.0"
},
```

**Comment by amrocha** [comment]
Duplicate of #155

**Comment by alexandcote** [comment]
@amrocha It is not exactly the same issue. Here it `localStorage` and `sessionsStorage` only on `jsdom@~11.12.0` but we can trait this as one issue if you prefer.

**Comment by TheMallen** [comment]
We're on Jest 25 now, which supports JSDOM 15+
