### ISSUE TITLE
Broken/outdated links in react-testing's README

### ISSUE THREAD

**Issue by lucabezerra** [Shopify/quilt#2433]
## Overview

A couple of links are broken and/or outdated in `react-testing`'s README, namely:

- The link to React's `act()` block listed in [this section](https://github.com/Shopify/quilt/tree/main/packages/react-testing#-acttaction---t-t).
  - As a whole, React has moved into Facebook's repo. I tried finding the corresponding link there, but after a short search couldn't find it right away. I did find [this piece of code](https://github.com/facebook/react/blob/main/packages/jest-react/src/internalAct.js#L25), but as the docstring above it says, I don't think it's the one we're looking for. Might be easy to find the proper one, but I don't have enough time right now.
- The link to the peer dependency containing the supported React versions listed in [this section](https://github.com/Shopify/quilt/tree/main/packages/react-testing#what-versions-of-react-does-this-support).
  - The link should actually point to [this line](https://github.com/Shopify/quilt/blob/main/packages/react-testing/package.json#L50). I'm not writing a PR for it because it's such a minor fix, it'd make more sense to fix both things at once.

## Motivation

Link to proper resources.

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by BPScott** [comment]
Fixed in 0b4ced4c
