### ISSUE TITLE
[@shopify/react-form] `form.submitErrors` is not populated  when returning `{status: "fail"}`

### ISSUE THREAD

**Issue by jokull** [Shopify/quilt#2500]
## Overview

In a very simple example `submitErrors` is not populated.

## Consuming repo

> What repo were you working in when this issue occurred?

Made a reproducable example. https://stackblitz.com/edit/vitejs-vite-qctwdk?file=src/App.tsx

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by jokull** [comment]
I now understand what is happening. Inside the `useSubmit` hook the submit promise itself is early-returning because the `useMountedRef` ref has turned `false`. 

I'm not sure what the purpose of this early exit is. I would vote to remove it. 

The mounted ref flips to `false` as soon as I change the form state (on the first field `onChange`). Maybe this is related to React 18 changes?

**Comment by jamalsoueidan** [comment]
> I now understand what is happening. Inside the `useSubmit` hook the submit promise itself is early-returning because the `useMountedRef` ref has turned `false`.
> 
> I'm not sure what the purpose of this early exit is. I would vote to remove it.
> 
> The mounted ref flips to `false` as soon as I change the form state (on the first field `onChange`). Maybe this is related to React 18 changes?

Did you have a solution to this problem?

**Comment by jokull** [comment]
I use patch-package with this diff:
https://gist.github.com/jokull/fb17f617c3f449ffec6c2012a02751b0

**Comment by jamalsoueidan** [comment]
This is NOT fixed! I should did a fresh vite with react 18 and still is a problem!

**Comment by jamalsoueidan** [comment]
it's still a problem, strict mode is breaking it!

**Comment by jamalsoueidan** [comment]
@jokull  you have time to test it? Since I don't :(
