### ISSUE TITLE
useForm doesn't support the <Select>. I can't be the only person trying to use a dropdown (<Select>) field...

### ISSUE THREAD

**Issue by craigprobus** [Shopify/quilt#2573]
## Overview
useForm doesn't support the <Select>. I can't be the only person trying to use a dropdown (<Select>) field...

...

## Consuming repo

> What repo were you working in when this issue occurred? https://github.com/craigprobus/campaigner-prototype-001

...

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by timmoti** [comment]
@craigprobus How was this resolved for you? I'm using a Select component as well and wondering how to make it work with `react-form`.
