### ISSUE TITLE
Error: Missing translation for key: date.humanize.lessThanOneYearAway in locale: en

### ISSUE THREAD

**Issue by therealtgd** [Shopify/quilt#2634]
When using `i18n.formatDate()` from `@shopify/react-i18n` I am getting the error from the title.

Here is the [code sandbox](https://codesandbox.io/s/practical-poincare-k00tfd?file=/App.js) with the described issue.

**Comment by yuvrajharod** [comment]
Hey Mate, can you tell me how'd you resolve this issue? I am getting same and though i understand adding locale should do the job ideally but I wanted to use elements like 'Just now' or 'Yesterday at 10:12 am' 

I am guessing that has to be done using locale as well but are there any documentation present which can help me work through this?
