### ISSUE TITLE
Revise i18n utilities tests

### ISSUE THREAD

**Issue by apman** [Shopify/quilt#269]
The native JS functions `Intl.DateTimeFormat` and `Intl.NumberFormat` work differently in the test environment because node doesn’t include locale data like the Browser does. The given locale parameter will therefore be ignored and input always formatted according to the default locale.

This explains why there are several tests in [utilities.test.tsx](https://github.com/Shopify/web/blob/master/packages/%40shopify/i18n/tests/utilities.test.tsx) that should actually fail, but pass: e.g.  
```
expect(formatCurrency(1234.56, 'es', {currency: 'eur'})).toBe('€ 1,234.56');
```
The expected output should really be '1.234,56 €', but that would make the test fail, because the test environment does not use the supplied 'es' locale (Spanish), but the server default ('en' or 'en-US') instead.

As a minimum, the tests should be changed to just use 'en' as explicit input, to avoid the confusion of something evidently wrong passing as true. But it might also be worth to think through each function to see how meaningful the test result still is, given this limitation in node, and if it can be tested on a more informative level (?)  

(As @TheMallen commented earlier, we don't need to test the native functions - so for those of our functions that simply wrap the native ones we should just test if the right native function was called with the right input. `getCurrencySymbol` (#4807) is a bit more complicated as it uses the two of the functions indirectly.)

**Comment by TheMallen** [comment]
Closing this for now, feel free to reopen if it is still needed.
