### ISSUE TITLE
Add an inline server=> serializer/ deserializer

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#270]
I was thinking: why do we force people to pass serialized data into our `HTML` component, and then manually deserialize it in the client entry point? To me, it feels like we can be smarter here, where we have a component that knows how to serialize in a server environment/ retrieve serialized data from the DOM (warning: speculative, potentially bad component idea incoming):

```ts
// Our app component could serialize its own Apollo store, and rehydrate on the client:

import {WithSerializedData, Serialize} from '@shopify/cereal';

const APOLLO_DATA_ID = 'apollo-data';

return (
  <WithSerializedData id={APOLLO_DATA_ID}>
    {(data) => {
      const client = new ApolloClient(...);
      return (
        <>
          <ApolloProvider client={client)>...</ApolloProvider>
          <Serialize id={APOLLO_DATA_ID} data={client.cache.extract()} />
        </>
      );
    }}
  </WithSerializedData>
);
```

@Shopify/web-foundation thoughts?

**Comment by tzvipm** [comment]
I'm thinking it might be possible to include this in the react-html package or react-serialize?

**Comment by tzvipm** [comment]
Done :)
