### ISSUE TITLE
Phone Formatter package

### ISSUE THREAD

**Issue by eylamf** [Shopify/quilt#2749]
## Overview

Similar to the `@shopify/address` package, we want to extract the `PhoneNumberFormatter` utility from `@shopify/web`'s `utilities` folder, into its own Quilt package so that it can be used in different codebases within Shopify in order to ensure alignment on how we format phone numbers across Shopify.

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

We have multiple apps within Shopify that need this functionality (`web` Admin and Inbox), and we want to be consistent with all the usages.

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

- Is it related to a new package?
  - [x] Tag it with the `New package` Label

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by egjiri** [comment]
What repo is `Inbox` in?

**Comment by woodward4422** [comment]
Inbox client is a react native and react native web application hosted here https://github.com/Shopify/inbox-client
