### ISSUE TITLE
Add package.json#sideEffects to all Quilt packages

### ISSUE THREAD

**Issue by BlazingBBQ** [Shopify/quilt#289]
## Overview

Add `package.json#sideEffects` to all existing Quilt packages and modify the generator template to include this change in new packages.

## Motivation

This change would enable webpack to tree shake any unused code. 

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by BlazingBBQ** [comment]
Added the `sideEffect` to all Quilt packages, but did not add it to the generator template.

**Comment by GoodForOneFare** [comment]
Because these are public-facing libraries, and not everyone has our safeguards against accidental treeshaking.  `sideEffects: false` should be an informed decision.
