### ISSUE TITLE
[react-form-state] different implementation of FormState.List

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/quilt#298]
## Overview

We have a way of dealing with arrays of objects like this:

```jsx
<FormState.List field={fields.variants}>
  {(fields) => {
    <TextField label="Option" {...fields.option} />
    <TextField label="Value" {...fields.value} />
    <TextField label="SKU" {...fields.sku} />
    <TextField label="Price" {...fields.price} />
  }}
</FormState.List>
```

^^ this pattern doesn't work well when using the ResourceList component because it requires the array of objects to be intact.

```jsx
<FormState.List field={fields.variants}>
  {(variantsFields) => {
    <ResourceList
      resourceName={{singular: 'variant', plural: 'variants'}}
      items={variantFields}
      renderItem={this.handleVariantField}
    />
  }}
</FormState.List>
```

@michelleyschen has introduced another compound field called `FieldArray` (https://github.com/Shopify/facebook-marketplace/blob/master/app/ui/polaris-next/FieldArray/FieldArray.tsx) which keeps the array intact.

We could either look at pulling that implementation into FormState or look at changing the .List implementation?

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

We need to use the `ResourceList` to display the nested fields and the two APIs aren't very compatible.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
One way we could structure the api would be with a prop like

```
<FormState.List field={fields.variants} map>
  {(fields) => (
    <TextField label="Option" {...fields.option} />
    <TextField label="Value" {...fields.value} />
    <TextField label="SKU" {...fields.sku} />
    <TextField label="Price" {...fields.price} />
  )}
</FormState.List>
```
```
<FormState.List field={fields.variants}>
  {(variantsFields) => (
    <ResourceList
      resourceName={{singular: 'variant', plural: 'variants'}}
      items={variantFields}
      renderItem={this.handleVariantField}
    />
  )}
</FormState.List>
```

Or we could split it into two components where one consumes the other like:

```
<FormState.ListMap field={fields.variants}>
  {(fields) => (
    <TextField label="Option" {...fields.option} />
    <TextField label="Value" {...fields.value} />
    <TextField label="SKU" {...fields.sku} />
    <TextField label="Price" {...fields.price} />
  )}
</FormState.List>
```
```
<FormState.List field={fields.variants}>
  {(variantsFields) => (
    <ResourceList
      resourceName={{singular: 'variant', plural: 'variants'}}
      items={variantFields}
      renderItem={this.handleVariantField}
    />
  )}
</FormState.List>
```

**Comment by macdonaldr93** [comment]
I like `FormState.ListMap` and `FormState.List` personally 👍

**Comment by TheMallen** [comment]
With the updated syntax we could maybe even go one step further with the alternate syntax, and also offer some special utilities directly instead of making you import `arrayUtils`.

```
<FormState.List field={fields.variants}>
  {(variantsFields, {add, remove}) => (
    <ResourceList
      primaryAction={add({option: '', value: '', price: ''})}
      resourceName={{singular: 'variant', plural: 'variants'}}
      items={variantFields}
      renderItem={this.handleVariantField}
    />
  )}
</FormState.List>
```

**Comment by macdonaldr93** [comment]
What are the `add` and `remove` properties?

**Comment by TheMallen** [comment]
add and remove would be functions for generating handlers that add or remove elements from the array

**Comment by TheMallen** [comment]
This API is the primary list API in `react-form`, out hook based library.
