### ISSUE TITLE
[react-form-state] validate form programatically

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/quilt#299]
## Overview

The same way we get `submit` as a render prop from FormState, it would be great if we could get `validate` as a prop from FormState. We have a few use cases now where we need to run validation on initial render or hooked into other events than dirtying the form. Facebook Ads, Facebook Marketplace(@michelleyschen) and Marketing section (@darrenhebner).

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

For us, we need to run validation right away because the data gets pre-populated from the backend so the merchant needs to know what fields are invalid according to our app.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
@macdonaldr93 do you think it would make sense / be enough to just have a `validateOnMount` or `validateOnInitialize` prop?

**Comment by michelleyschen** [comment]
Not quite, the form fields can also hide / show based on a state change. I would also need to re-validate when those state change.

**Comment by TheMallen** [comment]
I'm not really sure I follow, if fields can hide and show based on a state change but the form was validated at the start wouldn't that be good enough? They'd still have their initial errors they would just be hidden.

**Comment by macdonaldr93** [comment]
Yeah I think in this particular case, a given field selection may drastically change the fields required in the form and therefore the validations needed. So when the field value changes, we'd want to re-run validation since some of the field requirements will change.

More concretely, we have a field that is product category. So if the product category field is set to Apparel, that means the MPN, Size, and Field X are required. But if the product category gets changed to something else, that won't be the case. Does that make sense?

**Comment by michelleyschen** [comment]
The use case I am running into:
1. Form start with 5 fields, validate on init => 5 errors count is shown on screen
2. User trigger a state change 
3. The form now show 3 fields, (but the form it self still have 5)
4. I have two choice at this point. 
1️⃣ re-run validation (where my validation are based on state)
2️⃣ count the number of error only for the form fields that's being shown.

I would prefer 1️⃣ because I have a few components that will count / show text acoordingly
but 2️⃣ is do able

**Comment by TheMallen** [comment]
Yeah, but what I'm asking is would that usecase not be handled by having all fields validate when any one is updated + the ability to have fields validate even when not dirty?

**Comment by michelleyschen** [comment]
cc @laranoell also have the same use case

**Comment by TheMallen** [comment]
closing this for now as the public `validateForm` method + `validateOnSubmit` should enable these usecases :)
