### ISSUE TITLE
[react-form-state] validate fields that aren't dirty

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/quilt#300]
## Overview

This is somewhat related to #299 as well... But essentially we need way to force validation on fields that haven't been dirtied yet. This can be an empty as well as a field that has data populated from the server.

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

Same thing as #299, we need to inform the merchant what fields are invalid according to our app. The merchant hasn't necessarily interacted with the page yet.

cc @michelleyschen 

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
When we add validation on submit and possibly validation on initialize, those will definitely not bail out when the field is not dirty. Given that being the case, is that sufficient? Or do you want to also validate fields that are not dirty when they are blurred?

**Comment by michelleyschen** [comment]
I would always want to validate not dirty. Except for submit.

**Comment by macdonaldr93** [comment]
Yeah it's almost like we need an additionally option where we don't just validate dirty fields. Like force validation or something like that. @michelleyschen I think this option could be at the form level right? I don't think we'd change between the two during the same form interaction.

**Comment by michelleyschen** [comment]
That's correct. Form level is sufficient

**Comment by TheMallen** [comment]
I'm not necessarily against a form level prop for this (eg. `validatePristine`) , but I just want to check in with you to make sure this would not be solved by the `validateForm` method added in `0.3.x`. Additionally, if this would be solved by validating fields that are `touched` (have ever been interacted with at all) instead of dirty.

**Comment by michelleyschen** [comment]
My use case is actually covered by using a combination of `validateForm` and `validateOnSubmit`, since now the logic is consistent in both to validate all the fields even if its not touched.
