### ISSUE TITLE
[react-form-state] a way to validate nested fields with other 

### ISSUE THREAD

**Issue by michenly** [Shopify/quilt#305]
## Overview

Given a form with type like
```

interface listItem {
  field1: string;
  field2: string;
}

interface Fields {
  list: listItem[]
}
```

I want to be able to validate `field1` with `field2`. 
ie. in the validator for `field1`, has the ability to access `field2` value.

The current custom Matcher type pass back `(input: Input, fields: Fields)`
which mean I can  access `field2` value like so `fields.list[index].field2`
if I can some how get the `index` information from the matcher as well.

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

In facebook market place channel.
If a product variant has GTIN, the MPN is not require.
![screen shot 2018-09-21 at 1 52 58 pm](https://user-images.githubusercontent.com/1610169/45897652-bfcdf700-bda5-11e8-9ece-fddf94351cf9.png)

(not that you can check the dropdown with label GTIN to filled in MPN.)

## Possible solution

1. Matcher to pass index of the list if the field is an array
```
export interface Matcher<Input, Fields = never> {
  (input: Input, fields: Fields, index?: number): boolean;
}
```

2. Matcher to pass a keyPath to current field

```
export interface Matcher<Input, Fields = never> {
  (input: Input, fields: Fields, inputKeyPath: string): boolean;
}
```

```
inputKeyPath while validating `field1` would be `list.0.field1`
```

3. Matcher to pass id of the input

4. Any other brilliant things

**Comment by iainmcampbell** [comment]
+1!

I have a similar use case, and I've tried to implement a hack which doesn’t work quite right. I don't need to validate one field against another specific field, just to make sure that two sub-fields in an array don't have the same input.

```ts
interface item {
  name: string;
}

interface Fields {
  list: item[]
}

const validators = {
  list: validateList({
    name: validate(isUniqueName, 'name must be unique')
  })
}

function isUniqueName(input, fields) {
  const allNames = fields.list.value.map(field => {
    return field.name;
  });

  const instanceCount = allNames.reduce((instances, name) => {
    return name === input ? instances + 1 : instances;
  }, 0);
  
  return instanceCount >= 2 ? false : true;
}
```

It mostly works, except for one case I've found. When you've got an error state, ie two items in list with the same name:

```
fields = {
  list: [
    {name: 'asdf'},
    {name: 'asdf'},
  ]
}
```

…the validator works, and marks both sub-fields as having the correct error.

But when you modify the second item, the error on the first item doesn't clear. The validator is called once for each item in the list, and returns the correct values, but the `error` prop of the first item doesn't get updated.

It looks like somewhere in `<FormState.Nested>` / `validateList` we might need to switch some things around to accommodate this 'linked field validation' thing.

**Comment by TheMallen** [comment]
related #185

**Comment by TheMallen** [comment]
The hooks version of the library supports this! Since the older one is no longer having features added to it I am closing this. :)
