### ISSUE TITLE
Confusing error when mutations missing from mock

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#313]
## Overview

When a mutation is missing from the mock graphql client options, a confusing error is thrown:

```
TypeError: Cannot read property 'data' of undefined
```

## Consuming repo

`Shopify/web`

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Not sure if this is still an issue please reopen if it is.
