### ISSUE TITLE
Allow string type when replacement is string.

### ISSUE THREAD

**Issue by michelleyschen** [Shopify/quilt#314]
## Overview

`i18n.translate('deleteModal.content', {replacements: {productTitle: '123'}})`
return the type `React.ReactElement<any>`

where it should return `string` because `productTitle` is type string. 

## Consuming repo
https://github.com/Shopify/facebook-marketplace/blob/13f7a70c9a179f91f16bbc970a13fa66bd0f8420/app/ui/sections/Listing/ProductListingDetails/ProductListingDetails.tsx#L338

**Comment by lemonmade** [comment]
@michelleyschen I think this is actually related to the version you are using. The need for `{replacements: {productTitle: '123'}}` was a bug that was fixed in the most recent version. I verified that in the most recent version, the following works correctly and is typed as `string`:

```
i18n.translate('deleteModal.content', {productTitle: '123'})
```

**Comment by michelleyschen** [comment]
Thank you so much @lemonmade , I will update the version instead.
