### ISSUE TITLE
Fetch mock has useless typings

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#319]
## Overview

Our mock for fetch comes out as having `any` type, making it impossible to know how to use it.

**Comment by tkbky** [comment]
@lemonmade I'm new to this project and I'm interested to pick up some low hanging fruits. For this one, do you think we should remove the `any` type in `const restoreSpy = jest.spyOn(fetchMock, 'restore') as any;` since it is not useful?

**Comment by lemonmade** [comment]
I am actually not too sure what the problem is here, I don't think it's the spies though. When I navigate to the type definition for this module, I get the following (for `fetch.d.ts`):

```ts
declare const augmentedFetchMock: any;
export default augmentedFetchMock;
```

**Comment by tkbky** [comment]
I am on latest master and I got the following for `fetch.d.ts`:

```
declare const augmentedFetchMock: AugmentedFetchMock;
export default augmentedFetchMock;
```

**Comment by lemonmade** [comment]
Whoops I just need to update our version, sorry for the confusion!
