### ISSUE TITLE
Can we have fine grain control over a Forms fields dirty state 

### ISSUE THREAD

**Issue by laranoell** [Shopify/quilt#323]
## Overview

We have a scenario in which a form field needs to fetch some data (it's a product picker with selected values) and then update formData with the fetched values. 

In this case, we don't want to wait for all of the initial values to resolve, so that we can allow merchants to interact with the form straight away. 

We also do not want the dirty state to be true, when the formData is updated to reflect the fetched values.

Can we add a feature that allows fine grain control of a fields dirty state?

## Type

- [x] New feature

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Maybe we could do something for updating the initialValue of a single field (like adding `updateInitialValue` to the `fieldDescriptors` or something

**Comment by TheMallen** [comment]
Could you put together an example of a usecase for this by forking the [sandbox](https://codesandbox.io/s/zx387x0vmx)?

**Comment by TheMallen** [comment]
So I think there are two things here:
- we can get away with only resetting fields that actually got new initialValues by default, avoiding resetting the whole form if only one field ends up changed asynchronously
- we can expose an api to plug in custom logic for how to update fields when their initial values change 

@laranoell how do you feel about the following api for the latter?

```typescript
interface Props<Fields> {
  initialValues: Fields;
  validators?: Partial<ValidatorDictionary<Fields>>;
  onSubmit?: SubmitHandler<Fields>;
  validateOnSubmit?: boolean;
  // new optional prop that gets called for each field when initialValues changes
  onInitialValueUpdate?: InitialValueMapper<Fields>;
  children(form: FormDetails<Fields>): React.ReactNode;
}

// looks like this (I know the generics are wordy)
interface InitialValueMapper<Fields> {
  <Key extends keyof Fields>(
    field: FieldStates<Fields>[Key],
    newInitialValue: Fields[Key],
    key: Key,
    oldState: FieldStates<Fields>,
  ): FieldState<Fields>;
}

// example usage

<FormState
  initialValues={this.initialValues}
  onInitialValueUpdate={(
    field: FieldStates<Fields>[Key],
    newInitialValue: Fields[Key]
    key: Key,
    oldState: FieldStates<Fields>,
  ) => {
    if (path === 'someField') {
      // do something custom
      return someCustomLogic(field, initialValue, oldState[key]);
    }
    // otherwise do the default behaviour
    return null;
  }}
>
...
```

**Comment by rexmac** [comment]
>we can get away with only resetting fields that actually got new initialValues by default, avoiding resetting the whole form if only one field ends up changed asynchronously

:+1:
