### ISSUE TITLE
[react-form-state] FormState.List uses key={index}

### ISSUE THREAD

**Issue by iainmcampbell** [Shopify/quilt#334]
## Overview

FormState.List renders its children [like so](https://github.com/Shopify/quilt/blob/e13a3f79508c18287eadf4b0a3103756403e9ac9/packages/react-form-state/src/components/List.tsx#L42):

```jsx
      return (
        // eslint-disable-next-line
        <React.Fragment key={index}>
          {children(innerFields, index)}
        </React.Fragment>
      );
```

I'm having two issues with the use of `key={index}` here, while trying to use `<FormState.List>` for a form with a user editable number of sortable, collapsible cards.

<img width="714" alt="screen shot 2018-10-05 at 5 31 41 pm" src="https://user-images.githubusercontent.com/3248903/46561178-8d9fb780-c8c4-11e8-9419-6e7c5f98e2eb.png">

Issues:

1. Cards are getting re-created when their order is changed, which resets their internal state (collapsed/expanded, in my use case). Demo here &rarr; https://codesandbox.io/s/2364ko292p.

   I don't want to use FormState to track collapsed/expanded because a) collapsing a card would trigger dirty state and b) I want to keep view state separate from form data.

2. I'm trying to integrate with the Draggable library, which we've done elsewhere in Partners (using React) and I'm getting either a broken list and a React error about memory leaks, or extra DOM elements, depending on how I've tried to work around the issue. Based on our other implementation in Partners, I think `key={index}` is the issue here. I can try to extract a codesandbox demo for this, but it's a lot harder to isolate.

## Potential Solutions

1. A mechanism to provide FormState.List with keys for arrays

2. use @michelleyschen’s `FieldArray` component (https://github.com/Shopify/quilt/issues/298) so I can run the `map()` loop myself and assign unique `key` props

## Consuming repo

- [Partners](https://github.com/Shopify/partners)

**Comment by michelleyschen** [comment]
link to https://github.com/Shopify/quilt/issues/305

**Comment by michelleyschen** [comment]
I had this working in https://github.com/Shopify/facebook-marketplace/blob/4f13747104a0d00be4ceac1d17cde5415329175c/app/ui/sections/Listing/ProductListingDetails/validators.ts#L21-L50 with a 🍴 version of `react-form-state`

It is no longer in master because the latest validation no longer require it.

**Comment by michelleyschen** [comment]
Have you tried `FormState.Nested` and name your nested field instead?

**Comment by iainmcampbell** [comment]
hmm, that's a good workaround. I think I’d have to refactor too much stuff though; I need to add this functionality to an already complete section which has a bunch of files that rely on the way `FormState.List` supplies properties as `FieldState`. I think I'm gonna use your `FieldArray` for now.

For potential solution number 1, I wonder if `FormState.List` could take an optional prop that specifies which object property to use for `key`. ie with this field data:

```js
const fields = {
  items: [
    {
      id: '1',
      ...
    },
    {
      id: '2',
      ...
    },
  ],
}
```

you could use `FormState.List` like so:

```jsx
<FormState.List field={formDetails.fields.items} childKey="id">
```

…and it would use `item.id` for the `key` prop of each of the children it renders.

@TheMallen, what do you think?

**Comment by TheMallen** [comment]
I like childKey! I also wonder if we should use `FieldArray` in this package (and maybe build List on top of that).

**Comment by TheMallen** [comment]
If you want to take a stab at the `childKey` PR that would be amazing, otherwise I likely won't be able to get to it for a bit.
