### ISSUE TITLE
Update `onSubmit` typing to support `Promise<remoteErrors[] | undefined>`

### ISSUE THREAD

**Issue by loic-d** [Shopify/quilt#342]
## Overview

If the submit function passed to the `onSubmit` prop does not return anything. TS will complain. The interface seems to be a little too restrictive. 

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

Realized TS complained. The typing feels a bit too restrictive. The workaround is to return an empty array but we might as well update the interface to support `Promise<remoteErrors[] | undefined>`.

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Not sure if this is still an issue, but as we are mostly pushing folks to switch to the hooks library I would rather see this reopened if applicable targeting that.
