### ISSUE TITLE
[react-form-state] non-dirty sub-fields get validated on blur of a fellow sub-field

### ISSUE THREAD

**Issue by debchn** [Shopify/quilt#343]
## Overview

Sub-fields of `<FormState.Nested />` and `<FormState.List />` validate on blur of any other sub-field. This leads to early validation of non-dirty fields, and a buggy looking UI, e.g.:

![Shipping GIF](http://g.recordit.co/IbKqoylfuX.gif)

## Consuming repo

> facebook-marketplace

See https://github.com/Shopify/facebook-marketplace/issues/695

**Comment by TheMallen** [comment]
This is a fun one. I'm planning to do a bit of an overhaul of how the nested valdiators work for v1.0, so this will definitely be one of the main things to fix there.

**Comment by TheMallen** [comment]
@debchn so I can make sure I take into account everything going on here:
- what version of `react-form-state` is this?
- are these custom validators?
- are you using `validate` or `validateRequired` for these validators?

**Comment by debchn** [comment]
Hey @TheMallen, sorry for the late reply (was on vacation).
When I made this issue, we were on v0.2.3 and only using `validate` (with custom validators) within `validateNested`.

**Comment by TheMallen** [comment]
I think if the following are true this is mitigated:
- you're on .5.x
- you're using the non-`required` family of validators / validation helpers

example video: https://monosnap.com/file/Kis2waCreHhLFB7uzNTI2ocRL0zKYD

As far as solving this more generally, the way that validators and Nested/List work is going to have to go through a big change to fix some of the issues with them, I'm hoping to look at that when the current sprint is over.

If you have specific cases for this and the other bugs like it, it'd be super helpful if you could fork the [sandbox](https://codesandbox.io/s/zx387x0vmx) with a reproducible case :)

**Comment by jfangrad** [comment]
@TheMallen using your example form, if I start with blank values in the nested section and then change the "values" input (which has no validation on it) the sibling field "option" still gets validated. Is there a way to avoid that? This is the biggest issue that my team is facing.

![screencast 2018-12-11 16-19-54](https://user-images.githubusercontent.com/11445215/49831004-c5155f00-fd60-11e8-9845-2ce990499b80.gif)

**Comment by TheMallen** [comment]
The only workaround atm would be not using the `required` family of validators, since the others bail on an empty input. Otherwise no that's exactly why Nested / List need to be rethought

**Comment by debchn** [comment]
Thanks @TheMallen
Our team is facing the same issue as @jfangrad's (i.e. we need `required` validators on our nested fields). Interested in the big re-think—keep us in the loop!

cc @HiFiSamurai

**Comment by axelerator** [comment]
Hi, is there anything planned in the near future to address this?

**Comment by lordofthec4ctus** [comment]
@TheMallen Hi, we are facing the same issue. If anybody here has any suggestion for checking nested fields that are required, we would love to know.
