### ISSUE TITLE
[react-i18n] document Object.entries polyfill for Safari 10

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/quilt#369]
## Overview

We hit a bug in Facebook Ads (https://github.com/Shopify/facebook-ads/issues/2266) where we were missing `Object.entries` in Safari 10. Documenting this polyfill would be good since Safari 10 is still a supported browser for now.

## Consuming repo

Facebook Ads (https://github.com/Shopify/facebook-ads/issues/2266).

Here's the PR for the polyfill (https://github.com/Shopify/facebook-ads/pull/2312). It would be worth documenting the best way to polyfill this since I was unsure how to include the polyfill.

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Closing this as safari 10 was a while ago and it is likely not worth documenting anymore. Feel free to reopen.
