### ISSUE TITLE
Align formatDate DateStyle formats with shopify-i18n

### ISSUE THREAD

**Issue by patsissons** [Shopify/quilt#398]
## Overview

#397 is adding some basic date format options from the legacy i18n solution, but we ultimately want to align with the [pre-existing work](https://github.com/Shopify/shopify-i18n/blob/c712269cd2f97d5fd72c02d35c58c201d60255da/config/locales/rules/en.rb#L26) in [`shopify-i18n`](https://github.com/Shopify/shopify-i18n). 

## Type

- [ ] New feature
- [x] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing,
> or what else makes you think this should be in `quilt`?

The work in #397 was a first pass at bringing in similar functionality, with an expected second pass to fill in remaining formats.

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

- Is it related to a new package?
  - [ ] Tag it with the `New package` Label

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by darrenhebner** [comment]
Hey @patsissons - I'm looking to make use of some of the humanized date formats that Polaris recommends. Things like `13 minutes ago`, or `Yesterday at 10:30`. 

Was this ticket meant to address this?

The full list of recommended formats is here: https://polaris.shopify.com/content/grammar-and-mechanics#section-dates-numbers-and-addresses

**Comment by patsissons** [comment]
oof, this one is old 😂. I seem to recall this issue was just to add the initial `DateStyle` enum to `react-i18n` and should have probably been closed many moons ago. feel free to close it with any new efforst you plan on addressing 👍

**Comment by darrenhebner** [comment]
haha, true. I'll start a new ticket with the Polaris specific formats.
