### ISSUE TITLE
[koa-shopify-auth] Unsorted query params

### ISSUE THREAD

**Issue by DanWebb** [Shopify/quilt#438]
## Overview

The `ctx.query` isn't lexicographically sorted as specified in https://help.shopify.com/en/api/getting-started/authentication/oauth

This causes an invalid HMAC error when the query isn't in the correct order (like it wasn't in my case).

I had to implement extra middleware before the `createShopifyAuth` call to get it working:
```
app.use(async (ctx, next) => {
  const orderedQuery = {};
  Object.keys(ctx.query).sort().forEach(key => {
    orderedQuery[key] = ctx.query[key];
  });
  ctx.query = orderedQuery;
  await next();
});
```

## Consuming repo

[koa-shopify-auth](https://github.com/Shopify/quilt/tree/master/packages/koa-shopify-auth)

**Comment by TheMallen** [comment]
Thanks for the issue, that sounds very annoying to debug 😬, glad you have a workaround for now.
