### ISSUE TITLE
Add `initialErrors` prop to FormState

### ISSUE THREAD

**Issue by darrenhebner** [Shopify/quilt#444]
## Overview
We have a case where our form initializes with remote errors. We would like to pass these errors to `FormState` so the errors can be tracked the same way other remote errors are tracked.

Currently the only way `FormState` can know about remote errors is if you return errors when submitting the form.

We would be able to put together a PR to add this feature if the team thinks it's a good idea.

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation
We currently have to track our initial errors outside of `FormState`. On submit, we clear these initial errors and then use `FormState` to track any new remote errors that get returned. 

This gets a bit confusing to follow. 

```jsx
class MyComponent extends React.Component {
    state = {
        initialErrors: [{message: 'Example error'}]
    }

  render() {
    const {initialErrors} = this.state;
    
    return (
      <FormState
        onSubmit={async (formDetails) => {
          const response = await submitFormMutation(formDetails);
          
           if (response.errors) {
               this.setState({initialErrors: null});
               return response.errors;
           }
        }}
      >
        {({errors}) => {
           const errorsToDisplay = errors || initialErrors;
           return (
             <Banner>
               {errorsToDisplay.map(error => <li>{error.message}</li>)}
             </Banner>
           )
        }}
      </FormState>
    )
  }
}
```

Here's what we would ideally be able to do

```jsx
function MyComponent() {
   return (
     <FormState
        onSubmit={async (formDetails) => {
          const response = await submitFormMutation(formDetails);
          
           if (response.errors) {
               return response.errors;
           }
        }}
        initialErrors={[{message: 'Example error'}]}
     >
        {(errors) => (
            <Banner>
               {errors.map(error => <li>{error.message}</li>)}
             </Banner>
        )}
     </FormState>
   )
}
```

cc / @TheMallen @jim-chou-shopify

**Comment by TheMallen** [comment]
As we talked in meatspace, I'd rather see this as an `errors` or `externalErrors` prop with no built in reseting logic. That way the feature could also be used for async validators and stuff like that. The main reason is just that adding more state that has to reset at odd times will increase the number of broken edgecases and likelihood of needing more apis like #323 suggests.


My counter suggestion would look like:

```typescript
class MyComponent extends React.Component {
    state = {
        externalErrors: [{message: 'Example error', field: 'foo'}]
    }

  render() {
    const {externalErrors} = this.state;
    
    return (
      <FormState
        initialValues={{foo: ''}}
        externalErrors={externalErrors}
        onSubmit={async (formDetails) => {
          const response = await submitFormMutation(formDetails);
          
           if (response.errors) {
               // we still need to clear the errors ourselves because formstate 
              // doesn't know what they represent or when to clear them
               this.setState({externalErrors: null});
               return response.errors;
           }
        }}
      >
        {({fields, errors}) => {
           return (
             <Banner>
              {/* the externalErrors get seamlessly added to the errors array */}
               {errors.map(error => <li>{error.message}</li>)}
             </Banner>
               {/* and passed down to matching fields */}
              <TextField {...fields.foo} />
           )
        }}
      </FormState>
    )
  }
}
```

A cool thing about this api is we can also use it to build async validation components without needing to add any api to formstate.

```typescript
class MyComponent extends React.Component {
    state = {
        externalErrors: []
    }

  render() {
    const {externalErrors} = this.state;
    
    return (
      <FormState
        initialValues={{foo: ''}}
        externalErrors={externalErrors}
        onSubmit={async (formDetails) => {
          const response = await submitFormMutation(formDetails);
          
           if (response.errors) {
               return response.errors;
           }
        }}
      >
        {({fields, errors}) => {
           return (
             <Banner>
               {errors.map(error => <li>{error.message}</li>)}
             </Banner>
              <TextField {...fields.foo} />
              {/* this would return the same type of error objects */}
               <RemoteValidation 
                   fields={fields} 
                   url={someUrl} 
                  onFail={(externalErrors) => this.setState({externalErrors}}
                />
           )
        }}
      </FormState>
    )
  }
}
```

If this won't work for you let me know, but keep in mind how something like `initialErrors` would reset / react to updated props. I'm totally open to alternative suggestions.

**Comment by darrenhebner** [comment]
@TheMallen - That sounds great. I'm just working on adding this feature now.

**Comment by jim-chou-shopify** [comment]
@TheMallen I agree. The api allows developers to have control of how externalErrors are managed.
On the flip side, I see possibility for FormState to manage externalErrors and support remote validation.

Under the assumption that external errors are always clear on submit success similar to remote errors.
It's possible to return an error promise in the onFail callback of RemoteValidation to update externalErrors.
