### ISSUE TITLE
shopStore from shopify-express

### ISSUE THREAD

**Issue by sam-cnet** [Shopify/quilt#452]
Will we see similar options like 'shopStore' in upcoming releases?

**Comment by TheMallen** [comment]
ATM we have no plans to release something like that, but one of the advantages of the more granular multi-module approach the koa stuff uses is that you can pretty easily integrate something like it into an app using them. Is there a particular usecase you need it for?

**Comment by sam-cnet** [comment]
To be able to save the accesstoken and shop domain in a MySQL DB. It just sucks how shopify-express was deprecated with a Koa version that feels incomplete. Can you maybe point me to a roadmap?

Sent from my iPhone

On Dec 24, 2018, at 4:39 PM, Mallory Allen <notifications@github.com<mailto:notifications@github.com>> wrote:


ATM we have no plans to release something like that, but one of the advantages of the more granular multi-module approach the koa stuff uses is that you can pretty easily integrate something like it into an app using them. Is there a particular usecase you need it for?
