### ISSUE TITLE
Remove lodash from react-form-state

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#472]
## Overview

We currently use `lodash` in `@shopify/react-form-state`. This ends up causing lodash to be included in whichever vendor bundle `react-form-state` ends up in. Stranger yet, somehow this happens even if `lodash` is also in a different vendors bundle, so we end up getting it and `lodash-decorators` twice (~20kb).

## Consuming repo

`Shopify/web`

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by TheMallen** [comment]
Yeah, we can make simpler versions of set / deepEquals pretty easily. I had a branch that did this actually. We could even drop the decorators probably, though memoize would be a pain to handroll
