### ISSUE TITLE
Adding custom methods to koa context mock

### ISSUE THREAD

**Issue by krajowski** [Shopify/quilt#484]
## Overview
What's the best/correct way to extend koa ctx mock with custom methods?
...

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation
I have custom methods (either from npm package i.e. koa-respond that adds ctx.ok, ctx.send etc., or my own i.e. ctx.fail to throw custom errors).

I am adding them to jest-koa-mocks the following way today:
```
beforeEach(() => {
  ctx = createMockContext({ state: { config } })
  ctx = {
    ...ctx,
    send: jest.fn((status, body) => {
      ctx.response = { status, body }
    }),
    ok: jest.fn(body => ctx.send(200, body)),
  }
})
```

is there a better way to do so?
...

### Scope

Package: @shopify/jest-koa-mocks

**Comment by ismail-syed** [comment]
Hey, sorry for the delay. You can attach custom properties like [this](https://github.com/Shopify/quilt/blob/master/packages/jest-koa-mocks/src/create-mock-context/test/create-mock-context.test.ts#L179).
