### ISSUE TITLE
ValidateList and ValidateNested functionality is broken (0.7.0 version is OK)

### ISSUE THREAD

**Issue by dcugalj** [Shopify/quilt#500]
## Overview

Played with https://codesandbox.io/s/x94lqqkxxq. Validation on options in Variants section does nothing

## Consuming repo

> What repo were you working in when this issue occurred?

...

## Labels

- [ ] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by tzvipm** [comment]
Note: 0.7.4 is also working in that codesandbox.
