### ISSUE TITLE
React I18n / Expose client timezone on `I18n`

### ISSUE THREAD

**Issue by loic-d** [Shopify/quilt#503]
## Overview

Expose the client's timezone on `I18n`.

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

In some scenarios we need to know the client's timezone to calculate time offsets between a shop's timezone and the browser's timezone.

This can easily be done:

```
export function getBrowserIanaTimeZone() {
  return Intl.DateTimeFormat().resolvedOptions().timeZone;
}
```

This could easily be exposed on `I18n` as a getter `clientTimezone` or something like that.

This will also be easier to test. At the moment we are mocking `Intl.DateTimeFormat().resolvedOptions().timeZone` in our tests.

```
let resolvedDateFormatOptions: jest.SpyInstance;
const initialDateFormatFormat = Intl.DateTimeFormat();
  resolvedDateFormatOptions = jest.spyOn(Intl, 'DateTimeFormat');
  resolvedDateFormatOptions.mockImplementation(() => ({
    format: initialDateFormatFormat.format,
    resolvedOptions: () => ({
      ...initialDateFormatFormat.resolvedOptions(),
      timeZone: 'America/Toronto',
    }),
  }));
```

If the client's timezone was directly exposed on `I18n`, it would be easier to mock.

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
I don't believe this is still an issue. Please re-open if it is.
