### ISSUE TITLE
[Type: Bug] [Package: koa-shopify-auth] Status Code 400 for /auth path

### ISSUE THREAD

**Issue by juliantrueflynn** [Shopify/quilt#506]
## Overview

When visiting authorization path, browser console logs status code 400. I get this error when using the default path ("/auth") or custom paths using properties `prefix`, `authRoute`, and `fallbackRoute`. This error is also logged on all child paths, example: `/auth/inline?shop=`.

The authorization process still works as expected otherwise.

![status 400 auth](https://user-images.githubusercontent.com/2691129/52436753-16349b80-2ae3-11e9-9c24-e69e38b2defe.png)

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/juliantrueflynn/shopify-koa-app-example/tree/fix__400-auth/complete-app

**Comment by TheMallen** [comment]
@ragalie any idea where this might come from? I don't think this happened pre-ITP fixes

**Comment by ragalie** [comment]
Hmmm, I don't know where this would be coming from. Pinging @tylerball who's been working on the ITP 2.1 updates, maybe he has some ideas?

**Comment by ismail-syed** [comment]
I don't believe this is still an issue. Please re-open if it is.
