### ISSUE TITLE
React form state / Error not propagating to form field

### ISSUE THREAD

**Issue by loic-d** [Shopify/quilt#512]
## Overview

Form field error is not properly propagated to field after submission with 'Enter' key.

The field name in the error matches the form field.

<img width="343" alt="screen shot 2019-02-11 at 9 25 50 am" src="https://user-images.githubusercontent.com/3925905/52569392-15e81900-2ddf-11e9-85c5-960a586afd7a.png">

<img width="271" alt="screen shot 2019-02-11 at 9 26 00 am" src="https://user-images.githubusercontent.com/3925905/52569394-18e30980-2ddf-11e9-9eb7-52904209b9a4.png">

This field is using the `CurrencyField` from `polaris-next`.

I tried to reproduce in a code-sandbox but I can't reproduce it. Could be related to how we are using React form state with the `CurrencyField`.

Also tried to remove the `fieldsWithHandlers` cache but the issue persists.

The issue is reproducible on the `DiscountShow` page when creating a fixed amount discount without a money value and submitting the form with the 'Enter' key.

## Consuming repo

> What repo were you working in when this issue occurred?

`web`

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
Is this still an issue?

**Comment by loic-d** [comment]
I think we can safely close it as developers should use `react-form`
