### ISSUE TITLE
[Type: Bug] [Package: react-i18n] Timezone related test failing only at certain times of the day

### ISSUE THREAD

**Issue by jamesism** [Shopify/quilt#513]
## Overview

While running the quilt test suite in the hours around midnight (+/- 2) I noticed a failing test from `react-i18n`. I don't have timestamps in my prompt unfortunately, so I don't have an exact time. 

![image](https://user-images.githubusercontent.com/887305/52588288-16e27000-2e0a-11e9-9fe6-5fd33a12c45f.png)

Please excuse my weird terminal background.

## Consuming repo

> What repo were you working in when this issue occurred?

`react-form-state`, but hunch is definitely that it is about the time at which I was running the tests and specific to `react-i18n`.

**Comment by jamesism** [comment]
cc @shopify/insights-web-developers : was mentioned in slack that you added this test

**Comment by joshuajay** [comment]
Yeah, this is likely some kind of DST related bug. If the late night test failures are problematic we can ship a quick PR that skips the test while we figure out the underlying issue..

**Comment by joshuajay** [comment]
looks like this was fixed in https://github.com/Shopify/quilt/pull/510
