### ISSUE TITLE
FormState.List is broken when initialValue is empty array

### ISSUE THREAD

**Issue by marina101** [Shopify/quilt#519]
## Overview
*Urgent*
We noticed that FormState.List no longer works for us on a form where initialValue is an empty array. It used to work and we haven't changed our code, so we started digging in the List source. I think the regression got introduced here: `https://github.com/Shopify/quilt/commit/300389252b8d367b66b93690c4cda502cb9e7025#diff-68157ac38fbcaa003b546774b1857293R48`  on line 48 in `packages/react-form-state/src/components/List.tsx`.  When `initialValue[index]` is called on an empty array with index 0, it returns undefined, so `const initialFieldValue = initialValue[index][fieldPath];` throws an error.

This is blocking us on a form that is payments compliance related with a hard deadline coming up soon, so we'd really appreciate it if it would be possible to fix this as soon as possible. Relates to Shopify/shopify#188581

## Consuming repo

Shopify/web

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by axelerator** [comment]
Introduced here:
https://github.com/Shopify/quilt/pull/475/files#diff-68157ac38fbcaa003b546774b1857293R48
