### ISSUE TITLE
FormState.Nested does not re-render children if nested fields don't change

### ISSUE THREAD

**Issue by patsissons** [Shopify/quilt#557]
## Overview

In cases where nested fields are bound to components that also react to parent component state, when the parent component state changes the nested component will not re-render because only the parent state has changed, not the bound `FormState` fields.

A simple example would be a `<TextField />` that is bound to a form field, but perhaps has its `readOnly` prop driven by parent component state. When the parent component calls `setState` the `FormState.Nested` will see a re-render, but because the bound field doesn't change the `shouldComponentUpdate` returns `false` and the render props are never invoked.

This behaviour was originally observed using a Modal whose `open` prop was driven by parent component state. The modal would never open because the state change would never result in the nested component re-rendering.

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/Shopify/web

**Comment by amireynoso** [comment]
To add on that, the same problem is observed in `FormState.List`.

Another example (and it's actually my use case): a dropdown select which options are loaded from GraphQL. So, initially, it’s an empty array that then gets populated. Since the actual value of the field never changes, the dropdown doesn’t get re-rendered.

**Comment by amireynoso** [comment]
Looks like this was introduced in #312, with good reasoning behind it.

I'm thinking maybe adding a new prop to these components (maybe something like `update`, defaults to `false`) that if set, will ignore the checks in `shouldComponentUpdate`. This way, we keep the performance boost for most cases, and it's possible to opt-out of it. I don't, however, really like the idea of changing / adding to the API. 🤔 

@jfangrad @TheMallen What do you think?

**Comment by patsissons** [comment]
Yea my initial thought was to add a `state?: {}` prop and then include a deep compare in the `shouldComponentUpdate`

**Comment by amireynoso** [comment]
I just opened https://github.com/Shopify/quilt/pull/558 to address it, would love some eyes on it  👀

**Comment by amireynoso** [comment]
Resolved in `@shopify/react-form-state@0.9.0`. 🙂
