### ISSUE TITLE
Add formdata polyfill to polyfills

### ISSUE THREAD

**Issue by tzvipm** [Shopify/quilt#604]
## Overview

On the client side, we should include `formdata-polyfill`, and nothing on the server.

## Type

- [x] New feature
- [ ] Changes to existing features

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
I don't believe this is still an issue. Looks to be supported on all major browsers. Please re-open if it is.
