### ISSUE TITLE
[react-testing] `.toHaveReactProps` typing issue

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#641]
## Overview
It seems that `.toHaveReactProps` is not inferring the types for acceptable props assertions correctly when called on the result of a `wrapper.find`. We should be able to assert against any of the props on the component.

### Reproduction
- Create a test case
- Mount a react component
- `find` a child element
- pass the result to `expect` and invoke `.toHaveReactProps`

### Screenshots
![image](https://user-images.githubusercontent.com/4889856/55829140-fbc77000-5adb-11e9-82f2-a7c753a461fe.png)

![image](https://user-images.githubusercontent.com/4889856/55829248-3cbf8480-5adc-11e9-8204-f8cd00d3bf2c.png)

## Consuming repo
Shopify Web

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by lemonmade** [comment]
I think this is fixed, but can sometimes also be indicative of having multiple versions of `@types/react` in the project.
