### ISSUE TITLE
[react-form-state] Unable to validate required field on an initially empty field

### ISSUE THREAD

**Issue by jim-chou-shopify** [Shopify/quilt#652]
## Overview
Unable to validate required text field if it's initially empty, because validation is not fired on blur if field is  not dirty.

**Steps to reproduce:**
- type some text in the required text field
- remove the text

![Required field](https://user-images.githubusercontent.com/39597748/56111690-dc3ea600-5f26-11e9-9819-4e1fad4bc07a.gif)

**It works if the required text field has initial value:**

![Required field with initial value](https://user-images.githubusercontent.com/39597748/56113183-1c078c80-5f2b-11e9-8778-c41aebda2bc4.gif)

### Expectation
Field should be validated on blur.

Redux-form: (https://redux-form.com/6.0.2/examples/syncvalidation/)
>You will probably only want to show validation errors once your field has been touched, a flag that is set for you by redux-form when the onBlur event occurs on your field. When you submit the form, all the fields are marked as touched, allowing any of their validation errors to show.

## Consuming repo
- Web

**Comment by TheMallen** [comment]
Yeah, we really need to change the validation to run when `touched` is true instead of `dirty`.
