### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'shop' in undefined / koa-shopify-graphql-proxy

### ISSUE THREAD

**Issue by davetron5000** [Shopify/quilt#658]
## Overview

Following the tutorial, when I get to the part of https://help.shopify.com/en/api/tutorials/build-a-shopify-app-with-node-and-react/fetch-data-with-apollo where we add koa-shopify-graphql-proxy (the section titled Set up GraphQL), the sample app starts giving internal server errors with the above error:

```
TypeError: Cannot use 'in' operator to search for 'shop' in undefined / koa-shopify-graphql-proxy
```

As of this writing version 3.0.1 is what gets installed.  Downgrading to 3.0.0 does not fix it, but downgrading to 2.1.5 *does* get past the issue.

I'm sorry if this isn't super helpful—I'm following the tutorial, which doesn't really explain what any of the code is supposed to do, so I have no idea how to debug anything.  I just get a stack trace that doesn't not come from my code.

I'm pretty certain if you follow the tutorial you will experience this issue. [At least a few others](https://community.shopify.com/c/Shopify-APIs-SDKs/TypeError-Cannot-use-in-operator-to-search-for-shop-in-undefined/m-p/502997/highlight/false#M32625) have noticed this.

## Consuming repo

> What repo were you working in when this issue occurred?

...

## Labels

- [ ] Add the `Type: Bug` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by nscmnto** [comment]
Same issue here, in the same section. Downgrading to 2.1.5 solves it, but I'm still trying to figure out where's the error coming from.

**Comment by sebike88** [comment]
The issue seems to come from the `shopify-graphql-proxy.js` file.
`shop` is now using an `in` operator looking for the 'shop' string and 'proxyOptions.shop' is undefined.
Not sure i understand the reason behind the implementation.

**Comment by ralphilius** [comment]
You need to define the proxy option like below:

`server.use(graphQLProxy({version: '2019-07'}))`

You can change the version value with these options: '2019-04', 'unstable'  'unversioned'

**Comment by MladenJanjetovic** [comment]
There was recent update in the tutorials
        ```server.use(graphQLProxy({version:` ApiVersion.October19}));```

Still having the same issue.

**Comment by ismail-syed** [comment]
The solution seems to be highlighted by @ralphilius. Please re-open if the issues still persists.

**Comment by jamesvsshark** [comment]
Make sure you specify the version of the graphQLProxy to use and also be sure you don't have it defined twice in the file.

This works for me as of today:


`server.use(graphQLProxy({ version: ApiVersion.April20 }));`
