### ISSUE TITLE
can not apply style on top level component

### ISSUE THREAD

**Issue by jetblack1** [Shopify/quilt#684]
Package: shopify/polaris

## Overview
When using next.js with the polaris framework there is a div created without any id to control the style. My app is a clone of this [repo](https://github.com/Shopify/shopify-demo-app-node-react)

## Motivation
It would be nice for applying a relative `height` so that child elements can inherit from it.
Have a look at the below screenshot

![image](https://user-images.githubusercontent.com/33558024/57162102-8c4c5400-6ded-11e9-982b-2e78927cfbed.png)

**Comment by lemonmade** [comment]
Hey @jetblack1, could you open this issue in https://github.com/Shopify/polaris-react instead?
