### ISSUE TITLE
Remove casted `act()` when @types/react is updated

### ISSUE THREAD

**Issue by cartogram** [Shopify/quilt#692]
More info: https://github.com/Shopify/quilt/pull/688/files/3175af53f95565ba6f47e5038dbd07dfa186f457#r282502634

**Comment by ismail-syed** [comment]
I believe this is fixed, please re-open if this is still relevant.

**Comment by ismail-syed** [comment]
Nvm, see https://github.com/Shopify/quilt/blob/master/packages/react-testing/src/root.tsx#L26
