### ISSUE TITLE
shopOrigin Cookie not update

### ISSUE THREAD

**Issue by robotshatemonkeys** [Shopify/quilt#700]
## Overview
If I own or manage several shop, when I switch shop and open the app, the cookie shopOrigin is not updated, because the browser and app url still the same: 
 
Example: 
• xxxxx.myshopify.com access the app
• Cookie shopOrigin is set to xxxxx.myshopify.com
• User switch to the shop YYYYY.myshopify.com
• 02_shop.myshopify.com access the app
• A cookie shopOrigin already exists so it is not overridden, and shopOrigin  xxxxx.myshopify.com is sent instead of YYYYY.myshopify.com

**Comment by ismail-syed** [comment]
Hey, can you please provide us with a small app that reproduces this case. Is this still an issue?
