### ISSUE TITLE
Memoize form stuff based on ref to fieldBag rather than just fieldBag

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#705]
If we store a ref to `fieldBag` instead of relying on a closure for it, we can prevent a lot of the callbacks in `react-form` from changing more often than the need to.

cc/ @TheMallen

**Comment by TheMallen** [comment]
This is a super good plan

**Comment by loic-d** [comment]
I believe https://github.com/Shopify/quilt/commit/6a6d3f738f433d366139afbc99b0996ec709393d#diff-8c780e4be32788a79e8942b6595e4178R13 fixed the issue.
