### ISSUE TITLE
[react-i18n] Component not getting translations

### ISSUE THREAD

**Issue by jgodson** [Shopify/quilt#713]
## Overview
This happens frequently when doing in app navigation through our app (react-router).

The first time a component is rendered it stays using the `en` translations and the other translations never show up on the `i18n` object under `translations` even through many re-renders of the component. The same component rendered a second time on the page _does_ have the translations though. Navigating (in-app) and returning will render with the translations properly. Doing a page refresh _usually_ works, but also sometimes causes this same issue. It's definitely much more noticeable when doing in-app navigation though.
<details>
<summary>Screenshot</summary>

![alt](https://screenshot.click/21-45-a180x-i9xmz.jpg)
</details>

## Consuming repo
https://github.com/Shopify/parsnip
PR - https://github.com/Shopify/parsnip/pull/3143

**Comment by andrewlo** [comment]
I'm seeing this issue after updating from v0.11.2 to v1.2.3. I was using the babel plugin on v0.11.2, so that doesn't seem to be the problem.

I see that around 25-50% of the time it renders in English instead of the language set, when doing refresh or navigations within the app

cc @lemonmade

**Comment by lemonmade** [comment]
I need a specific page and reproduction steps to diagnose.

**Comment by jgodson** [comment]
@lemonmade for parsnip, install the app, pick `Esty` as a platform, grab a file from the [fixtures](https://github.com/Shopify/parsnip/tree/master/spec/fixtures/files/etsy) and drag it in. You'll see this behaviour through the regular app flow (run an import by continuing once the file is parsed).
