### ISSUE TITLE
How to get pass verifyRequest with postman 

### ISSUE THREAD

**Issue by alcfy** [Shopify/quilt#733]
As my app contain request other than GET, I try to use Postman to send request to my app. But I cannot do so because when I send a request like
```
POST https://[MY_APP_URL]/products?shop=[MY_TEST_SHOP]
```
`verifyRequest()` will prevent me from going further.

First, I will get a response of javascript which should redirect me to `https://app.shopify.com/services/login/identity` with a bunch of parameters if I'm using browser. 

I try to send a request to such link, and it html/javascript response which supposed to redirect to this link `https://accounts.shopify.com/oauth/authorize` with a bunch of parameters.

And again I send a request to the link above and receive a html response asking me to login with invalid recaptcha and etc, which I am not sure how to proceed.

So how can I establish a valid session and run `verifyRequest()` while sending the request using Postman?

**Comment by ismail-syed** [comment]
I don't believe postman executes JavaScript. Our libraries only support login flows via browsers.
