### ISSUE TITLE
[react-i18n] Pluralization, special case "zero" in English?

### ISSUE THREAD

**Issue by movermeyer** [Shopify/quilt#741]
## Overview

Add special handling for using the "zero" pluralization key in English, similar to [how Rails i18n does](https://guides.rubyonrails.org/i18n.html#pluralization):

```ruby
lookup_key = :zero if count == 0 && entry.has_key?(:zero)
lookup_key ||= count == 1 ? :one : :other
entry[lookup_key]
``` 

Today:
```javascript
new Intl.PluralRules('en-US').select(0)
<- "other"
```

## Motivation

We claim that:

>@shopify/react-i18n handles pluralization similarly to Rails’ default i18n utility.

However, users who have Rails code are not getting the same results as they migrate to React.

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by movermeyer** [comment]
Thoughts? cc @nimzco

**Comment by nimzco** [comment]
Seems like a legitimate use case. The problem should be solved on [`react-i18n`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules) level since `Intl.PluralRules` is a [Draft Spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/PluralRules) (currently solved through a polyfill).

**Comment by nimzco** [comment]
@TheMallen @lemonmade thoughts on this? Here's a quick patch that would solve this: https://github.com/Shopify/quilt/pull/742/files

**Comment by lemonmade** [comment]
Is `zero` a valid entry to come from plural rules, per the spec? I couldn't actually see a formal list anywhere. Is this actually a thing that applies across locales (the suggested patch does not scope it to any particular language or locale)?

**Comment by movermeyer** [comment]
> Is `zero` a valid entry to come from plural rules, per the spec?

I don't think so.

However, Rails has special casing for `zero`, and people use the "zero" key in English in Rails to handle cases like:

```zero: 'no messages',
one: '%{count} message',
other: '%{count} messages'```

https://guides.rubyonrails.org/i18n.html#pluralization

We claim that:

> @shopify/react-i18n handles pluralization similarly to Rails’ default i18n utility.

However, users who have Rails code are not getting the same results as they migrate to React.

**Comment by lemonmade** [comment]
Yes, I understand that point, however being 100% compatible with Rails is not an explicit goal (as I think is clear by us handing pluralization `similarly`, not `identically`). This might be a case where it makes sense, but feels weird to me to do this. As an English speaker, I agree that the `zero` message here is obviously preferable. But does this hold true for other languages? Are there are special case plural rules for other languages we are ignoring? What is the impact on translators if our English translations contain a key that will literally never be used by any other locale?

**Comment by donnielrt** [comment]
Is it true that the zero message is English-specific? I feel like it's a common enough language convention, as in @movermeyer's example.

Without a zero-pattern, there are strings that will require extremely verbose manual pluralization. [Here's an example](https://github.com/Shopify/web/pull/14625/files#diff-8fd2ab29abcda58178be99d6839c6e4dR16).

**Comment by lemonmade** [comment]
I have no idea what the rules are for other languages. I was mostly responding to the initial comment which indicated this would just be for English:

> Add special handling for using the "zero" pluralization key in English

**Comment by donnielrt** [comment]
> I have no idea what the rules are for other languages. I was mostly responding to the initial comment which indicated this would just be for English:

Ah, gotcha 👍

**Comment by movermeyer** [comment]
I realized that didn't actually know if `zero` was a legit key for any languages.

Grepping the CLDR data from [shopify-i18n](https://github.com/Shopify/shopify-i18n/blob/master/data), `zero` seems to be used by: `ar` (Arabic), `cy` (Welsh), `ksh` (Colognian), `lag` (Langi), `lv` (Latvian), `prg` (Prussian).

**Comment by movermeyer** [comment]
Instead of adding support for `zero` to React I18n, We've gone the other way, and disallowed the use of pluralization keys that aren't required by the source language.
