### ISSUE TITLE
koa-shopify-auth: redirect if no shop param is present?

### ISSUE THREAD

**Issue by ryanlanglois** [Shopify/quilt#745]
When using, `koa-shopify-auth` I get the message `Expected a valid shop query parameter` when I navigate to `/auth` without a `shop` param.

I'm looking for a way to intercept the `/auth` request or redirect to a different screen if there's no shop param present. That way, I'll be able to prompt a user to enter their shop URL instead of showing an error.

Is there a way to do this?

**Comment by kvindasAB** [comment]
Why don't you catch the url before assigning it to the middleware?

Something like this:

```
server.use(async (ctx, next) => {
        const queryShopMissing = somevalidation_here....
        if (queryShopMissing) { dosomething here... }
        const middleware = verifyRequest({
            authRoute: '/shopify/auth',
            fallbackRoute: '/'
        });
        return middleware(ctx, next);
    });

```

**Comment by ryanlanglois** [comment]
Thanks @kvindasAB, I'll give that a shot. Very new to this so I appreciate the help!

**Comment by ryanlanglois** [comment]
@kvindasAB so I've added the `fallbackRoute` to the `verifyRequest` middleware but that results in an endless redirect loop, and I'm not sure why.

**Comment by kvindasAB** [comment]
Hello @ryanlanglois ,

I had the same issue myself, the way Im dealing with it, is that the fallbackRoute is not being applied the middleware for shopify auth.

So basically I have a prefix `/shopify/` for the embedded app, and outside shopify is just public pages.

The fallback is redirected to root, so it is a public page, that way I was able to fix the redirect issue.

**Comment by ryanlanglois** [comment]
@kvindasAB do you have example code for how you're not applying the shopify auth middleware to your fallbackRoute?

**Comment by kvindasAB** [comment]
Hello @ryanlanglois is relatively easy.

You need to setup a middleware prefix, so that it executed only on `/shopify prefix`

I validate the url prior to applying the middleware though.
Do you see the `isUrlPublic` call.

```
server.use(async (ctx: any, next: any) => {
        const isPublicUrl = isUrlPublic(ctx.url);
        if (isPublicUrl) { return next(); }
        const shopifyAuth = await createShopifyAuth({
            prefix: '/shopify',
            ....
            afterAuth(ctx: any) {
                ...
                ctx.redirect('/shopify');
            },
        });
        return shopifyAuth(ctx, next);
    });
```

isUrlPublic has a very simple code:

```
function isShopifyAdminUrl(url: string) {
    return url.indexOf('/shopify') > -1;
}

function isUrlPublic(url: string) {
    return !isShopifyAdminUrl(url);
}
```

I do the same validation on the verifyRequest middleware

```
server.use(async (ctx: any, next: any) => {
        const isPublicUrl = isUrlPublic(ctx.url);
        if (isPublicUrl) { return next(); }
        const middleware = verifyRequest({
            authRoute: '/shopify/auth',
            fallbackRoute: '/'
        });
        return middleware(ctx, next);
    });
```

Basically what Im trying to do is that, if the url is adminUrl so with`/shopify` I will apply all middleware.

Otherwise I will just let the request pass by and be processed as a public page.

**Comment by ismail-syed** [comment]
I'd suggest trying out @kvindasAB's suggestion. Feel free to re-open that doesn't help.
