### ISSUE TITLE
[react-i18n] Support Polaris recommended data/time formatting

### ISSUE THREAD

**Issue by darrenhebner** [Shopify/quilt#761]
## Overview
The Polaris guidelines have some pretty specific recommendations around how to format date and time. I'm wondering if we think the `react-i18n` library should be updated to reflect this. 

It doesn't look like anyone has actually followed the Polaris guides yet. I'm unsure how these guides would translate to other languages.

They recommend the following:
- `Less than 1 min`: Just now
- `1 min to 60 min`: 13 minutes ago
- `Today`: 10:30 am
- `Yesterday`: Yesterday at 10:30 am
- `In the last 7 days`: Friday at 10:30 am
- `7 days to 1 year`: Aug 14 at 10:30 am

More than 1 year: Aug 14, 2016

## Motivation
I have a design that calls for this formatting.

<img width="1079" alt="Screen Shot 2019-06-20 at 12 01 32 PM" src="https://user-images.githubusercontent.com/4441303/59863681-31e26500-9353-11e9-95c8-c66f16505bcc.png">

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by darrenhebner** [comment]
I just found the `DateTime` component in `web` that looks like it handles this. So I may not need this change after all.

**Comment by rexmac** [comment]
Solved by https://github.com/Shopify/quilt/pull/405?

**Comment by darrenhebner** [comment]
That is exactly what I was looking for! I swear that wasn't in the README before 😄
