### ISSUE TITLE
[I18N] Create a name formatter module

### ISSUE THREAD

**Issue by mehdi-loup** [Shopify/quilt#787]
## Overview

This module will offer you a way to display user name regarding locale preferences.

## Type

- [x] New feature
- [ ] Changes to existing features

## Motivation

In country like 🇯🇵 for example, it's offensive to display first_name before last_name. 

### Area

- [x] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [x] Tag it with the `Package: <package_name>` label.

- Is it related to a new package?
  - [ ] Tag it with the `New package` Label

---

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by mateus** [comment]
@goldenson do you know if the I18n team is looking towards adding something like this to Web? Based on this PR https://github.com/Shopify/shopify/pull/207667

**Comment by goldenson** [comment]
@nimzco @adjnor do you know if somebody is working on that?

**Comment by adjnor** [comment]
Not that I know of 🤔

**Comment by nimzco** [comment]
That could be a good first task for Benoit maybe.
cc @trishrempel

**Comment by benoitzohar** [comment]
Looking into it 👍
