### ISSUE TITLE
Create self-serializers

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#796]
## Overview
We loosely document the "self-serializer" pattern for projects consuming `@shopify/react-html`
in [the readme of the project](https://github.com/Shopify/quilt/tree/master/packages/react-html#in-your-application-code), but we do not provide any out of the box currently, meaning they need to be reimplemented by consumers across mutliple projects. With [`@shopify/react-server`](https://github.com/Shopify/quilt/compare/react-server?expand=1) on the way we will be leaning into projects handling serialization entirely through this pattern, so we should act now.

These serializers should live on their own outside of their target libraries or `react-html` to avoid impacting their bundle size or making dependency management worse on consumers.

## Libraries we should provide serializers for
- [x] `@shopify/react-i18n`
- [x] `@shopify/react-graphql`
- [ ] `react-history`
- [x] `react-csrf` https://github.com/Shopify/web/blob/master/packages/@shopify/react-csrf/Provider.tsx
- [ ] `browser` https://github.com/Shopify/web/blob/master/app/foundation/Browser/Browser.tsx

**Comment by michelleyschen** [comment]
I am going to close this since most are done and we have a goos strategy going forward
