### ISSUE TITLE
Prefetcher needs to be throttled

### ISSUE THREAD

**Issue by phuongvu** [Shopify/quilt#804]
## Overview
Currently it looks like I can trigger an indefinite amount of prefetches just by hovering the mouse pointer in and out an item on a list. Refer to the screenshot below in marketing section's marketing activity index page:

<img width="1580" alt="Screen Shot 2019-07-22 at 3 49 26 PM" src="https://user-images.githubusercontent.com/604517/61660631-5013eb80-ac98-11e9-9f8f-97c77bed2144.png">

This would potentially cause GraphQL throttle issue. One solution is to throttle prefetcher, i.e., re-prefetch after 30 seconds or 1 minute since it is unlikely that data will be changed within such short amount of time.
## Motivation
Avoid GraphQL throttle issue.

> What inspired this enhancement? What makes you think this should be in `quilt`?
@darrenhebner referred me to this repo.

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by lemonmade** [comment]
I am not sure if this is really an issue. The prefetcher waits for a link to be [hovered for 150ms](https://github.com/Shopify/quilt/blob/master/packages/react-async/src/Prefetcher.tsx#L19) before triggering the prefetch. Yes, you can make it look painfully stupid by hovering for over 150ms over each item in sequence, but is that a realistic user interaction?
