### ISSUE TITLE
[react-i18n] locale aware sentence conversion

### ISSUE THREAD

**Issue by tayre** [Shopify/quilt#807]
## Overview

I don't believe there is a mechanism to join an array while being internationally aware. 

In [Rails](https://github.com/rails/rails/blob/5a9301ce47f1117c8d457cad2b850f932bf7f518/activesupport/lib/active_support/core_ext/array/conversions.rb#L61), we can define translated word connectors, which `#to_sentence` respects for a given locale.

```yaml
#   es:
#     support:
#       array:
#         words_connector: " o "
#         two_words_connector: " y "
#         last_word_connector: " o al menos "
```

```ruby
['uno', 'dos'].to_sentence(locale: :es)
# => "uno y dos"

['uno', 'dos', 'tres'].to_sentence(locale: :es)
# => "uno o dos o al menos tres"
```

## Type

- [x] New feature

## Motivation

Having a dynamic list which needs to be presented to the user as a sentence, in their preferred language, seems like a common use case. 

/cc @Shopify/intl-languages, 
/fyi @adjnor @trishrempel (this might be a reasonable port of Rails code that already exists)

@lemonmade would love your thoughts on this

**Comment by lemonmade** [comment]
This feature is part of the `Intl.ListFormat` API (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ListFormat). I'd love to have it, but unfortunately the browser support is very poor. There may be some suitable polyfills, but that would need to be sorted out, hopefully without much performance cost.
