### ISSUE TITLE
[react-async] Allow an async hydration component to never rehydrate

### ISSUE THREAD

**Issue by lemonmade** [Shopify/quilt#848]
There is a valid use case for components that never rehydrate. A static footer of links, for example, might be an ideal candidate to be server rendered but never gain any additional interactivity on the client side. This should be doable fairly easily by adding a `DeferTiming.Indefinite` or similar, and then respecting that by never rendering any of the loading logic for the component.

**Comment by Patil2099** [comment]
@lemonmade  Can I work on this?

**Comment by lemonmade** [comment]
@Patil2099 absolutely! Feel free to ping me on a PR, or let me know if you have additional questions.
