### ISSUE TITLE
Make auth middleware mountable, remove prefix option

### ISSUE THREAD

**Issue by TheMallen** [Shopify/quilt#85]
Right now we are generating the callback redirect for the `koa-shopify-auth` middleware using `ctx.path`. This is hostile to cleanly composing it using `koa-mount`. 

At the moment we support a custom `prefix` configuration option,  but it seems like bette citizenry with the framework to just use the simplest possible path in our own logic and then support `koa-mount` for namespacing our routes if a user wants to.

**Comment by michenly** [comment]
Done
