### ISSUE TITLE
Give SERVICE_URL a more descriptive name

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#855]
## Overview
Rename a variable to make its purpose clearer, and easier to grep for.  e.g., `REACT_SERVER_SERVICE_URL`.

## Motivation
The PR to use `process.env` defaults (#852) will be updated to use something like `process.env.REACT_SERVER_PORT` / `process.env.REACT_SERVER_IP`.  We should make the gem's config jibe with this convention.

cc @TheMallen

**Comment by TheMallen** [comment]
I think we will probably just also use the same two you outline for #852 :)
