### ISSUE TITLE
Find and 🔥stale private versions that block @shopify/react-server adoption

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#861]
## Overview
Shopify users running `yarn add @shopify/react-server` may be blocked by privately published versions of our dependencies.  e.g., `@shopify/network@1.0.2` fouls up my install.

I haven't dug further than this, but it's possible that more blocking packages exist.

## What do?
1. Ping teams using stale private versions and ask them to help with updating to a public version
2. If a team can't upgrade, publish a public version and ask them to update yarn.lock to point at it
3. 🔥 

## Motivation

This adds a high amount of friction for developers trying to self-serve.  It also adds bulk to "how to set up SSR" docs.

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
v1.0.2 is getting ~1000 installs a week. Mostly CI contains but a fair amount on downloads

<img width="535" alt="Screen Shot 2019-08-16 at 9 59 23 AM" src="https://user-images.githubusercontent.com/6130700/63172831-909f2480-c00c-11e9-9319-4aa796bd6971.png">

**Comment by ismail-syed** [comment]
**Upgraded:** 
- https://github.com/Shopify/article-88/pull/75
- https://github.com/Shopify/google-shopping/pull/4954
- Created an issue in https://github.com/Shopify/web-tech-playground/issues/3, a non-prod app
 
I haven't found any other repos using `@shopify/network@1.0.2`

**Comment by ismail-syed** [comment]
* All projects using `@shopify/network@1.0.2` have upgraded to a public version 
* `@shopify/network@1.0.2` on the private registry has been archived. 
* Verified that the following does now  foul installs
```
 yarn add @shopify/sewing-kit @shopify/react-server react react-dom typescript @types/react @types/react-dom @shopify/polaris
```
