### ISSUE TITLE
Automated Shipit deploys

### ISSUE THREAD

**Issue by ismail-syed** [Shopify/quilt#867]
## Overview

Yesterday we had to backfill the releases that should have been deployed in https://github.com/Shopify/quilt/commit/c17467957eaa0fe82a7b71c0f7319885453601ef. This is because in Shipit, we had forgotten to _deploy_ c17467957eaa0fe82a7b71c0f7319885453601ef in the queue before _deploying_ subsequent "Publish" commits.

When commits pile up, it can be easy to miss "Publish" commits. Ideally, the author of that "Publish" commit deploys on shipit, but sometimes we forget (slow CI, jumping into meeting/interviews, etc). When this happens we have to manually find out what went wrong, which packages to backfill etc. Even backfilling has it's flaws because the `latest` tag on the package is updated to the _backfilled_ version. 

## What to do?

We should explore & builds tooling to support automating monorepo deploys on Shipit. 

- Continuously _Deploy_ (release packages) on tagged "Publish" commits with passing CI. 
- Noop on "Publish" commit tags

Reading through slack messages in #shipping-pipeline, we do something similar for gems

> It triggers a deploy for every pushed commits, however if the commit doesn't bump the genspec version it simply noop.

**Comment by TheMallen** [comment]
Moving out of this sprint
