### ISSUE TITLE
[React-testing] Misleading type on `.find`

### ISSUE THREAD

**Issue by MateusJabour** [Shopify/quilt#869]
## Overview

On version `1.7.4`, when trying to find an `img` component using the `src` prop:

```js
      wrapper.find('img', {
        src: imagePath,
      }),
```

An error is shown saying: `'src' does not exist in type 'Partial<HTMLAttributes<"img">>'`

## Consuming repo

> What repo were you working in when this issue occurred?

https://github.com/Shopify/online-store-web

Bump PR: https://github.com/Shopify/online-store-web/pull/4361

## Checklist

- [x] Please delete the labels section before submitting your issue
- [x] I have described this issue in a way that is actionable (if possible)

**Comment by MateusJabour** [comment]
@patsissons hey! I think the change with `Props` vs `PropsFor` introduced this issue (https://github.com/Shopify/quilt/commit/d02fe48fb5533e5f1868440b85ce3a4114bca9df#diff-9e394c875658d30f21bf9a906434ecf2). I've tested that in `1.7.3` I don't have this issue, only in `1.7.4`

Let me know if you need anything from my end. 👍

**Comment by patsissons** [comment]
due to the way that `react-testing` uses props extraction, we may want to consider just re-adding the original `useful-types` helper into `react-testing` internally.

```tsx
export type PropsFor<T> = T extends keyof JSX.IntrinsicElements
  ? JSX.IntrinsicElements[T]
  : T extends string
    ? HTMLAttributes<T>
    : T extends ComponentType<infer Props> ? Props : never;
```
