### ISSUE TITLE
Creat `react-csrf` package

### ISSUE THREAD

**Issue by michelleyschen** [Shopify/quilt#891]
Move this boilerplate into its own package

https://github.com/Shopify/web-rails-proving-ground/tree/master/app/ui/utilities/csrf

**Comment by TheMallen** [comment]
Even if we do make a separate package, I'm wondering if this should be provided in `@shopify/react-network' (and thus `@shopify/react-server`), with a `useCsrfToken` hook and with the provider automatically grabbing it and rendering a provider based off of the `X-CSRF-Token` being present.

Ideally the consumers of the `@shopify/react-html` family of libraries can internalize that they can grab whatever stuff makes sense to off of the incoming request using the tools in that library, and not have to worry too much about the details of how we get them or serialize them.
