### ISSUE TITLE
have a way to find `App` props when using `react-server-webpack-plugin`

### ISSUE THREAD

**Issue by michelleyschen** [Shopify/quilt#897]
It was difficult to find what Props the default `App` would have and we should also find a way to throw some kind of error if the `App` type have mismatch type (ie. have any mandatory prop)

Current type:
export interface AppProps {
  server?: boolean;
  locale?: string;
  location?: string;
}

**Comment by TheMallen** [comment]
Instead of providing an interface for this we should work to prevent having to pass in props and let apps just use the hooks from `@shopify/network` to get what they need.
