### ISSUE TITLE
[koa-shopify-auth] accessToken expires in 4hrs

### ISSUE THREAD

**Issue by gkrinc** [Shopify/quilt#930]
## Overview

When installing my app, the `accessToken` returned in the `afterAuth` handler in the `createShopifyAuth` function isn't permanent. Every day when I start working on the app I get 401's until I re-install.

The `ctx.session` value includes a `_expire` property which looks like a unix timestamp that is 4hrs in the future.

I'm using the koa-shopify-auth package v3.1.34

I tried setting the `myShopifyDomain` property in the `createShopifyAuth ` options, but that caused the application to throw other errors.

I have another app that I built using `@shopify/shopify-express` and when I look at the req.session value in `afterAuth` I see that the `_expires` value is `null`.

What am I doing wrong?

**Comment by gkrinc** [comment]
Is no one else running into this problem? I'm wanting to move forward with my app, but I know I'm not going to be able to go live until I get this figured out.

I'm using the example code provided in the package for setting up the server, session and shopifyAuth call. Any suggestions? Is there something messed up with the session? Could I have something misconfigured on the app admin?

**Comment by kirkbackus** [comment]
You need to set `accessMode: "offline"` in your `createShopifyAuth` function.  By default, all access tokens are online tokens set to expire.  This token will not expire.

**Comment by gkrinc** [comment]
Thanks @kirkbackus that was totally the issue. I misread the docs, my fault.
