### ISSUE TITLE
Add an easy util for getting the local from accept-language header

### ISSUE THREAD

**Issue by cartogram** [Shopify/quilt#931]

**Comment by b-ryu** [comment]
I noticed that [this package](https://github.com/opentable/accept-language-parser) is a dependency of `@shopify/react-network`. Does this cover our intended use case or are we looking for something else?

**Comment by ismail-syed** [comment]
> Or are we just looking to wrap that functionality and export it as a separate utility?

I'm _think_ this is what @cartogram intended but it might be worth double-checking with him.

**Comment by cartogram** [comment]
Closed in https://github.com/Shopify/quilt/pull/909
