### ISSUE TITLE
Fix gem list from being deleted in the readme when a new package is created

### ISSUE THREAD

**Issue by cartogram** [Shopify/quilt#948]
## Overview

...

## Motivation

> What inspired this enhancement? What makes you think this should be in `quilt`?

...

## Labels

- [ ] Add the `Type: Enhancement` label to this issue.

### Area

- [ ] Add any relevant `Area: <area>` labels to this issue

### Scope

- Is this issue related to a specific package?

  - [ ] Tag it with the `Package: <package_name>` label.

---

## Checklist

- [ ] Please delete the labels section before submitting your issue
- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by ismail-syed** [comment]
I believe we've fixed this, please reopen if this is still an issue.
