### ISSUE TITLE
First request of a session always fails on `useQuery` calls

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#957]
## Overview
A session's very first request always fails because:
- There is no CSRF token defined for the session
- We create a CSRF token and pass it along to the Node server
- The Node server passes the CSRF token along to GraphQLController
- GraphQLController's CSRF protection tries to validate the passed token against a (non-existent) persisted session token
  - It fails

When the user's first request is rejected, Rails passes back a session + csrf token, and everything works because:
- The session has a _persisted_ csrf token
- Browser requests now contain a session id + csrf token
- ... this csrf token is passed through to Node->GraphQLController with no validation issues

## Consuming repo
beta-buddy

**Comment by TheMallen** [comment]
Fixed via our new reccs around CSRF
