### ISSUE TITLE
Some Node exceptions aren't logged

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#958]
## Overview
In production, beta-buddy the first `useQuery` call for a session fails (#957), but no Node exceptions appear in our production logs.  There should be _something_ about the call out to GraphQLController failing here.

## Consuming repo

beta-buddy

**Comment by ismail-syed** [comment]
Given that we've disabled SSR in beta-buddy, would this be re-producible in web-rails-proving-ground?

**Comment by GoodForOneFare** [comment]
It's not specific to `useQuery`.  To test:
- Create a `server.ts` file that intentionally throws an exception
  - Try to find the exception logs in Splunk
- Revert the above change, and throw an unchecked exception from a component
  - Try to find the exception logs in Splunk

Note that Mat has a PR open in sewing_kit to enable more logging, so you might want to test with that integrated.

**Comment by GoodForOneFare** [comment]
And note that this is behaviour that I observed in passing almost a month ago.  Things may have changed since then, so don't take my word as gospel ¯\\_(ツ)_/¯

**Comment by ismail-syed** [comment]
> Create a server.ts file that intentionally throws an exception

* Working on this one right now. As of now, not seeing any logs in splunk from the server. [test changeset](https://github.com/Shopify/web-rails-proving-ground/commit/2c9f2558ea4cf1bee6c5067d6d76dd964276b297)

> Revert the above change, and throw an unchecked exception from a component

Splunk logs are readable with https://github.com/Shopify/quilt/pull/978

**Comment by ismail-syed** [comment]
> As of now, not seeing any logs in splunk from the serve

Found the logs! Though the server-level exception logs from `server.ts` are chopped up like what was mentioned in https://github.com/Shopify/quilt/issues/959

**Comment by ismail-syed** [comment]
> Create a server.ts file that intentionally throws an exception

We spoke about this yesterday in the pod. If we throw an exception in a server file outside the middlewares (which now captures readbale logging on splunk) it's almost certain that our server will fail to start. When our server fails to start, [shipit will fail on deploy](https://shipit.shopify.io/shopify/web-rails-proving-ground/production/deploys/839899). This is enough for us to write off this concern. 

That said, we still want some reasonable feedback in development. In development, our logs are already visible by default now in `@shopify/react-server` - See https://github.com/Shopify/quilt/pull/978. 

@GoodForOneFare, can we close this off or do you want to verify with `useQuery` in beta buddy first?

**Comment by GoodForOneFare** [comment]
>  it's almost certain that our server will fail to start. When our server fails to start, shipit will fail on deploy. This is enough for us to write off this concern.

I think the conversation concluded with: "shipit failing with no log output will make it very difficult for developers to self-serve startup failures.  We should add _something_ that logs uncaught startup exceptions (i.e., port not available), even if it's not pretty".
