### ISSUE TITLE
Node error traces are unreadable in Splunk

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/quilt#959]
## Overview
Each line of a Node error traces appear as a separate Splunk log line.  This makes them unreadable.

[This Splunk forum](https://answers.splunk.com/answers/705902/why-are-my-multi-line-events-getting-split.html) suggests that adding timing info to logs may help to group them.  

## Consuming repo
beta-buddy, web-rails-proving-ground, etc

**Comment by ismail-syed** [comment]
Do we have any splunk queries to view the logs in question?

**Comment by GoodForOneFare** [comment]
No, because of `some Node exceptions aren't logged` (#958).  You can create a service, add uncaught exception handler, change the middleware's logger to `Verbose`, and log test exceptions before app startup / during app render.

**Comment by ismail-syed** [comment]
web-rails-proving-ground  in prod is updated with `@shopify/react-server@0.5.0`. We now have readable splunk logs with for requests going through`@shopify/react-server`.
