### ISSUE TITLE
Add monorail lib

### ISSUE THREAD

**Issue by michenly** [Shopify/quilt#960]
Since the organization is deprecating Trekkie in favor of monorail.

https://groups.google.com/a/shopify.com/forum/#!searchin/rnd/monorail%7Csort:date/rnd/Z-IkRUBkLzc/RDmdtJsrAgAJ

We will need to extra the set of tooling we build for web into quilt for other project to consumer.

These two links should be a good striating point of figuring out what should be extracted.

Whats in web right now:
https://github.com/Shopify/web/blob/master/app/utilities/monorail.ts

Whats in pos channel:
https://github.com/Shopify/pos-channel/tree/master/app/ui/utilities/monorail

Another thing to consider her is should this go into quilt?
Or be part of the monorail typescript repo: https://github.com/Shopify/monorail/tree/master/lang/typescript

**Comment by lemonmade** [comment]
This should definitely live in the Monorail repo.
