### ISSUE TITLE
Figure out how to add ApolloBridge for migrated SSR App

### ISSUE THREAD

**Issue by michenly** [Shopify/quilt#967]
[`react-effect-apollo`](https://github.com/Shopify/quilt/tree/master/packages/react-effect-apollo) is necessary when using the Query component from react-apollo or @shopify/react-graphql.

I imagine this will be a pattern we want to support for current app that uses Query component but want to upgrade to SSR.

`<ApolloBridge>` should be wrap around the app in both [decorate function](https://github.com/Shopify/web-proving-ground/blob/ada7a16026c16be9e18ad10673e3a16cde4903fa/server/middleware/render-app.tsx#L67) and [streaming respond](https://github.com/Shopify/web-proving-ground/blob/ada7a16026c16be9e18ad10673e3a16cde4903fa/server/middleware/render-app.tsx#L93)

I think we have 3 choices
1. expect the user to wrap it themselve in `<App/>`
2. offer it as part of `@shopify/react-graphql-universal-provider` either by default or as an option. 
3. offer it as part of `@shopify/react-server` either by default or as an option.

**Comment by TheMallen** [comment]
4th option is having the webpack plugin include it.
